### ISSUE TITLE
Packaging issues on Fedora 28

### ISSUE THREAD

**Issue by barberio** [Netatalk/Netatalk#100]
Fedora 28 has started to switch some packaging warnings into failure errors, some of which will effect using Netatalk.

Scripts with relative path shbangs will now cause errors. Scripts that use env or similar to generate paths will cause errors in a future version.

(snippet of attempt to build an rpm)
```
*** ERROR: ./usr/bin/cnid2_create has shebang which doesn't start with '/' (perl)
*** ERROR: ./usr/bin/macusers has shebang which doesn't start with '/' (perl)
*** ERROR: ./usr/bin/asip-status.pl has shebang which doesn't start with '/' (perl)
*** ERROR: ./usr/bin/apple_dump has shebang which doesn't start with '/' (perl)
*** WARNING: mangling shebang in /usr/bin/afpstats from #!/usr/bin/env python to #!/usr/bin/python2. This will become an ERROR, fix it manually!
```

**Comment by barberio** [comment]
Testing a pretty simple patch that fixes this.

**Comment by hat001** [comment]
Try newest netatalk-3.1.11-1.3.fc29.src.rpm .
<http://netatalk.sourceforge.net/wiki/index.php/Netatalk_3.1.11_SRPM_for_Fedora_and_CentOS>

*** WARNING: mangling shebang in /usr/bin/afpstats from #!/usr/bin/env python to #!/usr/bin/python2. This will become an ERROR, fix it manually!

This isn't corrected yet.

**Comment by barberio** [comment]
This should probably still be fixed upstream, since best practice now is to use absolute paths to script binaries detected at compile time, in order to prevent casual per-user environment changes affecting system installed items.

**Comment by rdmark** [comment]
The afpstats script was made python3 compatible with https://github.com/Netatalk/Netatalk/commit/916b515705cf7ba28dc53d13202811c6e1fe6a9e
