### ISSUE TITLE
[2.4] wolfssl: undefined symbol: CAST_cbc_encrypt

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1013]
On debian 12 when built with embedded wolfssl, if you load the DHX library and start up afpd:

```
May 20 11:15:24 deb12 afpd[126177]: uam_load(uams_dhx.so): failed to load: /usr/local/lib/x86_64-linux-gnu/netatalk/uams_dhx.so: undefined symbol: CAST_cbc_encrypt
May 20 11:15:24 deb12 afpd[126177]: uam: uams_dhx.so load failure
```

Will test and see if 3.x and other OSes are affected.

**Comment by dgsga** [comment]
@rdmark, this one has got me completely stumped. The embedded ssl code is identical in both v2 and v3 so why should it not work in v2 if it works in v3? I have tested v3 main on Debian and DHX authentication on Mac OS 9 works fine. Have I missed any differences between the relevant code in 2 and 3?

**Comment by rdmark** [comment]
@dgsga That's doubly weird, because on the same Debian 12 system, I have netatalk3 working perfectly fine with wolfssl-powered DHX, on the latest commit c3e27fadcf26f1948db863d4020d5c0633a91a8d ...

Are you on a different code revision by any chance?

**Comment by rdmark** [comment]
Curiously, the RandNum UAM also fails to load, but with what I believe is a symbol in Cracklib...

```
May 21 09:55:17 deb12 afpd[478791]: uam_load(uams_randnum.so): failed to load: /usr/local/lib/x86_64-linux-gnu/netatalk/uams_randnum.so: undefined symbol: FascistCheck
May 21 09:55:17 deb12 afpd[478791]: uam: uams_randnum.so load failure
```

When building without cracklib support the library loads fine and can be used. So something's up with symbol references when linking with the bundled wolfssl.

**Comment by dgsga** [comment]
Got to the root of it. The clang linker on macOS automatically links the DHX and RANDNUM UAM modules to libatalk when embedded SSL is true, but gcc's linker doesn't so we have to ensure they link with build_rpath: and install_rpath: kwargs like we did with the executables.
Also, the gcc linker requires that the cast functions library be built, whereas clang ld seems quite happy just to use the cast.h header.
So the code is fixed now, will create PR when testing complete. 🌞

**Comment by rdmark** [comment]
Another round of cross platform C linking shenanigans! A never ending source of head scratchers. 

Great job figuring that one out.
