### ISSUE TITLE
Netatalk 2 Docker copy issues

### ISSUE THREAD

**Issue by BrnDnlsn** [Netatalk/netatalk#1035]
**Describe the bug**
When trying to copy files to fileshare it most of the times stalls during copy. 

**To Reproduce**
Connect to share and copy file to it. 

**Expected behavior**
The file should copy to the share. 

**Environment**
 - Synology DSM 7.2 Docker
 - Mac OS 7.1
 - Netatalk Version 2.3x

**Logs**
Log1: limitsize is removed but volsizelimit is active in configuration
Log2: limitsize is active but volsizelimit is removed in configuration
Log3: both volsizelimit and limitsize is removed in configuration

[log1.html.zip](https://github.com/Netatalk/netatalk/files/15470456/log1.html.zip)
[log2.html.zip](https://github.com/Netatalk/netatalk/files/15470458/log2.html.zip)
[log3.html.zip](https://github.com/Netatalk/netatalk/files/15470459/log3.html.zip)

**Comment by rdmark** [comment]
@BrnDnlsn Apologies for not following up sooner. We're in the middle of preparing two major releases, but I will get back to your logs in a few days!

**Comment by rdmark** [comment]
@BrnDnlsn Maybe this is an obvious question, but is the observed behavior exactly the same between all three scenarios?

Also please remind me what happens when you enable both options?

**Comment by BrnDnlsn** [comment]
@rdmark If volsizelimit isn't there almost all files I want to copy to the share won't because it will tell me there is not enough space. 
Both options does not make any difference. The copy will stall just before it is finished.

**Comment by rdmark** [comment]
@BrnDnlsn This is a weird one. In all three scenarios, I can see that a DSI stream is set up to transfer "DaynaPORT 7.5.3.img" and the CNID database is starting to get written to. But at one point it gives up and sends an AFP_DELETE command to remove the file. There is no obvious hint in either of the logs that I can see which points to the root cause.

One idea that springs to mind is some kind of corner case file system permissions problem, such as in the AppleDouble database. Can you try recursively setting permissions to `2755` on the shared volume directory and see if that gives you a different behavior?

Other ideas would be to rebuild the CNID database and put it in a different place on the file system, using the `dbpath:` option.

**Comment by rdmark** [comment]
If you are feeling adventurous, I have a prerelease version of 2.4 on Docker Hub, called "multicasttest"

`docker pull netatalk/netatalk2:multicasttest`

https://hub.docker.com/r/netatalk/netatalk2/tags

It should be very stable. But standards warnings about taking backups etc. apply. :)

**Comment by BrnDnlsn** [comment]
Unfortunately I have the same issue on the prerelease version. Just for fun I did a test on Mac OS 9.04 from Sheepshaver and it worked flawlessly.

**Comment by BrnDnlsn** [comment]
Did some more testing. When running Mac OS 7.5.5 in Basilisk II it also works without any issues. Seems to be Mac OS 7.1 (with Open Transport 1.3.1 and AppleShare Client 3.7.4) that isn't compatible some how.

**Comment by rdmark** [comment]
Interesting! Now when I think of it, AppleShare Client 3.7.4 isn't officially compatible with System 7.1. According to Apple's documentation, the 3.7.x release series requires System 7.5.3 or later.

Would you be able to try installing [AppleShare Client 3.0.3](https://macintoshgarden.org/apps/appleshare-30) and try again? Of course, this means AFP-over-AppleTalk only...

There is some recent discussion on this topic over at https://68kmla.org/bb/index.php?threads/netatalk-2-3-0-available.46318/page-8

**Comment by BrnDnlsn** [comment]
I would be happy to test but unfortunately AppleTalk does not work for me in my Netatalk installation in Docker and I wouldn't know where to start troubleshooting it. IGMP snooping is already disabled on my Wi-Fi though so it could very well be something on my Synology.

**Comment by rdmark** [comment]
Oh yeah, this rings a bell...

So the Synology NAS and the Mac are connected via a wireless AP? AppleTalk packages are known to get mangled by most WiFi APs.

**Comment by BrnDnlsn** [comment]
Yes, exactly. I have a BlueSCSI installed in the Mac. I was under the impression that this could work. 

Currently I'm trying to configure macvlan on my Docker setup. I read that utilizing macvlan maybe could be a solution for getting AppleTalk working. I keep receiving errors though: "atalkd: can't get interfaces, exiting" is one of them and fiddling with ATALKD_INTERFACE unfortunately just tells me that the requirements for starting the AppleTalk service isn't met.

**Comment by rdmark** [comment]
There is an epic discussion thread over at 68kmla on this topic: https://68kmla.org/bb/index.php?threads/what-is-the-technical-reason-why-ddp-appletalk-doesnt-work-with-wifi.45811/

In short: Most Wifi equipment assumes all network frames are Wifi frames, and mangles DDP frames.

As for the "can't get interfaces" error, have you made sure the docker container has all the right permissions to access host network interfaces?

**Comment by BrnDnlsn** [comment]
I think the conclusion is that AppleTalk over IP does not work properly on Mac OS 7.1 or earlier. I was able to connect but not able to perform any copying without errors. 

Thank you very much for all the help and inputs. I think this issue can be closed.

**Comment by rdmark** [comment]
Apologies that we couldn't help you get this working...

I updated our own wiki docs to no longer suggest that ASIP can work on System 7.1.
