### ISSUE TITLE
After 3.2 I can't use a password longer than 8 chars

### ISSUE THREAD

**Issue by marcosvrs** [Netatalk/netatalk#1066]
**Describe the bug**
Before 3.2, I had a password 32 chars length. Now it fails when I run the docker machine with my password.

**To Reproduce**
Set a password longer than 8 chars in AFP_PASS env variable.

**Expected behavior**
It allows more secure password length

**Environment**
 - Server OS: Ubuntu 24.04
 - Client OS macOS Sonoma 14.5
 - Netatalk Version 3.2

**Logs**
```
*** Setting up users and groups
chpasswd: password for 'marcosvr' changed
afppasswd: max password length is 8.
```

**Comment by rdmark** [comment]
Thanks for reporting! This was an oversight on my behalf, so apologies for the inconvenience. I will attempt a hotfix to the docker image in an hour or so.

The technical explanation is: We added the Random Number UAM to the docker configuration, to enable authentication with older Classic Mac OS clients. However, Random Number has an 8 char password length limitation, and I didn't anticipate that the password utility would stop the Docker entrypoint script entirely when using a longer password.

**Comment by rdmark** [comment]
@marcosvrs I pushed a new 3.2.0/latest image, amd64 only for now. Would you be able to test it your environment?

**Comment by marcosvrs** [comment]
@rdmark Thank you very much for the fast fix!
I'm having another issue with my connection being dropped on 3.2 only. I will open a new ticket soon, but before I do it, I'm making sure I have my latest backup done.
After that, I will test your fix and open a new issue with detailed logs from my connection problem.

**Comment by marcosvrs** [comment]
It works! Thanks!

**Comment by rdmark** [comment]
That's great, thanks for testing!

Let me keep this ticket open until the fix has been merged to all relevant branches.
