### ISSUE TITLE
The "maintainers" are Posers

### ISSUE THREAD

**Issue by mfwitten** [Netatalk/Netatalk#107]
The supposed "maintainers", @hat001 and @slowfranklin, are worthless poser fools who don't give a shit about this project.

If they cared, they'd set up a regular schedule for handling input from third parties.

Specifically, they'd say "Hey, there are 2 of us; how about we split the week into roughtly 2 halves?" @hat001 could take *Mondays*, and @slowfranklin could take *Thursdays*; on his day, each maintainer could spend but 30 minutes considering input from third parties and but 30 minutes responding to that input, for a total of 1 hour every week, which would be 1/168 (or less than 0.6%) of one's life.

Of course, if these fakers decided that they couldn't make this work, they could at least have the decency to say "Hey. We aren't any good at time management, despite being Germans. So, let's find more people to help us maintain this project." But, they are fakers; so, they'll never do this.

FSCK YOU.

You're the reason we can't have nice things.

**Comment by slowfranklin** [comment]
Wow, you're raising a few good points, but you're tone is unacceptable. So please calm down and let's continue discussion in a civilized manner. Thanks!
