### ISSUE TITLE
Incorrect GPL address

### ISSUE THREAD

**Issue by knight-of-ni** [Netatalk/Netatalk#109]
Source files contain an outdated GPL mailing address.

```
$ rpmlint netatalk*.rpm | grep incorrect-fsf
netatalk.x86_64: E: incorrect-fsf-address /usr/share/licenses/netatalk/COPYING
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/etc/afpd/afprun.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/include/atalk/ftw.h
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/include/atalk/queue.h
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/include/atalk/vfs.h
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/adouble/ad_recvfile.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/compat/strlcpy.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charcnv.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/generic_cjk.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/generic_cjk.h
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/generic_mb.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_centraleurope.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_chinese_simp.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_chinese_simp.h
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_chinese_trad.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_chinese_trad.h
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_cyrillic.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_greek.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_hebrew.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_japanese.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_japanese.h
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_korean.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_korean.h
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_roman.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_roman.h
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_turkish.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/iconv.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/utf8.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/util/fault.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/util/ftw.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/vfs/extattr.c
netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/vfs/vfs.c
netatalk-devel.x86_64: E: incorrect-fsf-address /usr/include/atalk/vfs.h
```

Would upstream consider replacing the text in the named source files from:
```
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
```
with the text:
```
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
```

**Comment by slowfranklin** [comment]
On Wed, Nov 28, 2018 at 05:20:11AM -0800, Andrew Bauer wrote:
>Source files contain an outdated GPL mailing address.
>
>```
>$ rpmlint netatalk*.rpm | grep incorrect-fsf
>netatalk.x86_64: E: incorrect-fsf-address /usr/share/licenses/netatalk/COPYING
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/etc/afpd/afprun.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/include/atalk/ftw.h
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/include/atalk/queue.h
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/include/atalk/vfs.h
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/adouble/ad_recvfile.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/compat/strlcpy.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charcnv.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/generic_cjk.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/generic_cjk.h
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/generic_mb.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_centraleurope.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_chinese_simp.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_chinese_simp.h
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_chinese_trad.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_chinese_trad.h
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_cyrillic.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_greek.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_hebrew.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_japanese.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_japanese.h
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_korean.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_korean.h
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_roman.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_roman.h
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/charsets/mac_turkish.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/iconv.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/unicode/utf8.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/util/fault.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/util/ftw.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/vfs/extattr.c
>netatalk-debuginfo.x86_64: E: incorrect-fsf-address /usr/src/debug/netatalk-3.1.11/libatalk/vfs/vfs.c
>netatalk-devel.x86_64: E: incorrect-fsf-address /usr/include/atalk/vfs.h
>```
>
>Would upstream consider replacing the text in the named source files from:
>```
>You should have received a copy of the GNU General Public License
>along with this program; if not, write to the Free Software
>Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
>```
>with the text:
>```
>You should have received a copy of the GNU General Public License
>along with this program; if not, write to the Free Software
>Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
>```

sure! Can you provide a patch?

-slow

-- 
Ralph Boehme, Samba Team                https://samba.org/
Samba Developer, SerNet GmbH   https://sernet.de/en/samba/
GPG-Fingerprint   FAE2C6088A24252051C559E4AA1E9B7126399E46

**Comment by slowfranklin** [comment]
Fixed in master.
