### ISSUE TITLE
[2.4] atalkd: Use multicast on Linux

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1091]
atalkd has a workaround that originates in the 2.0 development cycle which forces ALLMULTI on interfaces that atalkd is using.

This is the commit that added it, dated April 2005. https://github.com/Netatalk/netatalk/commit/ecfc96169ab669b578e53fa8e13592934fe37788

The documentation has this to say:

> -noallmulti (Linux only)
>
>    On Linux, the interfaces atalkd uses are set to ALLMULTI by default, because of countless NICs having problems when not being forced into this mode (some don't even work with ALLMULTI set). In case you have a NIC known to support multicasts properly, you might want to set this option to make fewer packets be processed

I have a hypothesis that... MULTICAST should work ok on Linux 20 years later. This ticket is to test this out and remove the workaround if all looks good.

**Comment by dgsga** [comment]
😂 I think you might be right...

**Comment by rdmark** [comment]
@NJRoadfan is this something you have experimented with already?

**Comment by NJRoadfan** [comment]
I have. I tried the `-noallmulti` switch and ran into issues with stuff not working on both VMs and a RPi. VM network interfaces in particular seem to be troublesome and others are reporting problems with things like mDNS in VMs as well.

The reason why I was playing with the multicast switch was working with a related problem. I wanted to see if `-noallmulti` was preventing atalkd from using the "zone specific" multicast addresses. Looking at the code, I suspect atalkd sends all multicast packets out with the generic AppleTalk multicast address by default.

**Comment by rdmark** [comment]
@NJRoadfan Thanks for the info... I ran a few tests in my Debian 12 setup today (a physical machine with a physical ethernet interface) but could not get `-noallmulti` to "stick" regardless of settings in atalkd.conf. When atalkd starts up it removes the option.

**Comment by rdmark** [comment]
Experimental branch available at https://github.com/Netatalk/netatalk/pull/1094 ...

I only have a very simple AppleTalk setup right now, with a single OS9 Mac (which use AppleTalk only for service discovery). So far I have not run into any adverse effects.

If you have a chance to test this out, ideally with AppleTalk-only systems, that would be very helpful...

**Comment by rdmark** [comment]
A Docker image for testing has been created: https://hub.docker.com/repository/docker/netatalk/netatalk2/tags

`docker pull netatalk/netatalk2:multicasttest`

BTW, there is a marked difference in vulnerabilities and image size going from Debian to Alpine!

![image](https://github.com/Netatalk/netatalk/assets/2108467/322b7fc6-b0ab-40c1-8328-6665c7faa957)

**Comment by NJRoadfan** [comment]
This PR seems to be working correctly with emulated machines over Ethernet. I will test with a real Quadra 605 with System 7.1 later in the weekend.

**Comment by NJRoadfan** [comment]
Tested with a real Quadra 605 (running 7.1) and a Powermac 6100/66 (running 8.6) with no issues. I have one more test case that I want to run before signing off.

**Comment by NJRoadfan** [comment]
Tested with a Fastpath 4 and LocalTalk clients with netatalk as a non-seed router. This was mostly because K-STAR on the Fastpath does proper NBP broadcasts using the zone specific multicast addresses. I have exhausted all the test cases I can think of. Looks like multicast is working properly on Linux..... at least on my hardware.

**Comment by rdmark** [comment]
I'm satisfied with the testing done so far, thanks for all your efforts on this one!

Let me go ahead and merge the change into the 2.4 branch, and if we find issues later we can tweak the code then...
