### ISSUE TITLE
[2.4] a2boot: Not working with meson builds.

### ISSUE THREAD

**Issue by NJRoadfan** [Netatalk/netatalk#1095]
System is running Debian 11 x64.

Steps to reproduce:
-Build netatalk 2,4 using meson
-Attempt to netboot an Apple IIgs.

When attempting to netboot the machine ether locks up or crashes at the first stage boot loader.

The following is in the debug log:
`a2boot open error on /usr/local/etc/netatalk/a2boot/ProDOS16\ Boot\ Blocks`

The listed file is present in that directory. Builds using autotools are working correctly.

**Comment by rdmark** [comment]
@NJRoadfan Nice catch. I wonder if Autotools interprets the backslashes in that path as escape characters, while Meson interprets them literally? Can you try editing `contrib/a2boot/meson.build` to remove those backslashes, reconfigure and build?

**Comment by NJRoadfan** [comment]
That seemed to do the trick. The Apple IIgs is tested and booting over the network again. Unfortunately I don't have a IIe Workstation card to test the rest of the boot block file variations. I don't see why it wouldn't work though.

**Comment by rdmark** [comment]
Great, I'm glad that it was an easy fix.

I have a IIGS but it sits in my closet and I don't really have space to set it up anywhere at the moment...

**Comment by NJRoadfan** [comment]
One can always emulate. GSport and GSplus both support emulated AppleTalk and netboot works with it.
