### ISSUE TITLE
Github or Sourceforge - One more authoritative than the other?

### ISSUE THREAD

**Issue by knight-of-ni** [Netatalk/Netatalk#111]
There is an open review request to add netatalk back into the Fedora repos that has stalled.
You are probably familiar with it: https://bugzilla.redhat.com/show_bug.cgi?id=1520024

I left a post to that thread recently to get some movement on the review. I'll give it another week, and if there is no movement I will close it out then create a new request.

I am thinking ahead here, do you have a preference as to which site I pull the source tarball from, sourceforge or github? Personally, I'd rather use github because I am more familiar with it, but I can use sourceforge if there is some reason I shouldn't use github. Let me know if you prefer one over the other.

**Comment by slowfranklin** [comment]
On Wed, Dec 05, 2018 at 05:16:52AM -0800, Andrew Bauer wrote:
>There is an open review request to add netatalk back into the Fedora repos that 
>has stalled.  You are probably familiar with it: 
>https://bugzilla.redhat.com/show_bug.cgi?id=1520024
>
>I left a post to that thread recently to get some movement on the review. I'll 
>give it another week, and if there is no movement I will close it out then 
>create a new request.
>
>I am thinking ahead here, do you have a preference as to which site I pull the 
>source tarball from, sourceforge or github? Personally, I'd rather use github 
>because I am more familiar with it, but I can use sourceforge if there is some 
>reason I shouldn't use github. Let me know if you prefer one over the other.

if you want to fetch from a git repo, you can use github. Source tarball 
releases are still done via SF.

Thanks!
-slow

-- 
Ralph Boehme, Samba Team                https://samba.org/
Samba Developer, SerNet GmbH   https://sernet.de/en/samba/
GPG-Fingerprint   FAE2C6088A24252051C559E4AA1E9B7126399E46

**Comment by knight-of-ni** [comment]
Thanks!
