### ISSUE TITLE
Debian removed libgcrypt-config in libgcrypt 1.11

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1113]
We use libgcrypt-config to configure libgcrypt in the build system, both autotools and meson.

However, the Debian project is removing libgcrypt-config from v1.11 of their packaged version of the library. This affects the upcoming Debian Trixie.

As a result, netatalk no longer compiles in unstable: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1071945

The mother Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=714589

GnuPG discussion thread: https://dev.gnupg.org/T7114

**Comment by dgsga** [comment]
Easy to fix...

**Comment by dgsga** [comment]
> @dgsga Debian has flagged netatalk for autoremoval from Trixie testing on June 4th, unless this is fixed. If you're able to come up with a patch for Autotools in addition to Meson, then I'll go ahead and file a downstream patch for the Debian package to prevent this from happening...

Working on it...
