### ISSUE TITLE
Github & Sourceforge 3.1.11 tarballs do not agree

### ISSUE THREAD

**Issue by knight-of-ni** [Netatalk/Netatalk#112]
I did a comparison between these two tarballs, both advertised as the 3.1.11 release:
https://github.com/Netatalk/Netatalk/archive/netatalk-3-1-11.tar.gz
http://prdownloads.sourceforge.net/netatalk/netatalk-3.1.11.tar.gz?download

There are differences between the two that I cannot reconcile.

These files are in the tarball from Github, but not in the tarball from Sourceforge:
```
bin/megatron/asingle.c
bin/megatron/asingle.h
bin/megatron/hqx.c
bin/megatron/hqx.h
bin/megatron/macbin.c
bin/megatron/macbin.h
bin/megatron/megatron.c
bin/megatron/megatron.h
bin/megatron/nad.c
bin/megatron/nad.h
bin/megatron/updcrc.c
bin/megatron/updcrc.h
bin/uniconv/
bin/uniconv/iso8859_1_adapted.c
bin/uniconv/Makefile.am
bin/uniconv/uniconv.c
contrib/misc/
contrib/misc/cnid.lua
contrib/misc/libevent.patch
contrib/misc/Makefile.am
etc/afpd/spotlight-packet2.bin
etc/afpd/spotlight-packet.bin
libatalk/locking/
libatalk/locking/locking.c
libatalk/locking/Makefile.am
```
There are other differences between the documentation and manpage files as well.
Both tarballs have the same date of Mar 15, 2017.

I don't know if I should be concerned about this or not, so I thought I'd bring it to your attention.
As far as I understand it, github should mirror the sourceforge site, or am I mistaken?

**Comment by slowfranklin** [comment]
Well, the tarballs on sf.net are the "authoritative" ones created with make dist. The ones from github are created by github automagically, I have no idea how...
