### ISSUE TITLE
On Alpine, avahi compat layer needed for zeroconf with mdns

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1122]
While in the 2.x branch, you can build zeroconf support with only the built-in mdns on Alpine, the same doesn't work in 3.x (main.) If you remove avahi-dev, you don't get any zeroconf built.

Seems to affect autotools and meson equally.

**Comment by dgsga** [comment]
@rdmark,  solved! Alpine has a weird dns_sd setup where the library is installed by the avahi-compat-libdns_sd package but the dns_sd.h header is installed by avahi-dev. So we need both to enable mdns support.

**Comment by rdmark** [comment]
@dgsga Nicely done!

Can you please also fold the GitHub workflow change from https://github.com/Netatalk/netatalk/pull/1121/files into your PR?

**Comment by dgsga** [comment]
> @dgsga Nicely done!
> 
> Can you please also fold the GitHub workflow change from https://github.com/Netatalk/netatalk/pull/1121/files into your PR?

@rdmark, please see PR's #1155 and #1157
