### ISSUE TITLE
[2.4] meson: Still has a distinct with-libtirpc option

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1128]
The `with-libtirpc` option was removed for 3.x in https://github.com/Netatalk/netatalk/commit/c8ab3a277d134e18780f78bf84608a9cafd197fa but it remains in 2.x

**Comment by rdmark** [comment]
@dgsga Was this an oversight or deliberate choice?

**Comment by dgsga** [comment]
An oversight. Fixed in PR #1129
