### ISSUE TITLE
Unicode 11.0.0

### ISSUE THREAD

**Issue by hat001** [Netatalk/Netatalk#114]
libatalk shoud support Unicode 11.0.0 .

**Comment by hat001** [comment]
patch is here.
[0001-libatalk-Update-Unicode-support-to-version-11.0.0.patch.txt](https://github.com/Netatalk/Netatalk/files/2682084/0001-libatalk-Update-Unicode-support-to-version-11.0.0.patch.txt)

**Comment by rdmark** [comment]
@hat001 It seems Unicode 14.0 is available at this point. Would it make sense to revise this for the latest standard?

**Comment by rdmark** [comment]
I put up a PR for Unicode 14 in master: https://github.com/Netatalk/Netatalk/pull/177

**Comment by rdmark** [comment]
This ticket can be closed now. Unicode 14 updates have been merged to master, 3.1 and 2.2 branches.
