### ISSUE TITLE
[2.4] srvloc gone with meson build system of netatalk2?

### ISSUE THREAD

**Issue by VorpalBlade** [Netatalk/netatalk#1140]
**Describe the bug**
I was looking at updating the AUR package to netatalk 2.4.0, and noticed that there is a new meson build system. I currently configure the AUR package to use srvloc as that is the only way I found being able to do service discovery with early OS X and late OS 9 (and I have computers from that era). As far as I know zeroconf and srvloc are mutually exclusive (unfortunately). With meson I can't find the option to enable srvloc. Have you forgot to port that over?

**To Reproduce**
Look through `meson_options.txt` trying to figure out how to migrate to the new build system.

**Expected behavior**
srvloc support should not be dropped

**Environment**
 - Server OS: Arch Linux
 - Client OS: Mac OS 9.2 and Mac OS X 10.2 (first generation clamshell iBook)
 - Netatalk Version 2.4.0

**Logs**
Attach syslogs from the malfunctioning process, `maxdebug` log level

**Additional context**
If it is a crash, please attach a [stacktrace](https://github.com/Netatalk/netatalk/wiki/Using-GDB-to-Analyze-a-Crash).

**Comment by rdmark** [comment]
Right, I completely forgot about SLP. It should be possible to add support, I think.

Thanks for taking a closer look at the new build system. Please report any other shortcomings you come across. :)

**Comment by dgsga** [comment]
Working on it...

**Comment by dgsga** [comment]
@VorpalBlade Please can you checkout the dgsga-srvloc branch and see if this addresses your issue?

Meson now automatically enables SLP (srvloc) support if the slp library is found along with the slp.h header. You can disable it with the `-Dwith-srvloc=false` option at configure time.

If you have (Open)SLP installed in an unconventional location you can point to it using the `-Dwith-srvloc-path` option

**Comment by VorpalBlade** [comment]
@dgsga I will look at it this weekend, unfortunately I will likely not have time before that. You are way more quick to respond than I am.

**Comment by rdmark** [comment]
@VorpalBlade FYI the fix has been merged to branch-netatalk-2-4. I am working on a 2.4.1 release now which is time sensitive because of a CVE security patch.

If something doesn't work properly in your testing, we can always do additional fixing and a fast-follow 2.4.x release!
