### ISSUE TITLE
Remove obsolete init scripts: Red Hat Upstart and SuSE SysV

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1151]
Both netatalk 3.x and 2.x ship traditional init scripts for Red Hat and SuSE. However, both distros have long since transitioned to systemd (2014 and 2015, respectively) and neither ship optional packages that restore the traditional init system anymore (they did for several years during a transition period.)

Therefore, neither of these two can be tested or used on modern versions of these OSes.

As a side note, Debian still provides SysV init script tooling, but it seems to be a wrapper on top of systemd.

**Comment by rdmark** [comment]
I propose we make this change in the next feature releases, e.g. 3.3 and 2.5

**Comment by dgsga** [comment]
@rdmark, would it make sense for me to take this one on as part of the init system revamp?
