### ISSUE TITLE
[2.4] Can't override system WolfSSL with embedded WolfSSL

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1171]
When trying to test https://github.com/Netatalk/netatalk/issues/1170 by forcing meson to build with the bundled WolfSSL library with `-Dwith-embedded-ssl=true` the setup summary still says WolfSSL. No change in behavior.

While it might be a small corner case, I think the ability to override the default setting would be useful sometimes.

**Comment by dgsga** [comment]
Closed with #1175 and #1176
