### ISSUE TITLE
meson: with-pam-confdir option

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1173]
The *with-pam-confdir* option from the autotools seems to have fallen off in meson. 

```
--with-pam-confdir=PATH Path to PAM config dir (default:
                          ${prefix}/etc/pam.d)
```

**Comment by rdmark** [comment]
@dgsga Was this a deliberate decision? (Apologies if you already addressed this at some point...)

**Comment by dgsga** [comment]
No, an oversight. Working on it...
