### ISSUE TITLE
uams_dhx2_passwd.so of netatalk-3.2.1 does not link libgcrypt via configure

### ISSUE THREAD

**Issue by masahito-yamaga** [Netatalk/netatalk#1174]
netatalk-3.2.1 needs the following patch in order to link libgcrypt.
<pre>
--- ./macros/libgcrypt.m4.ORG	2024-06-29 14:58:36.000000000 +0900
+++ ./macros/libgcrypt.m4	2024-06-30 14:05:49.174875397 +0900
@@ -8,7 +8,7 @@
                    netatalk_cv_libgcrypt=$withval)
     if test x$netatalk_cv_libgcrypt != x ; then
         LIBGCRYPT_CFLAGS="-I$netatalk_cv_libgcrypt/include"
-        LIBGCRYPT_LIBS="-L$netatalk_cv_libgcrypt/lib"
+        LIBGCRYPT_LIBS="-L$netatalk_cv_libgcrypt/lib -lgcrypt -lgpg-error"
     else
         PKG_CHECK_MODULES(LIBGCRYPT, [libgcrypt >= 1.2.3],
             ac_cv_have_libgcrypt=yes,</pre>

**Comment by rdmark** [comment]
@masahito-yamaga Thank you for reporting the issue and suggesting a fix!

May I ask which OS distribution and version you are using? I want to reproduce the issue you are seeing. However, on my Debian 12 system this patch is not needed to link with libgcrypt...

**Comment by masahito-yamaga** [comment]
Oh! Really?
It might be difficult to reproduce this issue because my environment is so unique.

Linux. but not a general distribution.
uClibc + gcc 8.5.0

It would be best to keep an eye on the situation to see if there is any other environment that can reproduce this.

**Comment by rdmark** [comment]
@masahito-yamaga That's an interesting setup! gcc 8.5.0 is a fairly old version of the compiler, so I assume the other autotools toolchain pieces are also a bit older? This might be the the explicit library flags are needed.

Your change doesn't seem to have an adverse effect in my Debian 12 environment (gcc 12.2.0).

If you can create a GitHub PR with your fix, our CI workflow will tell us right away if this breaks linking on other platforms (I don't think so.)

Git and PR guidelines are described on https://github.com/Netatalk/netatalk/wiki/Developer-Notes
