### ISSUE TITLE
spotlight code lack copyright notice from Wireshark

### ISSUE THREAD

**Issue by jonassmedegaard** [Netatalk/Netatalk#119]
The file <etc/afpd/spotlight.c> lack copyright notice from when it was copied from Wireshark, as indicated in commit eae8763 which corresponds to Wireshark code at the time: https://github.com/wireshark/wireshark/commit/2f035a3

Seems a simple case of adding `1998 Gerald Combs <gerald@wireshark.org>`.

**Comment by jonassmedegaard** [comment]
Seems <etc/afpd/spotlight_marshalling.c> is derived from <etc/afpd/spotlight.c> and need same treatment.

**Comment by jonassmedegaard** [comment]
Seems <etc/spotlight/*> may also be derived and need same treatment.

**Comment by slowfranklin** [comment]
Spotlight code in Wireshark and Netatalk were developed in conjunction by Frank Lahm.

**Comment by jonassmedegaard** [comment]
Thanks for clarifying!
