### ISSUE TITLE
[2.4] Meson: SHADOW password support for UAMs not working.

### ISSUE THREAD

**Issue by NJRoadfan** [Netatalk/netatalk#1190]
When building 2.4 with Meson (may also affect 3.2, untested), UAMs requiring access to system passwords (Cleartxt, DHX, DHX2) aren't working. Here is the configuration output from Meson:

```
UAMs:
      Kerberos V               : NO
      PGP                      : NO
      Randnum                  : (afppasswd)
      clrtxt                   : ()
      guest                    : YES
      DHX                      : ()
      DHX2                     : ()
```

When building with autotools, shadow password support is working. Output from configure:
```
UAMS:
         DHX     ( SHADOW)
         DHX2    ( SHADOW)
         RANDNUM (afppasswd)
         clrtxt  ( SHADOW)
         guest
```

Note: Building with PAM is working fine with both Meson and autotools. However, the PAM dev libraries are not installed by default in most distros, including Debian.

**Comment by dgsga** [comment]
@NJRoadfan, thanks for spotting this. Fixed in PR's #1191 and #1192
