### ISSUE TITLE
Permission to relicense from GPLv2 to a later version

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1193]
The GPLv2 has a clause that allows upgrading to future revisions of the GPL.

The standard GPLv2 grant[1] recommends this paragraph, and is what is used for the majority of GPLv2 licensed sources in Netatalk:

> This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version. 

However, three sources files in the Netatalk codebase[2] have this grant:

>  This program is free software; you can redistribute and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation version 2 of the License or later version if *explicitly stated by any of above copyright holders*.

(my emphasis)

This ticket is about gaining the explicit approval from *any of the copyright holders* of the three source files in question.

The one named copyright holder common between all three files is Rafal Lewczuk. I have reached out to him privately and asked for permission.

[1] https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html @ section "How to Apply These Terms to Your New Programs" 
[2.a] https://github.com/Netatalk/netatalk/blob/main/libatalk/cnid/cnid.c
[2.b] https://github.com/Netatalk/netatalk/blob/main/libatalk/cnid/cnid_init.c
[2.c] https://github.com/Netatalk/netatalk/blob/main/include/atalk/cnid.h

**Comment by rdmark** [comment]
Copyright holders are at the time of writing:

- [ ] the Netatalk Team
- [ ] Rafal Lewczuk
- [ ] Frank Lahm

**Comment by rlewczuk** [comment]
I'm giving permission to relicense above files under later versions of GPL as requested by @rdmark.

Glad to see netatalk project still alive, good luck to all involved.

**Comment by rdmark** [comment]
@rlewczuk Thank you for all your contributions to the project back then!

For starters, I have put up PRs to leave a note of the "evidence" of this permission under the copyright notices.
