### ISSUE TITLE
Incompatible version error when any UAMs are used

### ISSUE THREAD

**Issue by drewcassidy** [Netatalk/netatalk#121]
When trying to connect to a netatalk server which has any UAM enabled, I get an error that the version is incompatible. this only happens with `uam list = ` in the config and when connecting as a registered user. <img width="542" alt="Screen Shot 2019-04-25 at 8 41 53 PM" src="https://user-images.githubusercontent.com/3837797/56782130-9a212a00-679a-11e9-8be1-5b49dacf3622.png">

##### Server:
- OS: Arch, latest (I'm not sure how to get an actual "version number" for arch)
- netatalk 3.1.12, installed via AUR

##### Client:
- OS: macOS Mojave 10.14.4

##### Config:
```
;
; Netatalk 3.x configuration file
;

[Global]
; Global server settings
 mimic model = PowerMac
 log level = default:warn
 log file = /var/log/afpd.log
 hosts allow = 192.168.1.0/24
 ;spotlight = yes
 uam list = uams_guest.so,uams_dhx.so,uams.dhx2.so

[Homes]
 basedir regex = /home

[Media]
 path = /srv/afp/Media
 validusers = drewcassidy

[Time Machine]
 path = /srv/afp/TimeMachine
 validusers = drewcassidy
 time machine = yes
```

**Comment by rdmark** [comment]
@drewcassidy There is a typo in your uam list. `uams.dhx2.so` -> `uams_dhx2.so`. It should work if you fix the typo.

**Comment by drewcassidy** [comment]
Thank you for that. I don't think I still own the machine this was set up on so I guess I'll just close and assume that was the issue
