### ISSUE TITLE
home name (H) requires $u but it's not in the documentation

### ISSUE THREAD

**Issue by hfiguiere** [Netatalk/netatalk#123]
home name (H) requires $u but it's not in the documentation. 

- I wasted some time figuring out why it wasn't working as it is not documented in afp.conf(5)
- it also broke my setup when upgrading as the home volume was called "Galactica Home" (Galactica is the server name)

commit e4743bf doesn't give much detail on the change as to why.

**Comment by hfiguiere** [comment]
And a quick note: Debian 9 (stretch) still had 2.2.5 while Debian 10 (buster) the current stable now ship 3.1.x. 
(since the commit is 7 years old)

**Comment by rdmark** [comment]
There is some additional context in https://sourceforge.net/p/netatalk/bugs/454/

**Comment by rdmark** [comment]
The discussion thread starting with https://sourceforge.net/p/netatalk/mailman/message/28909382/ is relevant to the original design decision, I think.

**Comment by rdmark** [comment]
Raised https://github.com/Netatalk/netatalk/pull/264 to get the manpage updated.

**Comment by rdmark** [comment]
Merged to main.
