### ISSUE TITLE
Dropping privilege permanently more completely with initgroups

### ISSUE THREAD

**Issue by theopolis** [Netatalk/Netatalk#126]
Hi, I was reviewing the privilege dropping code and noticed that supplemental groups are not dropped in the following implementation:
https://github.com/Netatalk/Netatalk/blob/7df85420cecacfef0b79988fdb9d37f3b70eb0ef/etc/afpd/afprun.c#L111

An easy way to drop these groups is with `setgroups(0, NULL)` but the recommended and more secure method is with `initgroups`, which sets the groups to the target user's groups.

**Comment by slowfranklin** [comment]
Fixed in a680bb2fae6d570a04cea9ddab3220b872a17f04. Thanks!
