### ISSUE TITLE
meson: test 1 fails if run out of order

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1273]
On Arch Linux, the tests fail with Meson if Netatalk hasn't already been built with Autotools once in the same source tree.... veeery suspiciously.

```
ninja: Entering directory `/__w/netatalk/netatalk/build'
ninja: no work to do.
1/2 test2 FAIL            0.01s   exit status 1
>>> MALLOC_PERTURB_=70 LD_LIBRARY_PATH=/__w/netatalk/netatalk/build/libatalk MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MESON_TEST_ITERATION=1 /__w/netatalk/netatalk/build/test/afpd/afpdtest

2/2 test1 OK              0.01s

Ok:                 1   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
```

I wonder if it has to do with Autotools building the objects in-dir, while Meson does it the build dir?

**Comment by rdmark** [comment]
This affects only Arch out of the OSes in our GitHub CI workflow... So the tests are temporarily disabled there to unblock the workflow. The tests should be turned back on once this is fixed.

**Comment by knight-of-ni** [comment]
I am in the process of converting the Fedora/EPEL specfile over to Meson, and have just hit this error. I have not yet begun to troubleshoot, but it appears the same as what is reported in this thread.


```
ninja: Entering directory `/builddir/build/BUILD/netatalk-3.2.4/redhat-linux-build'
ninja: no work to do.
1/2 test2 FAIL            0.01s   exit status 1
>>> LD_LIBRARY_PATH=/builddir/build/BUILD/netatalk-3.2.4/redhat-linux-build/libatalk MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=198 ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 /builddir/build/BUILD/netatalk-3.2.4/redhat-linux-build/test/afpd/afpdtest
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
Initializing
============
Testing: setuplog("default:note", "/dev/tty", true) ...                                       [ok]
Testing: afp_options_parse_cmdline(&obj, 3, &args[0]) ...                                     [ok]
Testing: afp_config_parse(&obj, NULL) ...                                                     [ok]
Testing: configinit(&obj) ...                                                                 [error]
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

2/2 test1 OK              0.01s

Summary of Failures:

1/2 test2 FAIL            0.01s   exit status 1

Ok:                 1   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

```

**Comment by knight-of-ni** [comment]
During my progress of building a working specfile, the tests started passing. Race condition, perhaps? I'll keep an eye on it.

```
+ cd netatalk-3.2.4
+ /usr/bin/meson test -C redhat-linux-build --num-processes 4 --print-errorlogs
ninja: Entering directory `/builddir/build/BUILD/netatalk-3.2.4/redhat-linux-build'
ninja: no work to do.
1/2 test1 OK              0.01s
2/2 test2 OK              0.01s
Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
Full log written to /builddir/build/BUILD/netatalk-3.2.4/redhat-linux-build/meson-logs/testlog.txt
```

**Comment by rdmark** [comment]
Do you recall if it was a particular change to the specfile that triggered the change in behavior?

It seems to be deterministic with the right parameters…

**Comment by knight-of-ni** [comment]
It's possible. I was working on multiple changes that seem unrelated to the build test failure. 

For example, I believe _with-init-hooks=false_ was one change I made.

I also disabled the static library build for libatalk and modified how the documentation is built (can discuss these later if you are interested):

```
# The --disable-static flag does not work, so lets do it the hard way
sed -i 's\both_libraries\shared_library\' libatalk/meson.build

# Don't build the japanese docs and put the english docs into a subfolder
sed -i 's\install: true\install: false\' doc/ja/manual/meson.build
sed -i 's\doc/netatalk\doc/netatalk/htmldoc\' doc/manual/meson.build
```

In %install, I deleted the uam static libraries then turned one of the identical README files into a symlink.

At some point after these changes, the tests started working on their own. I'm still scratching my head as to how that could affect a change to the tests, unless their was some kind of race condition.

**Comment by rdmark** [comment]
> # The --disable-static flag does not work, so lets do it the hard way

Did you try the built-in `default_library` option (combo type with [static,shared,both] values)? If that doesn't work either, let's modify the build system to be sensitive to this option.

> # Don't build the japanese docs and put the english docs into a subfolder

I actually ended up making the exact same downstream patches for Debian packaging last week. On the fence if we should fix either upstream here or not... What do you think?

**Comment by knight-of-ni** [comment]
Now that I have a spec file that mock builds successfully, I will create new issues to document what I ran into along the way.
There isn't anything that would take a lot of work to resolve.

**Comment by rdmark** [comment]
Another point for a race condition: After making an unrelated change to the build system, the exact same failure happened on macOS in the GitHub CI workflow:

```
ninja: Entering directory `/Users/runner/work/netatalk/netatalk/build'
ninja: no work to do.
1/2 test2 FAIL            0.01s   exit status 1
>>> ASAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1 UBSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MSAN_OPTIONS=halt_on_error=1:abort_on_error=1:print_summary=1:print_stacktrace=1 MALLOC_PERTURB_=232 MESON_TEST_ITERATION=1 /Users/runner/work/netatalk/netatalk/build/test/afpd/afpdtest

2/2 test1 OK              0.02s

Ok:                 1   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /Users/runner/work/netatalk/netatalk/build/meson-logs/testlog.txt
Error: Process completed with exit code 1.
```

https://github.com/Netatalk/netatalk/actions/runs/10109228221/job/27956694371?pr=1309

**Comment by rdmark** [comment]
After trying the various test options in the [meson documentation](https://mesonbuild.com/Unit-tests.html), I found something that seems to work consistently: Force test order and single threaded execution.

In the long run, the tests should be rewritten as isolated unit tests (I have a ticket for this) but for now I'm satisfied with this solution.
