### ISSUE TITLE
Fedora migrating away from IO::Socket::INET6 to IO::Socket::IP

### ISSUE THREAD

**Issue by knight-of-ni** [Netatalk/Netatalk#130]
The Fedora project plans to deprecate IO::Socket::INET6. Netatalk has been patched use IO::Socket::IP instead.

Here is the diff:
https://src.fedoraproject.org/rpms/netatalk/pull-request/3#request_diff

I can create a PR for this if there is any interest. Let me know.

**Comment by slowfranklin** [comment]
Yes, please submit a patch. Thanks!

**Comment by knight-of-ni** [comment]
Here is the patch we are using in Fedora:
https://src.fedoraproject.org/fork/mspacek/rpms/netatalk/raw/8866197af5b581d33881560d22a03d2d5cfdaf2e/f/netatalk-3.1.12-rewrite_deprecated_perl_dependency.patch

**Comment by slowfranklin** [comment]
4dddddf0cc9d824963d8e723df61bf0c4da19d35
