### ISSUE TITLE
Allow specifying what documentation is built and its target location

### ISSUE THREAD

**Issue by knight-of-ni** [Netatalk/netatalk#1306]
**Is your feature request related to a problem? Please describe.**
This is purely a preference.  "Wouldn't it be nice if...."

**Describe the solution you'd like**
Through the use of meson build flags, allow one to specify whether the English, Japanese, or both sets of documentation are built.

Additionally, it would be nice if we could specify the target folder.  Putting all those html files into their own subfolder, e.g. _/usr/share/doc/netatalk/htmldoc_, makes a good separation between those files and the other files that get placed into the documentation folder (in my case: CONTRIBUTORS, NEWS, INSTALL.md, README.md, and SECURITY.md). 

**Describe alternatives you've considered**
Currently I am hacking these changes during the rpm build with a sed one-liner.

**Additional context**
I think the second item was on your radar at one point, but it was closed out (can't find the github issue at the moment).

**Comment by rdmark** [comment]
Thanks for the suggestions. You probably thought of this ticket: https://github.com/Netatalk/netatalk/issues/1233 My idea was to put the generated html doc files into a hard-coded subdir (i.e. htmldocs, to mimic the organization of the website). Do you think it would be useful for downstream packagers to be able to specify a path freely?

Regarding the manual localization: I made this change to the main dev branch the other day: https://github.com/Netatalk/netatalk/pull/1283 As a simple solution to your request, I could modify the `-Dwith-manual=local` option to only build the English manual. What do you think?

**Comment by rdmark** [comment]
For starters, this achieves my lowest-effort proposal: https://github.com/Netatalk/netatalk/pull/1309

Please let me know if this looks acceptable to you.

**Comment by rdmark** [comment]
I got a bit carried away and added support for installing readme files too, with optional transcoding from markdown to plain text.

On macOS, f.e.:

```
/opt/homebrew/share/doc/netatalk
├── CONTRIBUTORS
├── DEVELOPER
├── INSTALL.txt
├── NEWS
├── README.txt
├── SECURITY.txt
└── htmldocs
    ├── ad.1.html
    ├── afp.conf.5.html
    ├── afp_signature.conf.5.html
    ├── afp_voluuid.conf.5.html
    ├── afpd.8.html
    ├── afpldaptest.1.html
    ├── afppasswd.1.html
    ├── apple_dump.1.html
    ├── asip-status.1.html
    ├── cnid_dbd.8.html
    ├── cnid_metad.8.html
    ├── compile.html
    ├── configuration.html
    ├── dbd.1.html
    ├── example-toc.html
    ├── extmap.conf.5.html
    ├── gpl.html
    ├── index.html
    ├── installation.html
    ├── intro.html
    ├── macusers.1.html
    ├── man-pages.html
    ├── manual-index.html
    ├── netatalk-config.1.html
    ├── netatalk.8.html
    ├── table-toc.html
    └── upgrade.html

2 directories, 33 files
```

**Comment by rdmark** [comment]
@knight-of-ni I have prepared a more sophisticated solution in: https://github.com/Netatalk/netatalk/pull/1376

Please let me know what you think!

**Comment by rdmark** [comment]
@knight-of-ni FYI I changed my mind and am making these baseline changes to the stable branches: https://github.com/Netatalk/netatalk/pull/1390 https://github.com/Netatalk/netatalk/pull/1391

A new version is forthcoming shortly!
