### ISSUE TITLE
Netatalk rc.d startup script should be located at /usr/local/etc/rc.d/netatalk on FreeBSD

### ISSUE THREAD

**Issue by andylemin** [Netatalk/netatalk#1337]
**Describe the bug**
Building and installing Netatalk 3.2.4 using meson (possibly legacy builder too), deploys rc startup script to /etc/rc.d/netatalk

**To Reproduce**
Follow Netatalk 3 build and install steps for FreeBSD as per new instructions in appendix of Netatalk manual.

**Expected behavior**
/etc/rc.d/ is reserved for FreeBSD base packages. /usr/local/etc/rc.d/ is for all other packages

**Environment**
 - Server OS: FreeBSD 14.1
 - Netatalk Version 3.2.4

**Additional context**
Mostly superficial, but bad practice and confusing/inconsistent

**Comment by rdmark** [comment]
Thanks for reporting. Do you have an official policy document that describes this rule? Not that I don't believe you, but it's good to have a concrete reference for posterity when making a change like this. The closest I could find is the [rc man page](https://man.freebsd.org/cgi/man.cgi?query=rc) which says:

> The  rc.local  script  contains
       commands	 which	are pertinent only to a	specific site.	Typically, the
       /usr/local/etc/rc.d/ mechanism is used instead of rc.local  these  days [...]

This reads more like guidance for system administrators rolling their own rc scripts than for package maintainers, but I could be mistaken!

Now when I look closer at the build script, I realize that we forgot to implement the `with-init-dir` option in Meson (only a stub exists). For starters I will reintroduce this option to enable users and package maintainers to customize the init script path...

**Comment by rdmark** [comment]
Actually now when I think about it, building and installing a package like this arguably counts as "rolling your own rc script".

Looking at the downstream [netatalk3 port](https://www.freshports.org/net/netatalk3/), they are indeed modifying meson to install into:

```
$ ls /usr/local/etc/rc.d
avahi-daemon	avahi-dnsconfd	cupsd		dbus		git_daemon	netatalk	uuidd
```

**Comment by andylemin** [comment]
I'm not sure if there is an official statement, but from experience I have never seen non-base package rc scripts in /etc/rc.d/ on FreeBSD.

It's fairly common for Unix distros to keep things separated like this.

Pleased to see this helped highlight some other meson improvements for you.

PS; serious Kudos for all the work on Netatalk lately. It's great to see the project brought fully back to life 😀 you have been busy!
