### ISSUE TITLE
Check for C11 support in compiler prior to checking headers

### ISSUE THREAD

**Issue by barracuda156** [Netatalk/netatalk#1356]
**Describe the bug**
Configure fails to detect basic system headers. Like, none of them exist at all:
```
Has header "acl/libacl.h" : NO 
Has header "attr/xattr.h" : NO 
Has header "crypt.h" : NO 
Has header "dirent.h" : NO 
Has header "dlfcn.h" : NO 
Has header "dns_sd.h" : NO 
Has header "errno.h" : NO 
Has header "fcntl.h" : NO 
Has header "inttypes.h" : NO 
Has header "langinfo.h" : NO 
Has header "limits.h" : NO 
Has header "locale.h" : NO 
Has header "mntent.h" : NO 
Has header "mount.h" : NO 
Has header "ndir.h" : NO 
Has header "netdb.h" : NO 
Has header "pam/pam_appl.h" : NO 
Has header "security/pam_appl.h" : NO 
Has header "sgtty.h" : NO 
Has header "statfs.h" : NO 
Has header "stdarg.h" : NO 
Has header "stdint.h" : NO 
Has header "stdio.h" : NO 
Has header "stdlib.h" : NO 
Has header "strdarg.h" : NO 
Has header "string.h" : NO 
Has header "strings.h" : NO 
Has header "sys/attributes.h" : NO 
Has header "sys/dir.h" : NO 
Has header "sys/ea.h" : NO 
Has header "sys/extattr.h" : NO 
Has header "sys/file.h" : NO 
Has header "sys/filio.h" : NO 
Has header "sys/ioctl.h" : NO 
Has header "sys/mnttab.h" : NO 
Has header "sys/mount.h" : NO 
Has header "sys/ndir.h" : NO 
Has header "sys/param.h" : NO 
Has header "sys/stat.h" : NO 
Has header "sys/statvfs.h" : NO 
Has header "sys/time.h" : NO 
Has header "sys/types.h" : NO 
Has header "sys/uio.h" : NO 
Has header "sys/vfs.h" : NO 
Has header "sys/wait.h" : NO 
Has header "sys/xattr.h" : NO 
Has header "syslog.h" : NO 
Has header "termios.h" : NO 
Has header "time.h" : NO 
Has header "ufs/quota.h" : NO 
Has header "unistd.h" : NO 
Has header "utime.h" : NO 
Has header "varargs.h" : NO
```
Turns out, it smuggles in C11, but never checks for it.

**To Reproduce**
Try building with pre-C11 compiler.

**Expected behavior**
Meson configure script should check compiler for C11 support and fail with a clear message, instead of delivering nonsensical output.

**Environment**
 - macOS 10.6
 - Netatalk 2.4.4

**Logs**
```
Running compile:
Working directory:  /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_netatalk/netatalk/work/build/meson-private/tmpio8x_4zu
Code:

        #ifdef __has_include
         #if !__has_include("dirent.h")
          #error "Header 'dirent.h' could not be found"
         #endif
        #else
         #include <dirent.h>
        #endif
-----------
Command line: `/usr/bin/gcc-4.2 -I/opt/local/libexec/openssl3/include -I/opt/local/include/db48 /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_netatalk/netatalk/work/build/meson-private/tmpio8x_4zu/testfile.c -E -P -pipe -Os -arch ppc -P -O0 -std=c11` -> 1
stderr:
cc1: error: unrecognized command line option "-std=c11"
-----------
Has header "dirent.h" : NO 
```

**Comment by rdmark** [comment]
@barracuda156 Thanks for reporting. What I would propose here is to simply compile a snipped of the very simplest C code as soon as the compiler is defined, and bail out if this fails. This isn't quite a check for C11, but at least the build system will fail early.

**Comment by barracuda156** [comment]
Looks like meson has `c_std=c11` which can be set in `default_options`. In any case it is desirable to have some meaningful error output, since the default compiler may not support C11, but it does not mean that another compiler is not available: a user just needs to be informed that a non-default choice is required.

**Comment by rdmark** [comment]
If you look at line 6 in the mother meson.build, we already set the `c_std=c11` parameter. In fact, this parameter is what’s causing your gcc 4.2 to bail out, since it’s too old to recognize it. 

The error message will point you towards the meson log, which is where you will get the concrete reason the C compiler isn’t functional for our build system. 

If you are aware of a more granular way to do this in Meson, please let me know!

**Comment by barracuda156** [comment]
Then perhaps your suggestion above is the way to go: compile a trivial example and fail on that.

**Comment by rdmark** [comment]
I made the error message a bit more helpful. The fix has been merged to all the stable branches.
