### ISSUE TITLE
2.4.4 fails to configure: `libatalk/util/meson.build: ERROR: Unknown variable "have_atfuncs"`

### ISSUE THREAD

**Issue by barracuda156** [Netatalk/netatalk#1357]
**Describe the bug**
Configure fails:
```
libatalk/util/meson.build:22:3: ERROR: Unknown variable "have_atfuncs".
```

**To Reproduce**
Try building 2.4.4 with meson.

**Expected behavior**
Obviously, build should not use local variables which it does not define.

**Environment**
 - macOS 10.6
 - Netatalk 2.4.4

**Comment by barracuda156** [comment]
Also here: `bin/meson.build:1:3: ERROR: Unknown variable "have_atfuncs".`

**Comment by rdmark** [comment]
Good catch! We were anticipating the have_atfuncs check to always succeed. The simple fix is to declare it as 'false' globally first.

**Comment by barracuda156** [comment]
> Good catch! We were anticipating the have_atfuncs check to always succeed. The simple fix is to declare it as 'false' globally first.

Unless I missed that, nothing even checks for `have_atfuncs`. If it did, the macro should have been defined to something in result.

**Comment by rdmark** [comment]
Actually, you are pointing out the two places in the build system where the flag is used. 

FWIW, these are not macros per se, but variables that can be assigned a Python like data type such as Boolean or object.

**Comment by barracuda156** [comment]
> Actually, you are pointing out the two places in the build system where the flag is used.

They are _used,_ but they are not defined. This perhaps was borrowed from autotools build, but missing a need to check if it is true or false.

**Comment by rdmark** [comment]
It is defined here:

https://github.com/Netatalk/netatalk/blob/1efe59d6408808de6b34c5d7f646b926e23d6a63/meson.build#L337

One drawback of Meson is that it’s too easy to define a flag in one conditional branch but forget to define it when the conditional fails, which leads to the kind of issue that you found here. The better pattern is to define it at a default value before the conditional, which is what I do in the proposed solution.

**Comment by rdmark** [comment]
The fix has been merged to all the stable branches.

**Comment by barracuda156** [comment]
@rdmark Thank you!
