### ISSUE TITLE
meson: Can't find libatalk.so.x on glibc Linux when installed in /usr/local

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1379]
Latest main branch code: This is a suspected breakage bug introduced either by the recent library() target change, or the recent soname change. When building with --prefix=/usr for instance, everything is fine. But when not specifying a prefix and letting the build system fall back to the default /usr/local then the netatalk binaries cannot find libatalk.so ... 

This affects all glibc based Linux distros (Arch, Debian, Fedora, openSUSE...) while musl based Alpine is fine.

**Comment by NJRoadfan** [comment]
2.4.4 is affected by this as well. Building with the static library still works though.

**Comment by rdmark** [comment]
This is triggered when defining the libatalk version and/or soversion in Meson. If you remove both, the problem goes away...

https://github.com/Netatalk/netatalk/blob/834cf5d5675ceb68041ee86d2c69d5359d254c5c/libatalk/meson.build#L60

The soversion was defined since the very beginning of Meson, so there may be some other yet unknown compounding factor.

**Comment by rdmark** [comment]
So the actual breaking point was when I removed rpath for most platforms, i.e. https://github.com/Netatalk/netatalk/pull/1214 (and in the stable branches)

This is because Debian forbids the use of rpath in compiled binaries. It is generally disallowed by Linux distros, according to my research, because it overrides the system library search path.

Anyways, so the rpath setting must have been masking some other misconfiguration in the Meson build system... More investigation is needed.

**Comment by rdmark** [comment]
Updated the CI jobs to run netatalk everywhere. We get a pretty clear picture that this issue affects only Linux that uses glibc...

https://github.com/Netatalk/netatalk/pull/1381

**Comment by rdmark** [comment]
This is probably obvious, but if you tell the netatalk binary where to look for shared libraries, it works fine:

```
$ LD_LIBRARY_PATH=/usr/local/lib/x86_64-linux-gnu/ netatalk -V
```

**Comment by rdmark** [comment]
Ok, I think I found the real root cause: autotools always runs `ldconfig` after installation to refresh the dynamic linker cache, while Meson does not.

Apparently Meson implemented this early on, but removed it in [0.62](https://mesonbuild.com/Release-notes-for-0-62-0.html#ldconfig-is-no-longer-run-on-install) (March 2022) due to cross-platform breakages. See: https://github.com/mesonbuild/meson/issues/4737

So the reason the issue didn't happen on Ubuntu 22.04 is because it's running an old Meson version (0.61).

The solution I will attempt is:
- Check if Meson version is > 0.61
- Check if host OS is Linux
- Check that glibc is present (perhaps optional?)
- If all is true, find and execute ldconfig

**Comment by rdmark** [comment]
While this solution works fairly well, Fedora and Arch are still problematic because they don't allow /usr/local/lib* targets by default in their /etc/ld.so.conf settings. Overriding this with f.e. `ldconfig -n /path/to/lib -v` doesn't have any effect either. What is suggested in the Meson ticket discussions, is to edit /etc/ld.so.conf on the fly, as an install hook. I really don't want to go down that path...

For now, I'll add --prefix=/usr to the Arch and Fedora CI jobs and call it a day.

I'd be curious to find out how autotools works around this situation.

**Comment by rdmark** [comment]
I figured out the correct and non-intrusive way to configure the dynamic linker cache: Install a config file under `/etc/ld.so.conf.d/` containing only the lib path. This is what other libraries that put stuff in /usr/local are doing (on Debian at least).

Now Arch and Fedora are happy too!

While I was at it, the new install hook can be turned off with `-Dwith-install-hooks=false` if you're running unprivileged install commands, since ldconfig requires root privileges...

**Comment by rdmark** [comment]
As an implementation note: Alpine's glibc compatibility package ships a ldconfig binary that is completely broken at the time of writing. It either fails silently (with exit code 1) or spuriously complains about unsupported options. This is why I added an extra check in Meson to validate the return code from ldconfig once before actually adding the install hook. Without it, installation fails on Alpine, and potentially other musl based Linux systems.

Anyhow, this explicit solution in Meson is preferable to whatever black magic autotools is doing, IMHO. And it was an opportunity to learn about dynamic linker caching on Linux. :)

I'm patching both stable branches and will tag new releases in the not-too-distant future.

**Comment by NJRoadfan** [comment]
This is STILL broken. Building main with the following:

`meson setup build -Dwith-appletalk=true -Dwith-pkgconfdir-path=/etc/netatalk -Dwith-init-style=systemd -Dwith-init-hooks=false`

Results in: `/usr/local/sbin/netatalk: error while loading shared libraries: libatalk.so.19: cannot open shared object file: No such file or directory`

**Comment by rdmark** [comment]
Fixed with:

- https://github.com/Netatalk/netatalk/pull/1406
- https://github.com/Netatalk/netatalk/pull/1407
- https://github.com/Netatalk/netatalk/pull/1408
