### ISSUE TITLE
meson: Confusion arises when wolfssl subproject fallback is triggered

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1428]
[main branch] When system wolfssl is missing, meson still detects wolfssl since it exists as a subproject in netatalk. However, the pkgconfig check fails further down with:

```
../meson.build:577:16: ERROR: Could not get pkg-config variable and no default provided for <PkgConfigDependency wolfssl: True None>
```

This is on macOS with homebrew specifically.

I want to try refactor this part to use the subproject as an explicit fallback as per the docs: https://mesonbuild.com/Dependencies.html#building-dependencies-as-subprojects

**Comment by mahato098** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by rdmark** [comment]
Subproject reverted with https://github.com/Netatalk/netatalk/pull/1440
