### ISSUE TITLE
DHX2 UAM doesn't correctly handle client nonce if incremented value is less than full size (16 bytes)

### ISSUE THREAD

**Issue by demonfoo** [Netatalk/netatalk#1456]
**Describe the bug**
In testing of my own AFP client code, I'd noticed occasional authentication failures due to nonce mismatch checks. After digging into the problem, I discovered that the Netatalk UAM code reads in the client's nonce value, increments it, and then `gcry_mpi_print()`s it, but doesn't check to make sure that the value written out was as long as the field it's being put into.

https://github.com/Netatalk/netatalk/blob/main/etc/uams/uams_dhx2_pam.c#L499-L502

**To Reproduce**
https://github.com/demonfoo/afp-perl

Get and install my AFP client code from the above repo.

Change line 191 of `lib/Net/AFP/UAMs/DHX2.pm` to:
```
    my $clientNonce = Math::BigInt->from_bytes(random_bytes($nonce_len - 1));
```
This forces the client nonce to be 1 byte shorter than usual.

Attempt to connect by running e.g.:

```
perl -Ilib examples/afpclient.pl afp://user@server/share
```

Authentication will fail 100% of the time, even though the value is appropriately aligned to the field.

**Expected behavior**
Authentication should succeed 100% of the time.

**Environment**
 - Server OS: TrueNAS Core 13.0U6
 - Client OS Linux Mint 21.3, Perl 5.40.0 (via Perlbrew)
 - Netatalk Version netatalk3-3.1.13_7,1

**Logs**
I don't think they're needed for this case, but if so, please let me know and I'll see about gathering some.

**Additional context**
Not a crash, but a misuse of libgcrypt.

**Comment by rdmark** [comment]
Thanks for reporting! Do you have an idea how to fix it? We happily welcome PRs. :)

BTW I can't believe I hadn't about your AFP client before. It's very encouraging to know that there's an alternative to afpfs-ng out there that is actively developed. Instantly starred!

**Comment by demonfoo** [comment]
I do, it looks like it needs to simply get the written length into a variable, and if the length is less than the expected length, it should be `memmove()`'d and the interstitial space `memset()`'d to 0's. I was also chasing a once-in-awhile auth failure in the `DHCAST128` UAM code, trying to figure out if it was in my client code or on the server side.

I actually contributed the UAM implementations to `afpfs-ng` based on the UAM implementations for my client years ago now. I recently decided to do some more enhancement and development to my own, and had noted occasional auth errors, but I'd assumed it was a bug on my side, until I found this.

**Comment by demonfoo** [comment]
https://github.com/Netatalk/netatalk/pull/1458

I just made the above PR. It builds cleanly on my local machine (Linux Mint 21.3).

**Comment by rdmark** [comment]
Thank you, LGTM. It built and ran cleanly on all the CI runners too.

Just one nitpick: Putting "DHX2" somewhere in the commit message would be handy, for when browsing in git log oneline mode or when generating a changelog. We have this in our developer guidelines: https://github.com/Netatalk/netatalk/wiki/Developer-Notes#commit-messages

And as a side note, I want to backport this patch to the 3.x and 2.x stable branches. Up to you if you want to contribute PRs for those branches. If you can't be bothered I will backport them. :)

**Comment by demonfoo** [comment]
I extracted the diff and applied it to the Debian sources for `netatalk`, and built the package locally and installed that; after installing the package and restarting `netatalk`, connecting to `afpd` with an intentionally abbreviated `clientNonce` authenticates correctly, without the nonce check error.

**Comment by rdmark** [comment]
Great, thanks for testing. I’m not surprised. The DHX2 UAM hasn’t changed much for a long long time. 

This project’s workflow for back porting patches is to cut additional PRs for each stable branch (currently: branch-netatalk-2-4 and branch-netatalk-3-2). It’s a bit of manual overhead up front but it saves us time later on because GitHub can generate the release notes for us.

**Comment by demonfoo** [comment]
Okay, I've created branches and cherry-picked the fix commit to each. This one is for 3.2:

https://github.com/Netatalk/netatalk/pull/1460

And this is for 2.4:

https://github.com/Netatalk/netatalk/pull/1461

Let me know if that looks good.

**Comment by rdmark** [comment]
Looks good! I touched up the PR titles a little to fit better in the context of future changelogs (the PR title is what GitHub puts in the release notes.)

again, big thanks for the report & patches. Please let us know if you encounter other bugs or areas of improvement.

**Comment by demonfoo** [comment]
I'll continue looking into the issue with the `DHCAST128` UAM as well, it seems to be failing somewhere in the `FPLoginCont()` callback, seemingly somewhere in the nonce check code, but unfortunately there is no logging in the code path where it's failing.
