### ISSUE TITLE
DHCAST128 UAM doesn't align private and public keys correctly

### ISSUE THREAD

**Issue by demonfoo** [Netatalk/netatalk#1464]
**Describe the bug**
In testing my AFP client, I discovered that occasionally authentication with the DHCAST128 UAM will fail for no clear reason, even when supplying the `afp://` URL via the command line. I discovered this is because if `Mb` (the server's "public" key part in the Diffie-Hellman exchange) or `K` (the "private" key) are shorter than `KEYSIZE`, the UAM code does not verify that they are aligned correctly to the memory regions they're being placed in.

**To Reproduce**
https://github.com/demonfoo/afp-perl

Get and install my AFP client code from the above repo.

Replace line 930 in `examples/afpclient.pl` with:

```perl
    my $line = "quit\n";
```

Then run e.g.:
```sh
while : ; do perl -Ilib examples/afpclient.pl --debug-afp "afp://user;AUTH=DHCAST128:password@server/volume" ; if [[ "$?" -ne 0 ]] ; then break ; fi ; done
```
Eventually it will fail with error -5019 (aka `kFPParamErr`), after a random number of attempts.

**Expected behavior**
No login failures should occur; logging in and disconnecting should proceed indefinitely.

**Environment**
 - Server OS: TrueNAS 13.0U5.1
 - Client OS: Linux Mint 21.3, Perl 5.40.0 (via Perlbrew)
 - Netatalk Version: netatalk3-3.1.13_7,1

**Logs**
Relevant code doesn't log anything enlightening.

**Additional context**
There is no crash, issue is due to misuse of OpenSSL DH computation routines.

**Comment by demonfoo** [comment]
Created PRs for this against:

`main` branch: https://github.com/Netatalk/netatalk/pull/1465
`branch-netatalk-3-2` branch: https://github.com/Netatalk/netatalk/pull/1466
`branch-netatalk-2-4` branch: https://github.com/Netatalk/netatalk/pull/1467

Please let me know if this all looks good.

**Comment by demonfoo** [comment]
Okay, looks like I _may_ not have fully fixed the issue, I'll need to investigate a bit more.

**Comment by demonfoo** [comment]
I realized why. I'll update the branches later to fix the remaining issue.

**Comment by demonfoo** [comment]
Okay, I've added an additional commit to each branch, and I'm testing it now to make sure I've completely addressed the issue.

**Comment by demonfoo** [comment]
FWIW, I've gone over 1000 iterations and not had a `kFPParamErr` failure.

**Comment by NJRoadfan** [comment]
For future commits, please prefix the 3.x and 2.x branch specific PRs with `[3.x]` and `[2.x]`.

**Comment by rdmark** [comment]
@demonfoo Can you please rebase the changeset for each PR into a single commit? The policy in this project is that each commit should represent a fully functioning and bug free (to the extent possible) revision of the code. 

I’m sure your know exactly how to do this, but here’s an example, from the work branch:

```
git rebase -i HEAD~2
git push --force
```

**Comment by demonfoo** [comment]
Done, commits are squashed in each branch.

**Comment by demonfoo** [comment]
Actually realized a debugging log entry that I added slipped through. Going to fix that.

**Comment by demonfoo** [comment]
Got those taken care of... now hopefully I won't see anything else I missed!

**Comment by rdmark** [comment]
Thanks for the patches! I did some minor touch-up of the PR descriptions to align with project conventions.

I will merge the PRs shortly. If you find further improvement areas, please file a new issue ticket.
