### ISSUE TITLE
[3.x] DSI tickle not being sent from server.

### ISSUE THREAD

**Issue by NJRoadfan** [Netatalk/netatalk#1514]
This affects Netatalk 3.x and main branches. The server should be sending tickles over DSI every 30 seconds to a client so that the client knows the server is still up. Netatalk 2.x is not affected and sends out tickles every 30 seconds over DSI.

To reproduce:
-Install Netatalk 3.x or main branch.
-Monitor your network connection. You should see tickles from the client every minute or so, but none from the server.
-Connect to Netatalk using MacOS 8.x-9.x via TCP/IP. After 4 minutes, the client will time out and disconnect.

MacOS X clients don't seem to be adversely affected by this. They support client sleep/reconnect and can recover somewhat gracefully from the lack of server tickles. There is a function called `alarm_handler()` in `afp_dsi.c` that handles the periodic tickle transmissions. Somewhere along the line, it broke.

**Comment by rdmark** [comment]
Good catch. I have observed this too intermittently, and now I understand the circumstances. 

If it’s not too risky to fix, I think it’s worth patching stable 3.2 as well.

**Comment by NJRoadfan** [comment]
A meson configuration setting was wrong. Fixed in #1515 and #1517.

**Comment by rdmark** [comment]
Autotools is not affected in 3.2?

**Comment by NJRoadfan** [comment]
Doesn't appear so. This option should have always been 'no' or 'false'.
