### ISSUE TITLE
netatalk-dbus.conf installed in deprecated location by default

### ISSUE THREAD

**Issue by smcv** [Netatalk/netatalk#1533]
**Describe the bug**
It appears that the `dbus_sysconfpath` into which you install `netatalk-dbus.conf` defaults to `/etc/dbus-1/system.d` or similar. Since the release of dbus 1.14.0 in 2022, that path is "officially" reserved for sysadmin overrides (similar to the use of `/etc/systemd` in systemd), and D-Bus configuration snippets installed by OS-level packages should normally be in the package's `datadir` instead, typically `/usr/share/dbus-1/system.d` (similar to the use of `/usr/lib/systemd` in systemd).

The reference implementation of D-Bus, dbus-daemon (part of dbus, used on e.g. Debian), has read configuration snippets from `/usr/share/dbus-1/system.d` since stable release 1.10.0 (2015).

The other widely-used implementation of D-Bus is dbus-broker (an independent reimplementation, used on e.g. Fedora), which I believe has always supported `/usr/share/dbus-1/system.d`.

**To Reproduce**
n/a, source code inspection only (I don't actually use netatalk myself)

**Expected behavior**
If no special build options are used, ideally I would expect `dbus_sysconfpath` to default to `datadir / 'dbus-1/system.d'` instead of the current `sysconfdir / 'dbus-1/system.d'`. This would avoid needing to take special measures to avoid overwriting local sysadmin customizations, as netatalk seems to do at the moment.

**Environment**
 - Netatalk Version: git main as of 2024-09-23

**Comment by smcv** [comment]
When installing into `/usr/local` in your CI, you might have to override this back to `/etc/dbus-1/system.d` - I don't think dbus-daemon or dbus-broker read policies from `/usr/local/share/dbus-1` by default.

**Comment by rdmark** [comment]
CI definitions updated & PRs merged.
