### ISSUE TITLE
Overzealous Libgcrypt version validation

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1550]
Now when we use Libgcrypt across the board for our UAMs, the arguably overzealous library version check will have an even bigger impact.

```
    if (!gcry_check_version (GCRYPT_VERSION)) {
        LOG(log_error, logtype_uams, "PAM DHX2: libgcrypt versions mismatch. Need: %s", GCRYPT_VERSION);
        result = AFPERR_MISC;
        goto error;
    }
```

Even a 0.0.1 version bump of Libgcrypt will fail this check, so if a distro for instance pushes out a Libgcrypt bugfix release, Netatalk has to be recompiled. This is something that has been reported by users ever since DHX2 was introduced 15 years ago.

Examples:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=568601
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=872437

**Comment by NJRoadfan** [comment]
I purposely didn't set it to fail in the DHX and RandNum UAMs. Seems that there was an error in the old API docs, because now they recommend doing the following:

```
       /* Version check should be the very first call because it
          makes sure that important subsystems are initialized.
          #define NEED_LIBGCRYPT_VERSION to the minimum required version. */
       if (!gcry_check_version (NEED_LIBGCRYPT_VERSION))
         {
           fprintf (stderr, "libgcrypt is too old (need %s, have %s)\n",
              NEED_LIBGCRYPT_VERSION, gcry_check_version (NULL));
           exit (2);
         }
```

Note that QEMU had the same problem: https://patchew.org/QEMU/20200527093409.3588189-1-rjones@redhat.com/

Changing the statement to NULL may all be whats needed.

**Comment by rdmark** [comment]
@NJRoadfan Thanks for doing the research. Do we even need this code, then? If I understand it correctly, `gcry_check_version (NULL)` will return the literal libgcrypt version string so the if statement will never be true and error never be thrown.

If we don't need check minimum library version right now, but want to keep the code for future use, one readable approach could be to define `NEED_LIBGCRYPT_VERSION` to NULL in uam.h and use that macro in the check. Thoughts?

**Comment by NJRoadfan** [comment]
The call to `gcry_check_version()` is strictly to initialize the library for use.

**Comment by rdmark** [comment]
Right, that's what the code comment says too if you actually read it. :)

And for reference, the docs: https://www.gnupg.org/documentation/manuals/gcrypt-devel/Initializing-the-library.html

I can put up a PR in a moment, unless you're already working on it.

**Comment by rdmark** [comment]
This is what I have in mind: https://github.com/Netatalk/netatalk/pull/1553

**Comment by rdmark** [comment]
The logic basically works as I expected. For instance, I have libgcrypt 1.10.1 on this Debian system. If `UAM_NEED_LIBGCRYPT_VERSION` is defined to "1.0.0" DHX2 will load without error, but when defined to "1.10.2" it will error out as below.

```
Sep 27 08:59:28 alien afpd[110561]: UAM DHX2 PAM: libgcrypt versions mismatch. Needs: 1.10.2 Has: 1.10.1
Sep 27 08:59:28 alien afpd[110561]: DHX2: Couldn't generate p and g
Sep 27 08:59:28 alien afpd[110561]: uam_load(uams_dhx2.so): uam_setup failed
Sep 27 08:59:28 alien afpd[110561]: uam: uams_dhx2.so load failure
```

One interesting observation is that DHX2 initializes immediately upon load, whereas DHX and RandNum initializes when a user tries to authenticate. Regardless, the error handling works for all of them.

**Comment by rdmark** [comment]
@NJRoadfan So is it safe to say that you agree we should not validate a minimum libgcrypt version right now?

**Comment by NJRoadfan** [comment]
No need that I can think of. The UAMs don't use any new features or functions of the library.

**Comment by rdmark** [comment]
Sounds good. Then I'll go ahead and merge the PRs later today, unless you have some suggestions on how to solve this differently.
