### ISSUE TITLE
Installation process on macOS

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1578]
### Discussed in https://github.com/Netatalk/netatalk/discussions/1577

<div type='discussions-op-text'>

<sup>Originally posted by **VitaliyYakob** October  2, 2024</sup>
Hello,

I used this [instruction](https://netatalk.io/stable/htmldocs/compile#build-macos) for deployment, and I have a couple of suggestions for improvement:

1. Do not use wget to get UnicodeData.txt, this is not the default in macOS, and curl is
`curl -O https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt`

2. After completing the "cd build && meson test" step, the user is in the build directory, but in the next step you need to go back to cd..</div>

**Comment by rdmark** [comment]
@VitaliyYakob What is the benefit of doing `curl -0`? The man page suggests it forces http v1.0 instead of curl's default. At a glance, wouldn't it be better to let curl decide?

**Comment by VitaliyYakob** [comment]
It's not 0 (zero), but O (letter), downloads the file to the current directory.


>     -O, --remote-name
>             Write output to a  local file named like  the remote file we  get.
>             (Only the file part  of the remote file is  used, the path is  cut
>             off.)
> 
>             The file is saved  in the current  working directory. If you  want
>             the file saved in a different directory, make sure you  change the
>             current working directory  before invoking curl  with this  option
>             or use --output-dir.
> 
>             The remote filename to use for saving is extracted from  the given
>             URL, nothing else, and if it already exists it is  overwritten. If
>             you want the  server to be  able to choose  the filename refer  to
>             --remote-header-name  which  can  be  used  in  addition  to  this
>             option. If the  server chooses  a filename and  that name  already
>             exists it is not overwritten.
> 
>             There is no URL  decoding done on the filename.  If it has %20  or
>             other URL  encoded  parts  of  the  name, they  end  up  as-is  as
>             filename.
> 
>             You may use this  option as many times as  the number of URLs  you
>             have.
> 
>             --remote-name can be used several times in a command line
> 
>             Example:
>              curl -O https://example.com/filename
> 
>             See      also       --remote-name-all,      --output-dir       and
>             --remote-header-name.

**Comment by rdmark** [comment]
That explains it, thanks. I'm using `--output` which is another alias for `-O` according the man page for curl 7.88.1
