### ISSUE TITLE
Update launchd commands on macOS

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1579]
### Discussed in https://github.com/Netatalk/netatalk/discussions/1577

<div type='discussions-op-text'>

<sup>Originally posted by **VitaliyYakob** October  2, 2024</sup>
3. The last action installation script loads and launches the netatakd daemon using outdated approaches
`Running custom install script '/bin/launchctl load -w /Library/LaunchDaemons/io.netatalk.daemon.plist'`

`man launchctl`

>  LEGACY SUBCOMMANDS
>      Legacy subcommands select the target domain based on whether they are executed as root or not. When executed as root, they target the system domain.
> 
>      load | unload [-wF] [-S sessiontype] [-D searchpath] paths ...
>               Recommended alternative subcommands: bootstrap | bootout | enable | disable
> 
>               Load the specified configuration files or directories of configuration files.  Jobs that are not on-demand will be started as soon
>               as possible. All specified jobs will be loaded before any of them are allowed to start. Note that per-user configuration files
>               (LaunchAgents) must be owned by root (if they are located in /Library/LaunchAgents) or the user loading them (if they are located
>               in $HOME/Library/LaunchAgents).  All system-wide daemons (LaunchDaemons) must be owned by root. Configuration files must disallow
>               group and world writes. These restrictions are in place for security reasons, as allowing writability to a launchd configuration
>               file allows one to specify which executable will be launched.

I suggest to consider the possibility of using a modern option

`launchctl bootstrap system/ /Library/LaunchDaemons/io.netatalk.daemon.plist`
`launchctl kickstart system/io.netatalk.daemon`</div>

**Comment by rdmark** [comment]
@VitaliyYakob Reading the man page paragraph about the `kickstart` subcommand, it seems like a drastic directive that overrides other configurations. For now I decided to use the `enable` subcommand instead. Please let me know if you disagree with this choice.

**Comment by VitaliyYakob** [comment]
@rdmark Hmm, maybe I misunderstood this command, but in my experiments Enable does not start Netatalk, but kickstart does.
```
% sudo netatalkd stop                           
Stopping netatalk fileserver...
 % sudo lsof -iTCP -sTCP:LISTEN -n -P | grep afpd
 % sudo launchctl enable system/io.netatalk.daemon
 % sudo lsof -iTCP -sTCP:LISTEN -n -P | grep afpd 
% sudo launchctl kickstart system/io.netatalk.daemon
 % sudo lsof -iTCP -sTCP:LISTEN -n -P | grep afpd    
afpd      44060           root    4u  IPv6 0x5c13f0d58a48efaa      0t0  TCP *:548 (LISTEN)
```

**Comment by rdmark** [comment]
Right, last I tested my observation was that `enable` starts netatalk on system reboot. It's a bit of a philosophical question which one is preferable. Do most users expect "installing" a piece software mean that the software is also launched?

One perspective here is that netatalk as a service kind of requires configuration (editing afp.conf) before it makes sense to launch it, so IMO `enable` is more appropriate than `kickstart`.

But I can be convinced otherwise. :)

**Comment by VitaliyYakob** [comment]
Exactly, I was trapped in the fact that I already have afpd.conf configured.
You're right, Enable will be enough.

**Comment by rdmark** [comment]
So from empirical testing in macOS Sequoia, it seems the correct sequence is:

For installing:
- enable
- bootstrap

For uninstalling:
- bootout
- disable

The former will actually start netatalk after step two, which is different from what I remember. But the latter won't stop netatalk if it's running.
