### ISSUE TITLE
FHS compliance

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1608]
This ticket is for discussing whether Netatalk should go all-in on [FHS 3.0 compliance](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html), or keep some of its non-compliant file system choices.

The one case in point that led to me starting this thread is the localstatedir, namely where CNID databases and other runtime data files are stored. The current default location is `/var/netatalk`. This location was introduced with [3.0-alpha1](https://netatalk.io/3.0/ReleaseNotes-3.0-alpha1) as a centralized place for these, as opposed to individual AFP volume dirs.

FHS 3.0 has this to say about the localstatedir:

> 5.8.1. Purpose
>
>This hierarchy holds state information pertaining to an application or the system. State information is data that programs modify while they run, and that pertains to one specific host. Users must never need to modify files in /var/lib to configure a package's operation, and the specific file hierarchy used to store the data must not be exposed to regular users. [[40]](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html#ftn.idm236090988912)
>
>State information is generally used to preserve the condition of an application (or a group of inter-related applications) between invocations and between different instances of the same application. State information should generally remain valid after a reboot, should not be logging output, and should not be spooled data.
>
>An application (or a group of inter-related applications) must use a subdirectory of /var/lib for its data. There is one required subdirectory, /var/lib/misc, which is intended for state files that don't need a subdirectory; the other subdirectories should only be present if the application in question is included in the distribution. [[41]](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html#ftn.idm236090984800)
>
>/var/lib/<name> is the location that must be used for all distribution packaging support. Different distributions may use different names, of course.

I read this as: Netatalk should put its local state data under `/var/lib/netatalk` rather than `/var/netatalk`

Two questions that I want to answer: 1. Are there other instances like this when netatalk uses file system locations that are non-FHS compliant, and 2. do we want to be FHS compliant in this project, or are the arguments for keeping local idiosyncrasies.

**Comment by NJRoadfan** [comment]
Keep in mind that moving the location of the CNID database will likely break upgrades.

Also moving from `/usr/local/sbin` to `/usr/sbin` might throw things off as well. The FHS doc's definition of "locally installed" software is kind of vague though. I know locally compiled installed of Netatalk have been going into `/usr/local` by default. Where have the official dpkg/rpm installs been going?

**Comment by rdmark** [comment]
@NJRoadfan Hehe I was going to ping you about this but you beat me to it.

> Keep in mind that moving the location of the CNID database will likely break upgrades.

Yes, the localstate change is likely going to break updates. I'm on the fence whether to push it out as a bugfix release, or start preparing for a 4.1 release series.

> Also moving from `/usr/local/sbin` to `/usr/sbin` might throw things off as well. The FHS doc's definition of "locally installed" software is kind of vague though. I know locally compiled installed of Netatalk have been going into `/usr/local` by default. Where have the official dpkg/rpm installs been going?

Sure but I didn't change anything but the CI jobs now, did I? All of the downstream packages have their own wrappers for Meson to set whatever prefix is required by distro policy. In Debian the prefix is always `/usr` and in FreeBSD it is always `/usr/local`, as two examples.

I updated the CI jobs to test how the localstate dir (sharedstate dir) changed depending on the prefix. As per https://mesonbuild.com/Builtin-options.html Meson will set the state dir prefix to `/var` if the prefix is `/usr` and to `/var/local` if the prefix is `/usr/local` which was surprising to me.

**Comment by rdmark** [comment]
As a side note, this investigation came about because of Debian packaging. It was flagged that the netatalk package uses a nonstandard localstatedir override. When I dug into it I realized that the netatalk deb has had a local override since the very beginning of packaging the 3.0 release series, because `/var/netatalk` was not accepted as a valid statedir as per Debian policy.

**Comment by NJRoadfan** [comment]
A lot of this packaging stuff has been tripping up the A2SERVER scripts. The change in storing the configuration directly in `/etc/netatalk` vs. `/usr/local/etc/netatalk` was another one.

**Comment by rdmark** [comment]
How about this as compromise: I make these changes, but put `/var/netatalk` as the default value of the "with-statedir-path" meson option. This should keep the default behavior the same as before, but with the scaffolding in place to turn on FHS compliant behavior in a future feature release.

**Comment by rdmark** [comment]
> A lot of this packaging stuff has been tripping up the A2SERVER scripts. The change in storing the configuration directly in `/etc/netatalk` vs. `/usr/local/etc/netatalk` was another one.

Sorry about the trouble. The whole pkgconfdir situation was a mistake/oversight during the Meson transition.

We have a `with-pkgconfdir-path` option now that allows you to get the old behavior back (config files into `/etc/netatalk`) that I assume you're aware of?

**Comment by rdmark** [comment]
> How about this as compromise: I make these changes, but put `/var/netatalk` as the default value of the "with-statedir-path" meson option. This should keep the default behavior the same as before, but with the scaffolding in place to turn on FHS compliant behavior in a future feature release.

On second thought, it's not this simple. I went back and checked the behavior of Autotools on the latest 3.2. Without any parameters, this also results in a CNID dir of `/usr/local/var/netatalk/CNID`. So the documentation has been incorrectly asserting that the default CNID dir is `/var/netatalk/CNID` for quite some time. The only time you get the latter is with a prefix of `/` which I think is exceedingly rare for both downstream distribution and self-built netatalk installs. The good news is that Meson and Autotools are aligned, so there shouldn't be any unexpected breakage for anyone doing the build system switch.

**Comment by rdmark** [comment]
@NJRoadfan I updated the PR. Please let me know what you think. In short, I added a statedir override option, but left the default behavior intact.

However, I made the spooldir FHS compliant, which I think should be safe. Can you see a reason this change would be disruptive?

**Comment by NJRoadfan** [comment]
Moving the spool directory shouldn't be a problem as it only stores temporary files.
