### ISSUE TITLE
Vintage AppleShare clients not connecting to server due to FPGetSvrInfo packet being too large.

### ISSUE THREAD

**Issue by NJRoadfan** [Netatalk/netatalk#1661]
One common issue encountered with vintage clients (basically anything older then AppleShare Client 3.8) is that they are unable to connect to a Netatalk server if the size of a FPGetSvrInfo response packet exceeds 512 bytes (they error out claiming no response from server). This limit can easily be reached with Netatalk 4.0 if one enables all UAMs and/or has a long host name. This is due to Netatalk 4.0 reporting many versions of the AFP protocol being available in addition to things like the UTF8 server name.

One possible fix is to limit reporting of AFP server versions above 2.1 to AppleTalk clients. This can be easily done as the current code path can be altered to deliver unique response to ASP and DSI clients.

**Comment by NJRoadfan** [comment]
I have an easy potential fix for this. It involves not sending an icon at all if a custom icon isn't configured. The icon+mask takes up 256 bytes of the reply. Otherwise the alternative is to build another status packet in `status_init()` just for AppleTalk connections. That would free up 42 bytes by not reporting AFP versions 2.2 to 3.4 to AppleTalk clients.

**Comment by rdmark** [comment]
I'm supportive of the easy solution. The default icons have little value anyways.

My only regret is that this situation makes it hard to have a single "universal" server for the newest and oldest Apple machines, with all of the bells and whistles activated at the same time: the fancy custom icon, all of the UAMs, and so on. It's a minor detail that few people will actually care about beyond myself.

**Comment by NJRoadfan** [comment]
Most of the additions to the FPGetSrvrInfo packet are exclusive to AFP3.0 and newer thus require TCP/IP. AppleTalk clients do not use the UTF8 server name or directory name.

**Comment by rdmark** [comment]
Right, and this is one argument for introducing a new status packet for AppleTalk like you say. Then you can configure your netatalk server in any way you please and have the older clients only get the FPGetSrvrInfo data that they need, without the need to compromise for newer clients.

The drawback is the added code complexity and maintenance, I suppose.

**Comment by NJRoadfan** [comment]
Fix is done. Of note, the code that builds the status string really needs a refactor. In addition it technically violates the AFP spec by not putting the icon data at the end of the response. Clients don't seem to care though as they just read the offset to find it.
