### ISSUE TITLE
[PATCH] Netatalk can't find BerkeleyDB headers

### ISSUE THREAD

**Issue by andy-js** [Netatalk/Netatalk#17]
Netatalk is failing to locate the BerkeleyDB headers on my system.  Here's the fix:

diff --git a/macros/db3-check.m4 b/macros/db3-check.m4
index 4135e5c..e378e43 100644
--- a/macros/db3-check.m4
+++ b/macros/db3-check.m4
@@ -87,7 +87,7 @@ if test "x$bdb_required" = "xyes"; then
     trybdbdir=""
     dobdbsearch=yes
     bdb_search_dirs="/usr/local /usr"
-    search_subdirs="/ /db5 /db5.1 /db51 /db5.0 /db50 /db4.8 /db48 /db4.7 /db47 /db4.6 /db46 /db4"
+    search_subdirs="/ /db6 /db5 /db5.1 /db51 /db5.0 /db50 /db4.8 /db48 /db4.7 /db47 /db4.6 /db46 /db4"
 
     bdbfound=no
     savedcflags="$CFLAGS"

**Comment by andy-js** [comment]
Github has mangled the patch but I think it's still obvious what the changes did.  It just added /db6 to the list of search dirs.

**Comment by slowfranklin** [comment]
Fixed for next release.
