### ISSUE TITLE
macipgw: Startup routine not compatible with aarch64 Linux

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#1735]
When attempting to launch macipgw on an aarch64 system, the optarg routine will always fail with `unknown option`. Looking at the data coming through optarg, there's an endless stream of ?s which normally indicate an unknown option letter or missing parameter.

Tested with Debian 13 (latest Testing), Alpine Linux, Asahi Fedora Remix.

**Comment by NJRoadfan** [comment]
Try compiling and running this revision: https://github.com/jasonking3/macipgw/commit/2a5f6a7521a627e46b18468d44f4306fb0a7b7ab

I've run this version on an RPi400 (which I believe is aarch64) with no issues. The next [commit](https://github.com/jasonking3/macipgw/commit/52d8068730b006eb4c53a1c38cb4d6915146979c), which was part of Adam's patchset, switched some variable types for 64bit compatibility, but that might have caused a regression?

**Comment by rdmark** [comment]
NJRoadfan found this fix in another thread, from Jason's fork: https://github.com/jasonking3/macipgw/commit/53ce4797b2d6111ced62e60f23bfeeac48f3f85c

So basically, using char to store the optargs was insufficient. And int was required.
