### ISSUE TITLE
macos: cnid_metad failing to load "setlimits: Invalid argument"

### ISSUE THREAD

**Issue by NJRoadfan** [Netatalk/netatalk#1793]
**Server OS:** macOS 10.15 Catalina

When attempting to launch netatalk, the `cnid_metad` service fails to launch with message: `setlimits: Invalid argument`

This is due to setting `rlim.rlim_max` in a `setrlimit()` call to 65535 when macOS limits this variable to 10240 (ref: https://github.com/apple-oss-distributions/xnu/blob/main/bsd/sys/syslimits.h and https://github.com/minio/minio/issues/9855)

https://github.com/Netatalk/netatalk/blob/e839b63cb320bd6c3dc31b4a554b7934224cfe80/etc/cnid_dbd/cnid_metad.c#L417-L434

**Fix:** Under macOS, set limit to 10240 instead of 65535. There are ways to [change this](https://gist.github.com/devinrhode2/4cbf7f02a9701510d61f5be0515b8286) at the system level, but it likely isn't needed.

**Comment by NJRoadfan** [comment]
Note: afpd has similar `setlimits()` function in `main.c` as well, although it doesn't seem to stop the daemon from launching.

**Comment by rdmark** [comment]
Are there any particular preconditions required to trigger this code path on macOS? 

I have not observed it on macOS 14 or 15. 

Regardless, I agree that lowering the number of permitted opened files to ~10k seems reasonable.

**Comment by NJRoadfan** [comment]
Just compile and run. Looking at the Emaculation thread, others have had the problem, so it appears to be OS version dependent.

**Comment by rdmark** [comment]
Can you please share the URL to the Emaculation thread? Sorry if you already did and I couldn’t find it. :)

To encapsulate this change, I suggest we introduce a MACOS (or DARWIN) compatibility macro.

**Comment by NJRoadfan** [comment]
https://www.emaculation.com/forum/viewtopic.php?t=11123

Apple has a macro already, should be defined as `__APPLE__` although some sources state that `__MACH__` should be used alongside of it.

**Comment by rdmark** [comment]
Do you want to attempt the PR or should I?

**Comment by NJRoadfan** [comment]
I am a bit occupied with other commitments at the moment. In my testing, I just changed `rlim.rlim_cur` and `rlim.rlim_max` to 10240 in the above snippet and it worked on Catalina.

**Comment by rdmark** [comment]
This seems to have not broken anything on macOS 15.1.1 -- https://github.com/Netatalk/netatalk/pull/1796

**Comment by rdmark** [comment]
Interestingly, macOS 15 reports a slightly higher upper limit:

```
ulimit -u
10666
```
