### ISSUE TITLE
Netatalk logs in as user sssd instead of username

### ISSUE THREAD

**Issue by knight-of-ni** [Netatalk/netatalk#1807]
**Describe the bug**
This was recently reported in redhat bugzilla:
https://bugzilla.redhat.com/show_bug.cgi

What you see below has been copy/pasted from the redhat bug report.

**To Reproduce**
Share home directory in afp.conf, then try to connect to the share remotely

Mac throws up an error message saying "There was a problem connecting to the server ...." 

**Expected behavior**
The finder window should come up with contents of the home directory share.

**Environment**
 - Server OS: Fedora 41
 - Client OS unknown
 - Netatalk Version 4.0.6

**Logs**
As can be seen, after authenticating my username (stephen), it logs in as user sssd instead, so it can't find the home directory.

```
Dec 07 16:13:06.864029 afpd[48249] {uams_dhx2_pam.c:325} (info:ad): DHX2 login: stephen
Dec 07 16:13:06.945597 afpd[48249] {uams_dhx2_pam.c:210} (info:ad): PAM DHX2: PAM Success
Dec 07 16:13:07.016240 afpd[48249] {uams_dhx2_pam.c:705} (info:ad): DHX2: PAM Auth OK!
Dec 07 16:13:07.016329 afpd[48249] {auth.c:245} (note:AFPDaemon): Login by sssd (AFP3.4)
Dec 07 16:13:07.024766 afpd[48249] {netatalk_conf.c:1323} (error:Default): readvolfile: user home "/run/sssd" doesn't match basedir regex "/home"
Dec 07 16:13:07.028887 afpd[48249] {netatalk_conf.c:1323} (error:Default): readvolfile: user home "/run/sssd" doesn't match basedir regex "/home"
Dec 07 16:13:11.274864 afpd[48249] {auth.c:827} (note:AFPDaemon): AFP logout by stephen
```

**Additional context**
This problem does not appear using Netatalk 3.1.18 on Rocky Linux 9.

I very quickly looked at netatalk_conf.c and the affected code has not been changed in years.

I am currently out of the county for work, but I thought I'd post this now to get eyes on it. I should be able to take a closer look into what it going on the week of the 16th.

**Comment by mrunge** [comment]
I ran into the exact same issue.

**Comment by NJRoadfan** [comment]
Hmm, `sssd` could be a reference to System Security Services Daemon. Maybe its a PAM issue? This has come up before: https://github.com/Netatalk/netatalk/issues/361

**Comment by rdmark** [comment]
I tested on my M1 MBP running Fedora Asahi Remix 40: building from bleeding edge netatalk code (4.0.8dev) and the pam.d/netatalk configuration from the rpm spec. The bug does not reproduce.

Curiously, I'm seeing log messages like this, though:

```
pam_sss(netatalk:session): Request to sssd failed. Cannot get stat of SSSD socket.
```

I wonder if the PAM library saw major changes between f40 and f41?

**Comment by rdmark** [comment]
@mrunge I'm curious if the PAM config file makes a difference or not. What happens if you replace the contents of /etc/pam.d/netatalk with the below and restart netatalk?

```
#%PAM-1.0
auth     include system-auth
account  include system-auth
password include system-auth
session  include system-auth
```

This is the default that we use when building netatalk from source, which I assume is more permissive than the one in the rpm spec.

**Comment by rdmark** [comment]
I have a fresh Fedora 41 system running in a VM now. Installing the netatalk 4.0.6 rpm via dnf, I could not reproduce the bug. Connecting and accessing the user home dir works, and no mention of sssd in the logs.

Perhaps some residual configuration from an in-place f40 to f41 upgrade is causing this?

**Comment by rdmark** [comment]
As an observation from this testing: when using the simple PAM configuration that is shipped with netatalk, you can always authenticate on the first try. But when using the complex PAM configuration shipped with the rpm, it takes 2-3 tries to authenticate. The first few tries fails silently.

It could be a coincidence and the data set it small, but I thought it was worth mentioning.

**Comment by mrunge** [comment]
I downgraded to netatalk 3.2.9 on F41, and I can still reproduce the issue.

But, I was able to figure out that my machine, unlike a freshly deployed machine was using an authentication profile named 'sssd'. I switched to the 'local' profile (default in the new deployment) by issuing
`# authselect select local`
which fixed the authentication issue.

Thanks a lot @rdmark

**Comment by rdmark** [comment]
You are very welcome! Good job unblocking yourself.

I wonder if there's anything we can do on the netatalk side to handle the sssd PAM configuration more gracefully?

**Comment by rdmark** [comment]
I added a note on this to the wiki, in case other users run into the same issue. 

https://github.com/Netatalk/netatalk/wiki/Installing-Netatalk-on-Fedora-Linux#netatalk-v4
