### ISSUE TITLE
Enable DDP by default

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#215]
Since the primary reason to run Netatalk 2.x over 3.x is the DDP / AppleTalk stack, I propose that we configure / build / install this functionality by default.

For the `configure` script we have:
- --enable-ddp
- --enable-cups
- --enable-timelord
- --enable-a2boot

In the template for `afpd.conf` the default configuration should start with:
- -transall

**Comment by slowfranklin** [comment]
> Since the primary reason to run Netatalk 2.x over 3.x is the DDP / AppleTalk stack, I propose that we configure / build / install this functionality by default.

+1

**Comment by rdmark** [comment]
Fixed with https://github.com/Netatalk/netatalk/pull/223

**Comment by rdmark** [comment]
I'm making no change to papd/CUPS, since it's detected and enabled automatically when libcups is installed on the system.

**Comment by rdmark** [comment]
This partially reverts https://github.com/Netatalk/netatalk/commit/7a06fbf04bb5c04715bad0e465540f961190e62c
