### ISSUE TITLE
atalkd fails to start during boot on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by rmcardle** [Netatalk/netatalk#232]
atalkd fails to start during boot on Raspberry Pi Zero W with the error, `atalkd: zero interfaces, exiting.` It retries 5 times but still fails.

It seems that it can't start until Wi-Fi has finished connecting. Changing `After=syslog.target network.target` to `After=syslog.target network-online.target` in `/usr/lib/systemd/system/atalkd.service` fixes the problem.

Running Raspberry Pi OS Lite released on February 21st 2023 based on Debian 11.6 Bullseye. Linux raspberrypi 5.15.84+ #1613 Thu Jan 5 11:58:09 GMT 2023 armv6l GNU/Linux

**Comment by rmcardle** [comment]
I'm currently running branch-netatalk-2-2 at commit c1aac12cd51ad2f43d9b401c43ba99258680b5ff.

https://github.com/Netatalk/netatalk/commit/c1aac12cd51ad2f43d9b401c43ba99258680b5ff

**Comment by rdmark** [comment]
@rmcardle Thanks for reporting, and finding the solution! I have observed the same on my Pi Zero Ws. PR here https://github.com/Netatalk/netatalk/pull/233

**Comment by rdmark** [comment]
Merged to branch-netatalk-2-2
