### ISSUE TITLE
ABI checks have not been run since 3.1.8

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#262]
The ABI check step of the release QA process has not been run since the 3.1.8 release https://github.com/Netatalk/netatalk/wiki/Developer-Notes#abi-checking

**Comment by rdmark** [comment]
@slowfranklin Since you were the last person committing an ABI file, can you comment on whether this QA mechanism is still valid today? I would assume so, and it seems to be a good idea to make sure we don't inadvertently change the behavior of the libatalk interface.

**Comment by slowfranklin** [comment]
Yes, it's a good idea to do semantic versioning of public libraries and this was initially added to allow external consumers of libatalk safe usage, but no, as afaict there are no external consumers of libatalk I just dropped maintaing the ABI stuff at some point and we can drop this stuff. As an additional change we can then make libatalk a private library.

**Comment by rdmark** [comment]
Now I understand the original intent. Agreed that there is little use in keeping this around. For starters I removed the ABI checking steps from the developer notes wiki page.

A few things to clean up:
- Remove the DEVELOPER flag from makefiles
- Remove VERSION_INFO from makefiles
- Remove the --enable-developer configure option
- Remove all stored abi files
- Remove any remaining documentation

Anything else?

**Comment by rdmark** [comment]
@slowfranklin Please see if this covers all the bases https://github.com/Netatalk/netatalk/pull/269
