### ISSUE TITLE
Add support for macOS hosts

### ISSUE THREAD

**Issue by dgsga** [Netatalk/netatalk#281]
Netatalk does run on modern Intel and Apple Silicon based Macs with a number of code patches which have been tested over a two-year period.

**Comment by rdmark** [comment]
As a side note, I think this would warrant a minor version bump, since it introduces a major new capability: netatalk 3.2.0

**Comment by slowfranklin** [comment]
Out of curiousity: why? Why running Netatalk on OS X when the builtin AFP server  is cleanly integrated with the OS, avoid the crutch of AppleDouble sidecar blob and the like.

**Comment by rdmark** [comment]
Didn't Apple get rid of the AFP *server* ages ago, and only kept the AFP *client* alive in macOS?

**Comment by rdmark** [comment]
The AFP server deprecated with Big Sur, according to MacWorld: https://www.macworld.com/article/234926/using-afp-to-share-a-mac-drive-its-time-to-change.html

**Comment by slowfranklin** [comment]
I kinda lost track when it AFP was deprecated in favor of SMB, quite a long time ago already apparently, and if the AFP server was ever actually *removed*, was it?

**Comment by dgsga** [comment]
Just checked, the Apple AFP server binary (afp) is definitely absent from Ventura. Quite relieved really as it might have made all my work on the macOS port null and void!

**Comment by slowfranklin** [comment]
> Just checked, the Apple AFP server binary (afp) is definitely absent from Ventura. Quite relieved really as it might have made all my work on the macOS port null and void!

:) Did you add a Mac specific metadata backend that stores all the Mac metadata natively in the filesystem or is it just build fixes so the metadata will be stored in AppleDouble sidecar files or xattrs?

**Comment by dgsga** [comment]
Just a minimal alteration to the ea search macro allows metadata to be stored in the native APFS filesytem.I don't have the programming knowledge to build a backend...

**Comment by dgsga** [comment]
Nearly there, just have to sort out an authentication issue...

**Comment by rdmark** [comment]
The code in in main now. Great job!

**Comment by rdmark** [comment]
for posterity, this was fixed in https://github.com/Netatalk/netatalk/pull/310
