### ISSUE TITLE
[PATCH] Netatalk can't find kerberos headers on illumos

### ISSUE THREAD

**Issue by andy-js** [Netatalk/Netatalk#31]
The kerberos headers on illumos are in /usr/include/kerberosv5

<pre>
diff --git a/macros/netatalk.m4 b/macros/netatalk.m4
index 28f5f1e..736ab5d 100644
--- a/macros/netatalk.m4
+++ b/macros/netatalk.m4
@@ -733,7 +733,7 @@ AC_MSG_RESULT($with_kerberos)
 
 if test x"$with_kerberos" != x"no"; then
    have_krb5_header="no"
-   AC_CHECK_HEADERS([krb5/krb5.h krb5.h], [have_krb5_header="yes"; break])
+   AC_CHECK_HEADERS([kerberosv5/krb5.h krb5/krb5.h krb5.h], [have_krb5_header="yes"; break])
    if test x"$have_krb5_header" = x"no" && test x"$with_kerberos" != x"auto"; then
       AC_MSG_FAILURE([--with-kerberos was given, but no headers found])
    fi
</pre>

**Comment by slowfranklin** [comment]
Committed. Thanks!
