### ISSUE TITLE
Generated sparql_parser.c|h code under revision control

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#337]
After regenerating the sparql_parser code with a more recent GNU Bison in https://github.com/Netatalk/netatalk/commit/ca9701d404ef02867d2797cfe7a194b7d351043e compiling the code became dependent on the presence of `yacc` which is a part of the `bison` package, and does not come standard in Debian Bookworm at least.

With a high level glance at the code I don't quite understand why that is, so this issue is to look deeper and fix or revert the change.

Unless there's a very good reason to have Bison yacc as a dependency, I think we should restore the previous behavior.

**Comment by rdmark** [comment]
For the record, I left the aforementioned change out of the stable 3.1.15 release for this reason.

**Comment by rdmark** [comment]
On the other hand I think it's a good idea that the sparql parser code is regenerated and kept fresh rather than staying 10+ old as before.

**Comment by rdmark** [comment]
Alternatively, we can stop distributing the generated code in the repo and depend on bison/yacc to generate the code on demand:

```
	etc/spotlight/sparql_parser.c
	etc/spotlight/sparql_parser.h
```

@dgsga Do you have an opinion here?

**Comment by dgsga** [comment]
My preference would be to stop distributing the generated code and depend on current versions of bison/yacc. Using up-to-date dependencies helps to minimise security vulnerabilities

**Comment by rdmark** [comment]
I can be on board with that. Platforms that have tracker are expected to have bison as well, generally speaking. 

Let’s just make sure that building doesn’t fail when spotlight is disabled, and the generated code hasn’t been generated.

**Comment by rdmark** [comment]
This should do the trick https://github.com/Netatalk/netatalk/pull/736

I tested that the code builds with and without spotlight. We already have an optional check for bison/yacc in the autoconf macro, but maybe we need to add a mandatory check under the SPOTLIGHT umbrella as well..

**Comment by rdmark** [comment]
Spruced up the autoconf macro, with inspiration from https://github.com/yandex/pire/blob/master/configure.ac

It should now bail out only when bison/flex is missing only when the generated code is also missing, which will be handy when building from f.e. tarballs.
