### ISSUE TITLE
Very slow data transfer HP-Prodesk-SSD <-> MacBook M1

### ISSUE THREAD

**Issue by ChR-iSz** [Netatalk/netatalk#352]
Hello,

my netatalk installation runs on a HP Prodesk with SSD Drive. Client is my MacBook with M1 chip.
Netatalk version is netatalk 3.1.12 (debian 11 - bullseye).

Copy files ( from Macbook M1) with 480 MB (r.b. 50 Files) to Debian netatalk takes over 25 minutes with GB-Lan ??

Whats wrong here...?

<img width="415" alt="Bildschirmfoto 2023-06-05 um 23 15 08" src="https://github.com/Netatalk/netatalk/assets/49807897/07d1034b-5ba3-451b-81de-5674f661bef2">

**Comment by rdmark** [comment]
Can you please share a debug log from this scenario? There might be signs of some recurring error state that netatalk has to continuously recover from.

Also, what file system are you using on the netatalk server system?

**Comment by ChR-iSz** [comment]
Sorry,

I have no logs. The issue is three month old and i switch to samba which running as expected.

The server software was Debian 11 (buster) plain, without desktop.

**Comment by rdmark** [comment]
Samba is definitely more performant on SMB-first versions of macOS.

The reason I'm keeping netatalk alive is for networking with a really old Macs where Samba can be clunky or not work at all.
