### ISSUE TITLE
[PATCH] File copy fails on illumos

### ISSUE THREAD

**Issue by andy-js** [Netatalk/Netatalk#36]
This is a particularly frustrating bug.  When trying to copy files Finder comes back with a "Permission Denied" because the user copying the file doesn't have access to its extended attributes.  This is the wrong thing to do.

The change below updates the call to vfs_copyfile() to not set err and this allows the copy to continue successfully and silently ignores the extended attributes that cannot be read - well not completely silently, there is still an entry in the log file about it.

I also updated the comment for sys_ea_copyfile to make it clearer that it is returning an AFP status code and not an errno as the original code implies.

<pre>
diff --git a/etc/afpd/file.c b/etc/afpd/file.c
index 27e5212..ec28853 100644
--- a/etc/afpd/file.c
+++ b/etc/afpd/file.c
@@ -1455,7 +1455,7 @@ int copyfile(struct vol *s_vol,
         LOG(log_error, logtype_afpd, "copyfile('%s'): %s", src, strerror(errno));
 
     if (err == 0)
-        if ((err = d_vol->vfs->vfs_copyfile(d_vol, sfd, src, dst)) != 0)
+        if (d_vol->vfs->vfs_copyfile(d_vol, sfd, src, dst) != AFP_OK)
             LOG(log_error, logtype_afpd, "copyfile('%s'): %s", src, strerror(errno));
 
     if (err < 0)
diff --git a/libatalk/vfs/ea_sys.c b/libatalk/vfs/ea_sys.c
index 7415302..2c616ac 100644
--- a/libatalk/vfs/ea_sys.c
+++ b/libatalk/vfs/ea_sys.c
@@ -465,9 +465,22 @@ int sys_remove_ea(VFS_FUNC_ARGS_EA_REMOVE)
 }
 
 /*
- * @brief Copy EAs
+ * Function: sys_ea_copyfile
  *
- * @note Supports *at semantics, therfor switches back and forth between sfd and cwd
+ * Purpose: copy EAs
+ *
+ * Arguments:
+ *
+ *    vol          (r) current volume
+ *    sdf          (r) source file descriptor
+ *    src          (r) source path
+ *    dst          (r) destination path
+ *
+ * Return AFP code AFP_OK on success or appropriate AFP error code
+ *
+ * Effects:
+ *
+ * Copies EAs from source file to dest file.
  */
 int sys_ea_copyfile(VFS_FUNC_ARGS_COPYFILE)
 {
</pre>

**Comment by slowfranklin** [comment]
I'm not convinced silently dropping xattrs is the right thing to do. Why does the user have permissions to read the source file, but lacks permissions to read its xattrs?

**Comment by andy-js** [comment]
The user has permission to read some attributes but not all of them.  Some attributes are system attributes and can only be read by root.

**Comment by slowfranklin** [comment]
Can you give an example? Maybe we whould build a list of system attributes that should be ignored instead of paving over the problem and ignoring failed xattr copies for all xattrs?

**Comment by andy-js** [comment]
OK here's an example.  This attribute was set by the illumos SMB server as far as I can tell.

<pre>
SUNWsmb:com.apple.quarantine:$DATA
</pre>

I don't think building a list of attributes to ignore is the best way to go.  The solaris_list_xattr function should be filtering stuff we don't have permission to read out, like it does on other platforms.

**Comment by andy-js** [comment]
Scratch that.  I think it is good idea to filter out this particular property.  Netatalk needs to be more forgiving of bad extended attributes in general though.

**Comment by andy-js** [comment]
I think we should go with something like this.  Completely untested BTW.

<pre>
diff --git a/libatalk/vfs/ea_sys.c b/libatalk/vfs/ea_sys.c
index 7415302..a821e0e 100644
--- a/libatalk/vfs/ea_sys.c
+++ b/libatalk/vfs/ea_sys.c
@@ -535,6 +535,12 @@ int sys_ea_copyfile(VFS_FUNC_ARGS_COPYFILE)
                if (STRCMP(name, ==, AD_EA_META))
                        continue;
 
+#ifdef SOLARIS
+               /* skip special attributes set by SMB server */
+               if (!strncmp(name, "SUNWsmb:", 8))
+                       continue;
+#endif
+
                if (sfd != -1) {
                        if (fchdir(sfd) == -1) {
                                LOG(log_error, logtype_afpd, "sys_ea_copyfile: cant chdir to sfd: %s",
</pre>

**Comment by slowfranklin** [comment]
On Mon, Feb 22, 2016 at 07:01:50AM -0800, Andrew Stormont wrote:
> I think we should go with something like this.  Completely untested BTW.
> 
> <pre>
> diff --git a/libatalk/vfs/ea_sys.c b/libatalk/vfs/ea_sys.c
> index 7415302..a821e0e 100644
> --- a/libatalk/vfs/ea_sys.c
> +++ b/libatalk/vfs/ea_sys.c
> @@ -535,6 +535,12 @@ int sys_ea_copyfile(VFS_FUNC_ARGS_COPYFILE)
>                 if (STRCMP(name, ==, AD_EA_META))
>                         continue;
>  
> +#ifdef SOLARIS
> +               /* skip special attributes set by SMB server */
> +               if (!strncmp(name, "SUNWsmb:", 8))
> +                       continue;
> +#endif
> +
>                 if (sfd != -1) {
>                         if (fchdir(sfd) == -1) {
>                                 LOG(log_error, logtype_afpd, "sys_ea_copyfile: cant chdir to sfd: %s",
> </pre>

lgtm.

I've somewhat lost track of your proposed patches and pull
requests. :/ Is there a single pull requests with *all* changes in one
patchset that I can grind my teeth into? If not, can you create one? :)

Cheerio!
-slow

**Comment by andy-js** [comment]
I only have one pending at the moment and it's #38.  I will create a few more for those other changes - I'm not a fan of bunging 'em all in together.

**Comment by andy-js** [comment]
I think this is a better version:

<pre>
diff --git a/libatalk/vfs/ea_sys.c b/libatalk/vfs/ea_sys.c
index 2c616ac..04d1817 100644
--- a/libatalk/vfs/ea_sys.c
+++ b/libatalk/vfs/ea_sys.c
@@ -37,6 +37,11 @@
 #include &lt;atalk/unix.h&gt;
 #include &lt;atalk/compat.h&gt;
 
+#ifdef SOLARIS
+#include &lt;sys/attr.h&gt;
+#include &lt;smbsrv/smb_vops.h&gt;
+#endif
+
 /**********************************************************************************
  * EA VFS funcs for storing EAs in nativa filesystem EAs
  **********************************************************************************/
@@ -548,6 +553,16 @@ int sys_ea_copyfile(VFS_FUNC_ARGS_COPYFILE)
         if (STRCMP(name, ==, AD_EA_META))
             continue;
 
+#ifdef SOLARIS
+               /* Skip special attributes set by NFS server */
+               if (!strcmp(name, VIEW_READONLY) || !strcmp(name, VIEW_READWRITE))
+                       continue;
+
+               /* Skip special attributes set by SMB server */
+               if (!strncmp(name, SMB_STREAM_PREFIX, SMB_STREAM_PREFIX_LEN))
+                       continue;
+#endif
+
         if (sfd != -1) {
             if (fchdir(sfd) == -1) {
                 LOG(log_error, logtype_afpd, "sys_ea_copyfile: cant chdir to sfd: %s",
diff --git a/libatalk/vfs/extattr.c b/libatalk/vfs/extattr.c
index 9e45bb8..9257733 100644
--- a/libatalk/vfs/extattr.c
+++ b/libatalk/vfs/extattr.c
@@ -897,8 +897,7 @@ static ssize_t solaris_list_xattr(int attrdirfd, char *list, size_t size)
 
        while ((de = readdir(dirp))) {
                size_t listlen;
-               if (!strcmp(de->d_name, ".") || !strcmp(de->d_name, "..") ||
-                    !strcmp(de->d_name, "SUNWattr_ro") || !strcmp(de->d_name, "SUNWattr_rw")) 
+               if (!strcmp(de->d_name, ".") || !strcmp(de->d_name, ".."))
                {
                        /* we don't want "." and ".." here: */
                        LOG(log_maxdebug, logtype_default, "skipped EA %s\n",de->d_name);
</pre>

**Comment by slowfranklin** [comment]
I think this issue is resolved.
