### ISSUE TITLE
afpd: systemd-logind ReleaseSession rejected by dbus-daemon

### ISSUE THREAD

**Issue by RichieB2B** [Netatalk/netatalk#361]
As reported at [https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018106](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018106)

I am using netatalk for time machine backups. After every session I see this line in /var/log/auth.log
```
2023-07-01T22:31:47.223949+02:00 my-server dbus-daemon[1538889]: [system] Rejected send message, 2 matched rules; type="method_call", sender=":1.153636" (uid=145 pid=2690475 comm="/usr/sbin/afpd -d -F /etc/netatalk/afp.conf") interface="org.freedesktop.login1.Manager" member="ReleaseSession" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=1538900 comm="/lib/systemd/systemd-logind")
```
Today I finally found the solution at [https://bugs.launchpad.net/ubuntu/+source/netatalk/+bug/1538004](https://bugs.launchpad.net/ubuntu/+source/netatalk/+bug/1538004)

It is simple really, in `/etc/pam.d/netatalk` replace this line:
```
@include common-session
```
with this line:
```
@include common-session-noninteractive
```
This fixed the issue for me.

**Comment by rdmark** [comment]
Thanks for filing this! Since the macro suggests that this particular branch applies to SuSE in addition to Debian, let me run a quick test on openSUSE to make sure this works cross-distro.

**Comment by rdmark** [comment]
Tested on Debian Bookworm & openSUSE Tumbleweed. Works as expected.

Next up is to back port this to the 2.2 branch.

**Comment by rdmark** [comment]
2.2 branch PR https://github.com/Netatalk/netatalk/pull/367

**Comment by mwmahlberg** [comment]
This also applies for Fedora 38 at least. Using it on a Raspi, so I can only confirm this for the arm side of things.

**Comment by rdmark** [comment]
@mwmahlberg Can you tell me the location and contents of the pam.d auth dir?

This is the current RH/Fedora logic:

```
        dnl RHEL/FC
        elif test -f "$pampath/system-auth" ; then
           PAM_DIRECTIVE=include
           PAM_AUTH=system-auth
           PAM_ACCOUNT=system-auth
           PAM_PASSWORD=system-auth
           PAM_SESSION=system-auth
```

We need to figure out if the non-interactive configuration sits in that same file, or if there's another one we should import instead.

**Comment by rdmark** [comment]
I booted into Fedora Linux Asahi Remix (39 based) on my MacBook to investigate. This is what I see.

```
dmark@daniel-macbookpro:/etc/pam.d$ cat system-auth 
# Generated by authselect
# Do not modify this file manually, use authselect instead. Any user changes will be overwritten.
# You can stop authselect from managing your configuration by calling 'authselect opt-out'.
# See authselect(8) for more details.

auth        required                                     pam_env.so
auth        required                                     pam_faildelay.so delay=2000000
auth        [default=1 ignore=ignore success=ok]         pam_usertype.so isregular
auth        [default=1 ignore=ignore success=ok]         pam_localuser.so
auth        sufficient                                   pam_unix.so nullok
auth        [default=1 ignore=ignore success=ok]         pam_usertype.so isregular
auth        sufficient                                   pam_sss.so forward_pass
auth        required                                     pam_deny.so

account     required                                     pam_unix.so
account     sufficient                                   pam_localuser.so
account     sufficient                                   pam_usertype.so issystem
account     [default=bad success=ok user_unknown=ignore] pam_sss.so
account     required                                     pam_permit.so

password    requisite                                    pam_pwquality.so local_users_only
password    sufficient                                   pam_unix.so yescrypt shadow nullok use_authtok
password    [success=1 default=ignore]                   pam_localuser.so
password    sufficient                                   pam_sss.so use_authtok
password    required                                     pam_deny.so

session     optional                                     pam_keyinit.so revoke
session     required                                     pam_limits.so
-session    optional                                     pam_systemd.so
session     [success=1 default=ignore]                   pam_succeed_if.so service in crond quiet use_uid
session     required                                     pam_unix.so
session     optional                                     pam_sss.so
```

There's no equivalent "non-interactive" profile that I can see, unlike Debian. Some other solution may be required.

**Comment by rdmark** [comment]
For reference, this is the diff between interactive and non-interactive pam configs.

```
dmark@macuntu:/etc/pam.d$ diff -u common-session common-session-noninteractive 
--- common-session	2023-10-01 23:52:52.307711006 +0000
+++ common-session-noninteractive	2023-10-01 23:52:52.407696570 +0000
@@ -1,9 +1,10 @@
 #
-# /etc/pam.d/common-session - session-related modules common to all services
+# /etc/pam.d/common-session-noninteractive - session-related modules
+# common to all non-interactive services
 #
 # This file is included from other service-specific PAM config files,
 # and should contain a list of modules that define tasks to be performed
-# at the start and end of interactive sessions.
+# at the start and end of all non-interactive sessions.
 #
 # As of pam 1.0.1-6, this file is managed by pam-auth-update by default.
 # To take advantage of this, it is recommended that you configure any
@@ -26,5 +27,4 @@
 session optional			pam_umask.so
 # and here are more per-package modules (the "Additional" block)
 session	required	pam_unix.so 
-session	optional	pam_systemd.so 
 # end of pam-auth-update config
```

**Comment by rdmark** [comment]
So in conclusion, the generated netatalk.pam on Fedora needs to *not* have this line, I think:

```
-session    optional                                     pam_systemd.so
```

**Comment by rdmark** [comment]
@knight-of-ni Do you have any insights into how Fedora deals with PAM configuration variants like this? Do you have something in your rpm packaging scripts that handles this?

In fact, from my brief testing on Fedora Remix Asahi Linux 39, I can't see that our install target even installs the generated `netatalk` PAM config...

**Comment by knight-of-ni** [comment]
Yep. The pam config you posted earlier is included as an additional source file in the rpm specfile:
https://src.fedoraproject.org/rpms/netatalk/blob/rawhide/f/netatalk.spec#_60
https://src.fedoraproject.org/rpms/netatalk/blob/rawhide/f/netatalk.pam-system-auth

This file predates my time as the Netatalk package maintainer. I never really looked too closely at it.
If it helps, feel free to include it in the upstream project.

**Comment by rdmark** [comment]
@knight-of-ni Thanks for sharing, it is interesting to see how this was tackled downstream!

I'm a bit hesitant to manage a custom PAM config file in the upstream project. I think there's a bigger risk it goes stale here than in the downstream package script.

One idea though... I wonder if it's possible to fit an equivalent configuration into the existing template: https://github.com/Netatalk/netatalk/blob/main/config/pam/netatalk.tmpl

Something worth investigating...

**Comment by rdmark** [comment]
@mwmahlberg Thanks for sharing! So what you have there, is exactly the [template used by the rpm packaging recipe](https://src.fedoraproject.org/rpms/netatalk/blob/rawhide/f/netatalk.pam-system-auth) that is linked in the previous comment. So this suggests that you installed netatalk via the rpm, and not from source. Is this accurate?

The reason our netatalk pam config is different is most likely because I installed from source in this particular instance.

Anyways, if the pam behavior on Fedora is the same as on Debian (which I would expect) it means that this line... `session    include      system-auth` in the netatalk pam config imports system-auth and which has this line... `-session    optional                                     pam_systemd.so` which is the one that would trigger the "rejected send messages".

Either the system pam config needs to be modified (on the fly?) or the netatalk pam config for the rpm package needs to be updated to work properly with today's Fedora default. More research is required...

**Comment by mwmahlberg** [comment]
@rdmark Indeed, I installed it from an RPM. Actually, mid-term I think of utilizing cockpit to provide a UI for setting up TimeMachine Backups. Which basically means a UI for netatalk.

@rdmark @knight-of-ni In this case, it should be easy enough to test, as far as I can see it:

1. Copy over the contents of system-auth into the netatalk pam.d module.
2. Remove (?) systemd from the result.
3. Restart netatalk daemon and check for functionality.

I will try this as soon as possible and will let you know the results.

**Comment by rdmark** [comment]
@mwmahlberg Cockpit looks neat! 

We do have a [Webmin module](https://github.com/Netatalk/netatalk-webmin) for netatalk which I've recently been improving upon. It works fairly well for basic administration of netatalk, including enabling TM for a volume. It does not, however, create dirs and set permissions on the dir for you. You have to prepare a dir elsewhere. I assume your use case is to do the administration end-to-end in the Web UI?

**Comment by rdmark** [comment]
@mwmahlberg Since the original issue for Debian was resolved and the solution for Fedora looks to be quite different, let me close this ticket again. May I ask you to create a new ticket for the Fedora situation?

**Comment by mwmahlberg** [comment]
@rdmark 

> @mwmahlberg Cockpit looks neat!
> 
> We do have a [Webmin module](https://github.com/Netatalk/netatalk-webmin) for netatalk which I've recently been improving upon. It works fairly well for basic administration of netatalk, including enabling TM for a volume. It does not, however, create dirs and set permissions on the dir for you. You have to prepare a dir elsewhere. I assume your use case is to do the administration end-to-end in the Web UI?

Indeed it is. The idea is to have a small Fedora distribution for converting a Raspi into a fully fledged TimeMachine and then some (for example Storage/LTS on SSE S3 instead of a local disk). I very much assume I am not the only one with that use case. The neat thing about Cockpit is that one has a bridge for about any operation one needs to do. In a local network, the security risk of that is (imho) acceptable.

**Comment by mwmahlberg** [comment]
> @mwmahlberg Since the original issue for Debian was resolved and the solution for Fedora looks to be quite different, let me close this ticket again. May I ask you to create a new ticket for the Fedora situation?

Will do later this day or tomorrow.
