### ISSUE TITLE
netatalk 2.2: `systemctl daemon-reload` performed by make install?

### ISSUE THREAD

**Issue by VorpalBlade** [Netatalk/netatalk#405]
I'm trying to create an Arch Linux AUR package for netatalk 2.2 for use with my retro computers. One strange thing that happens is that while I'm running `make install` with a `DESTDIR` set as part of the package building, it pops up a dialog asking for password. I have traced this down to `systemctl daemon-reload` in `distrib/initscripts/Makefile.am`.

I believe this only makes sense for when a user is running `sudo make install` directly, as opposed to `make install` running during a package install. As such I would like a way to turn this off (either by default, with a configure flag or an environment variable to make install).

For now I'm going to patch this out locally. but I would prefer an upstream solution.

**Comment by rdmark** [comment]
For the record, this one affects netatalk3 as well...

I'd like to keep the default behavior as-is, since without the daemon-reload the newly installed systemd services aren't activated. Having to run that command manually afterwards every time would be clunky, IMHO. Arch is probably niche in its non-privileged software installation. I'm open to be convinced otherwise though. :)

So either the configure flag or env variable option to opt out seems like the way forward.

Thoughts?

**Comment by VorpalBlade** [comment]
> Arch is probably niche in its non-privileged software installation.

You absolutely need privileges to *install* the package, this is about *building* the package, which is done non-privileged.

As far as I remember this works the same (or mostly the same) on other distros too. Both Debian and Arch uses `fakeroot` ([man page](https://man.archlinux.org/man/fakeroot.1.en)) to run the install command without privleges, but with a LD_PRELOAD to tell it that it is privileged. This also captures additional information such as setuid/setgid, uid/gid changes, etc that a normal user couldn't do. This is stored and then incorporated into the tar for the package later on.

As far as I remember (it has been over a decade since I used it) Gentoo did something similar. And I have no idea what the RPM family of distros do.

For some reason it seems `systemctl` outsmarts this. My guess is because it tries to use dbus.

**Comment by VorpalBlade** [comment]
Oh and I forgot to answer the second part of your post:

> So either the configure flag or env variable option to opt out seems like the way forward.

Sounds good, configure flag is a bit more discoverable for packagers, but probably more work (more files to change). I'll leave that decision up to you.

**Comment by rdmark** [comment]
I'm thinking that for simplicity, we can disable both the install as well as uninstall hooks when running non-privileged. Neither of those operations make sense if you don't have root access. Do you have an idea why this would be a bad idea?

**Comment by VorpalBlade** [comment]
Sounds good to me

**Comment by rdmark** [comment]
Please test this solution: https://github.com/Netatalk/netatalk/pull/419

**Comment by VorpalBlade** [comment]
> Please test this solution: #419

Seems to work fine

**Comment by VorpalBlade** [comment]
You are some of the most responsive upstream I have ever encountered, and for a project only relevant to retro computers no less! I'm impressed. Thanks.

**Comment by rdmark** [comment]
Happy to be of service! Thanks for finding good bugs. Especially the systemd stuff. I hacked together that solution two years ago when I had no idea what I was doing.
