### ISSUE TITLE
--disable-ddp should also disable papd/a2boot/timelord

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#423]
When configuring with `--disable-ddp` there are appletalk related symbols that don't get built which leads to papd/a2boot/timelord to fail to compile.

I think we should make `--disable-ddp` disable all of the appletalk related code, and also do away with the separate `--disable-a2boot` `--disable-timelord` at least (not sure about `--disable-cups`)

**Comment by NJRoadfan** [comment]
If papd isn't being compiled, then CUPS isn't used by netatalk at all. --disable-cups is a papd specific macro.

**Comment by rdmark** [comment]
Agreed. The reason I'm not sure about `--disable-cups` is that it doesn't seem to disable papd proper, just the CUPS integration of papd. I could be mistaken though because this is just what I observed when doing black box testing. Some reading of the code is required.

**Comment by NJRoadfan** [comment]
papd doesn't require CUPS. It can spool jobs to any manually configured lpr queues.

**Comment by rdmark** [comment]
Yes never mind, I think the papd checks are already conditional of USE_APPLETALK.

It's only the COMPILE_TIMELORD and COMPILE_A2BOOT conditionals that should be removed and branches folded under USE_APPLETALK.
