### ISSUE TITLE
make 3.1.15 available to Ubuntu 23.xx Lunar Lobster

### ISSUE THREAD

**Issue by CaliLuke** [Netatalk/netatalk#426]
I just installed netatalk on my Ubuntu home server with Apt Get and I noticed it pulls version 3.1.14. I checked on

https://launchpad.net/ubuntu/+source/netatalk

and I see the latest version seems to be available only for Mantic Minotaur which is still in development. Given the list of fixed bugs IMHO would be appropriate to make .15 the version installed by default unless there's incompatibilities with the previous releases of Ubuntu.

**Comment by rdmark** [comment]
Do you have a contact point at Canonical who manages the package updates?

What the downstream distributions do with netatalk releases and patches is out of the control of this project. I know for a fact that Debian unstable has a netatalk 3.1.15 package so it's up to Ubuntu when they want to adopt it.

**Comment by rdmark** [comment]
Closing this, since downstream packaging are out of the project's control.

On the launchpad page I see the names and contact information of Ubuntu packagers, so I would suggest reaching out to them directly!
