### ISSUE TITLE
Turn libatalk into a private library

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#427]
As per the discussion in https://github.com/Netatalk/netatalk/issues/262 -- we currently distribute a shared libatalk.so library, however to our best knowledge there are no external consumers of the libatalk library, so this is to turn it into a private library.

**Comment by rofore** [comment]
What about https://github.com/Godzil/lpstyl ?

**Comment by rdmark** [comment]
@rofore thats a neat project, I wasn’t aware of it before!

if I read the code correctly, its using libatalk to access netatalk’s appletalk networking interface specifically. 

Hence, it only really matters for netatalk v2 right now and not v3. 

At the same time, we’ve been contemplating grafting appletalk back onto v3 so that might be an argument for keeping the shared library architecture for the time being.

**Comment by rdmark** [comment]
Discarding this for now as per the above discussion.
