### ISSUE TITLE
No need to check for attropen on Solaris

### ISSUE THREAD

**Issue by andy-js** [Netatalk/Netatalk#44]
configure checks for attropen on Solaris but this function isn't used anywhere in the code.  It probably makes sense to drop this check entirely and just use #ifdef SOLARIS everywhere.  I think this also makes the code clearer.

**Comment by andy-js** [comment]
It would be good to get some clarification on whether or not HAVE_EAFD is only defined on Solaris which seems to be the case.

**Comment by slowfranklin** [comment]
On Mon, Feb 22, 2016 at 10:20:33AM -0800, Andrew Stormont wrote:
> configure checks for attropen on Solaris but this function isn't
> used anywhere in the code.  It probably makes sense to drop this
> check entirely and just use #ifdef SOLARIS everywhere.  I think this
> also makes the code clearer.

the golden rule is: check for features, not platforms.

Cheerio!
-slow

**Comment by slowfranklin** [comment]
On Mon, Feb 22, 2016 at 10:22:15AM -0800, Andrew Stormont wrote:
> It would be good to get some clarification on whether or not
> HAVE_EAFD is only defined on Solaris which seems to be the case.

yes. But again, we want conditional code built based on features, not
platforms.

Cheerio!
-slow

**Comment by andy-js** [comment]
In the case of attropen we're checking for a function that exists only on Solaris and if we find it we enable code in extattr.c (solaris_attropen, solaris_list_xattr, etc), none of which makes use of this function.

This means attropen is really just a sentinel - a marker that tells us to enable this functionality because the platform we're on supports it.  ifdef SOLARIS is a better way of doing that.

**Comment by andy-js** [comment]
If we want to check for something we really should be checking to see if O_XATTR is defined, I still don't think that makes any more sense than checking if SOLARIS is defined though.

I will forget about HAVE_EAFD for now because it could be extended to cover platforms.  As far as I can tell Linux already has support for the needed functionality through the fgetxattr and fsetattr functions.

**Comment by slowfranklin** [comment]
On Mon, Feb 22, 2016 at 02:05:26PM -0800, Andrew Stormont wrote:
> In the case of attropen we're checking for a function that exists
> only on Solaris and if we find it we enable code in extattr.c
> (solaris_attropen, solaris_list_xattr, etc), none of which makes use
> of this function.

It doesn't? Hm. If we're talking about the xattr platform
compatibiltiy layer, iirc this was taken from Samba and then suit to
fit. I'd have to check the code in order determine what would make the
most sense here.

> This means attropen is really just a sentinel - a marker that tells
> us to enable this functionality because the platform we're on
> supports it.  ifdef SOLARIS is a better way of doing that.

Iirc the module in question uses feature/function conditionals, not
#ifdef LINUX or #ifdef BSD, so it may make sense to stick to that for
the Solaris functions.

Cheerio!
-slow

**Comment by slowfranklin** [comment]
On Mon, Feb 22, 2016 at 02:09:54PM -0800, Andrew Stormont wrote:
> If we want to check for something we really should be checking to
> see if O_XATTR is defined, I still don't think that makes any more
> sense than checking if SOLARIS is defined though.
> 
> I will forget about HAVE_EAFD for now because it could be extended
> to cover platforms.  As far as I can tell Linux already has support
> for the needed functionality through the fgetxattr and fsetattr
> functions.

that's something different. attropen() or iirc openat() with O_XATTR
return a file descriptor that can be used with POSIX file IO. And
that's what is needed for OS X resource fork semantics.

Cheerio!
-slow
