### ISSUE TITLE
Persistent errors in variable substitution in manpages and docbook man/html pages

### ISSUE THREAD

**Issue by dgsga** [Netatalk/netatalk#441]

**Comment by rdmark** [comment]
For the record I was testing the latest code on FreeBSD and was getting this in generated man pages...

```
NETATALK(8)                   :NETATALK_VERSION:                   NETATALK(8)



NAME
       netatalk - Netatalk AFP server service controller daemon
```

**Comment by rdmark** [comment]
With the latest fixes from today, NETATALK_VERSION works again.

There's still one kink left on FreeBSD... seemingly falling back to `NONE` instead of nothing when no substitution happens?

```
FILES
       NONE/etc/afp.conf
           configuration file used by afpd

       NONE/var/netatalk/afp_signature.conf
           list of server signature

       NONE/var/netatalk/afp_voluuid.conf
           list of UUID for Time Machine volume

       NONE/etc/extmap.conf
           file name extension mapping

       NONE/etc/msg/message.pid
           contains messages to be sent to users.
```

**Comment by rdmark** [comment]
This is with `--sysconfdir=/usr/local` on FreeBSD:

```
FILES
       /usr/local/afp.conf
           configuration file used by afpd

       NONE/var/netatalk/afp_signature.conf
           list of server signature

       NONE/var/netatalk/afp_voluuid.conf
           list of UUID for Time Machine volume

       /usr/local/extmap.conf
           file name extension mapping

       /usr/local/msg/message.pid
           contains messages to be sent to users.
```

**Comment by rdmark** [comment]
Hmm I'm seeing the same `NONE` problem in Debian Bookworm too when not explicitly defining any prefixes.

**Comment by rdmark** [comment]
You know, this situation is kind of like a showcase why you want to move to the Meson build system. ;)

I butted my head against this for a few hours today. Cannot understand where the "NONE" comes from.

Reading up on stackoverflow this seems to be a long-standing limitation with autotools: it does not like to expand variables within variables in macros, hence that `sed` nonsense we see in Makefiles all over the place.

I'm starting to think that you very first proposal is the way to go... namely avoid double variable expansion with substitution. Just use the first layer of ${prefix} and hard-code the rest in the manual pages...

**Comment by rdmark** [comment]
This one is what I was thinking of: https://github.com/Netatalk/netatalk/commit/1d00aacfaeb04ef1db945fa8d2484fdd954c322c

**Comment by dgsga** [comment]
> With the latest fixes from today, NETATALK_VERSION works again.
> 
> There's still one kink left on FreeBSD... seemingly falling back to `NONE` instead of nothing when no substitution happens?
> 
> ```
> FILES
>        NONE/etc/afp.conf
>            configuration file used by afpd
> 
>        NONE/var/netatalk/afp_signature.conf
>            list of server signature
> 
>        NONE/var/netatalk/afp_voluuid.conf
>            list of UUID for Time Machine volume
> 
>        NONE/etc/extmap.conf
>            file name extension mapping
> 
>        NONE/etc/msg/message.pid
>            contains messages to be sent to users.
> ```

I think I know the fix for this, leave it with me...

**Comment by rdmark** [comment]
With the latest fix I'm seeing this in the generated Makefile in the source tree root:

```
[...]
localedir = ${datarootdir}/locale
localstatedir = NONE/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
pkgconfdir = NONE/etc
prefix = /usr/local
```

7 commits ago this is what that section looked like

```
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
```

**Comment by rdmark** [comment]
So the problem is clearly that these two standard directory variables aren't getting a default value: https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

If I configure with this the problems all go away: `./configure --sysconfdir=/etc --localstatedir=/var`
