### ISSUE TITLE
[PATCH] It should be possible to disable setting of RPATH

### ISSUE THREAD

**Issue by andy-js** [Netatalk/Netatalk#45]
When building on Solaris or NetBSD the -R flag is passed to the compiler.  I would rather not have the RPATH hardcoded into my binaries.  This patch adds a mechanism which can be used to turn this behaviour on and off and preserves the current defaults.

<pre>
diff --git a/configure.ac b/configure.ac
index 6d62810..a8532a2 100644
--- a/configure.ac
+++ b/configure.ac
@@ -94,6 +94,9 @@ AC_NETATALK_64BIT_LIBS
 dnl OS specific checks
 AC_NETATALK_OS_SPECIFIC
 
+dnl Whether to set rpath
+AC_NETATALK_SET_RPATH
+
 dnl Check for optional AFS support
 AC_NETATALK_AFS_CHECK
 
diff --git a/macros/db3-check.m4 b/macros/db3-check.m4
index 23ae72f..ac14d09 100644
--- a/macros/db3-check.m4
+++ b/macros/db3-check.m4
@@ -155,7 +155,7 @@ if test "x$bdb_required" = "xyes"; then
                         if test x"${atalk_cv_bdb_version}" = x"yes"; then
                             BDB_CFLAGS="-I${bdbdir}/include${subdir}"
                             BDB_LIBS="-L${bdblibdir} ${atalk_cv_lib_db}"
-                            if test x"$need_dash_r" = x"yes"; then
+                            if test x"$enable_rpath" = x"yes"; then
                                 BDB_LIBS="$BDB_LIBS -R${bdblibdir}"
                             fi
                             BDB_BIN="$bdbbindir"
@@ -181,7 +181,7 @@ if test "x$bdb_required" = "xyes"; then
                            if test x"${atalk_cv_bdb_version}" = x"yes"; then
                               BDB_CFLAGS="-I${bdbdir}/include${subdir}"
                               BDB_LIBS="-L${bdblibdir} ${atalk_cv_lib_db}"
-                              if test x"$need_dash_r" = x"yes"; then
+                              if test x"$enable_rpath" = x"yes"; then
                                  BDB_LIBS="$BDB_LIBS -R${bdblibdir}"
                               fi
                               BDB_BIN="$bdbbindir"
diff --git a/macros/netatalk.m4 b/macros/netatalk.m4
index d1e64cd..7ea4aa8 100644
--- a/macros/netatalk.m4
+++ b/macros/netatalk.m4
@@ -621,8 +621,6 @@ if test x"$this_os" = "xlinux"; then
 	dnl ----- on every single version of linux I've ever played with.
 	dnl ----- see etc/afpd/quota.c
 	AC_DEFINE(HAVE_BROKEN_DBTOB, 1, [Define if dbtob is broken])
-
-	need_dash_r=no
 fi
 
 dnl ----- NetBSD specific -----
@@ -633,7 +631,6 @@ if test x"$this_os" = "xnetbsd"; then
     AC_DEFINE(OPEN_NOFOLLOW_ERRNO, EFTYPE, errno returned by open with O_NOFOLLOW)
 
 	CFLAGS="-I\$(top_srcdir)/sys/netbsd $CFLAGS"
-	need_dash_r=yes 
 
 	dnl ----- NetBSD does not have crypt.h, uses unistd.h -----
 	AC_DEFINE(UAM_DHX, 1, [Define if the DHX UAM modules should be compiled])
@@ -656,7 +653,6 @@ if test x"$this_os" = "xsolaris"; then
 	AC_DEFINE(SOLARIS, 1, [Solaris compatibility macro])
     AC_DEFINE(_XOPEN_SOURCE, 600, [Solaris compilation environment])
     AC_DEFINE(__EXTENSIONS__,  1, [Solaris compilation environment])
-	need_dash_r=yes
 	init_style=solaris
 fi
 
@@ -666,6 +662,22 @@ echo NETA_LDCONFIG = $NETA_LDCONFIG
 AM_CONDITIONAL(RUN_LDCONFIG, test x"$this_os" = x"linux" -a x"$NETA_LDCONFIG" != x"")
 ])
 
+dnl Check whether to enable rpath (the default on Solaris and NetBSD)
+AC_DEFUN([AC_NETATALK_SET_RPATH], [
+	AS_CASE("$this_os", [solaris|netbsd],
+		[default_rpath=yes],
+		[default_rpath=no])
+	AC_ARG_ENABLE(rpath,
+		AS_HELP_STRING([--enable-rpath]
+			[enable RPATH/RUNPATH (default: $default_rpath)]),
+		AS_CASE("$enableval",
+			[yes], [enable_rpath=yes],
+			[no], [enable_rpath=no],
+			[AC_MSG_ERROR([bad value $enableval for --enable-rpath])]),
+		[enable_rpath=$default_rpath])
+	AC_MSG_RESULT([$enable_rpath])
+])
+
 dnl Check for building PGP UAM module
 AC_DEFUN([AC_NETATALK_PGP_UAM], [
 AC_MSG_CHECKING([whether the PGP UAM should be build])
diff --git a/macros/ssl-check.m4 b/macros/ssl-check.m4
index 8a58142..777bc4b 100644
--- a/macros/ssl-check.m4
+++ b/macros/ssl-check.m4
@@ -49,7 +49,7 @@ dnl	compile_ssl=no
 			if test -f "$ssldir/include/openssl/cast.h" ; then
 				SSL_CFLAGS="$SSL_CFLAGS -I$ssldir/include -I$ssldir/include/openssl"
 				SSL_LIBS="$SSL_LIBS -L$ssldir/$atalk_libname -L$ssldir -lcrypto"
-				if test "x$need_dash_r" = "xyes"; then
+				if test "x$enable_rpath" = "xyes"; then
 					SSL_LIBS="$SSL_LIBS -R$ssldir/$atalk_libname -R$ssldir"
 				fi
 				AC_MSG_RESULT([$ssldir (enabling RANDNUM and DHX support)])
</pre>

**Comment by slowfranklin** [comment]
On Tue, Feb 23, 2016 at 09:04:23AM -0800, Andrew Stormont wrote:
> When building on Solaris or NetBSD the -R flag is passed to the
> compiler.

Iirc as is rpath passed on Linux.

> I would rather not have the RPATH hardcoded into my
> binaries.

If the lib is not in an OS default library search path, we must add
the rpath.

Off the top of my head, I'd say this patch would eg break the OpenCSW
build.

Cheerio!
-slow

**Comment by andy-js** [comment]
As things stand now the need_dash_r variable is set to "no" on Linux and set to "yes" on Solaris and NetBSD.  Just applying the patch does not change the default behaviour (for any platform).

What the patch does do is let you override the defaults.  Some people might want to enable rpath, for the reasons you've suggested.  I want to disable it for different reasons.

The Debian guys have done a good job of explaining why the rpath can be a big problem if you don't need it: https://wiki.debian.org/RpathIssue

**Comment by slowfranklin** [comment]
Yeah, re-reading the code in question helps understanding the issue. :) So the change you're suggesting acutally looks like an improvement, but maybe it should be expanded to use a platform dependent variable instead of just using "-R" everywhere.

On Linux this could be RPATH_FLAGS="-Wl,--enable-new-dtags,-rpath," and on Solaris RPATH_FLAGS="-R ".

And then use it as BDB_LIBS="$BDB_LIBS -${RPATH_FLAGS}${bdblibdir}"

What do you think?

**Comment by andy-js** [comment]
The Solaris linker supports both -R and -rpath so there's no need to worry about that.  GCC will also map the -R flag to whatever the linker supports so it's probably a good choice if you care about portability.

The --enable-new-dtags flag seems to be a binutils thing.  Any platform using binutils (Linux and kFreeBSD come to mind) should support it.  Have a look over this updated patch.

<pre>
diff --git a/configure.ac b/configure.ac
index 6d62810..a8532a2 100644
--- a/configure.ac
+++ b/configure.ac
@@ -94,6 +94,9 @@ AC_NETATALK_64BIT_LIBS
 dnl OS specific checks
 AC_NETATALK_OS_SPECIFIC
 
+dnl Whether to set rpath
+AC_NETATALK_SET_RPATH
+
 dnl Check for optional AFS support
 AC_NETATALK_AFS_CHECK
 
diff --git a/macros/db3-check.m4 b/macros/db3-check.m4
index 23ae72f..4098e89 100644
--- a/macros/db3-check.m4
+++ b/macros/db3-check.m4
@@ -155,8 +155,11 @@ if test "x$bdb_required" = "xyes"; then
                         if test x"${atalk_cv_bdb_version}" = x"yes"; then
                             BDB_CFLAGS="-I${bdbdir}/include${subdir}"
                             BDB_LIBS="-L${bdblibdir} ${atalk_cv_lib_db}"
-                            if test x"$need_dash_r" = x"yes"; then
+                            if test x"$enable_rpath" = x"yes"; then
                                 BDB_LIBS="$BDB_LIBS -R${bdblibdir}"
+                                if test x"$enable_dtags" = x"yes"; then
+                                    BDB_LIBS="$BDB_LIBS -Wl,--enable-new-dtags"
+                                fi
                             fi
                             BDB_BIN="$bdbbindir"
                             BDB_PATH="$bdbdir"
@@ -181,8 +184,11 @@ if test "x$bdb_required" = "xyes"; then
                            if test x"${atalk_cv_bdb_version}" = x"yes"; then
                               BDB_CFLAGS="-I${bdbdir}/include${subdir}"
                               BDB_LIBS="-L${bdblibdir} ${atalk_cv_lib_db}"
-                              if test x"$need_dash_r" = x"yes"; then
+                              if test x"$enable_rpath" = x"yes"; then
                                  BDB_LIBS="$BDB_LIBS -R${bdblibdir}"
+                                 if test x"$enable_dtags" = x"yes"; then
+                                     BDB_LIBS="$BDB_LIBS -Wl,--enable-new-dtags"
+                                 fi
                               fi
                               BDB_BIN="$bdbbindir"
                               BDB_PATH="$bdbdir"
diff --git a/macros/netatalk.m4 b/macros/netatalk.m4
index e919762..23347c2 100644
--- a/macros/netatalk.m4
+++ b/macros/netatalk.m4
@@ -621,8 +621,6 @@ if test x"$this_os" = "xlinux"; then
 	dnl ----- on every single version of linux I've ever played with.
 	dnl ----- see etc/afpd/quota.c
 	AC_DEFINE(HAVE_BROKEN_DBTOB, 1, [Define if dbtob is broken])
-
-	need_dash_r=no
 fi
 
 dnl ----- NetBSD specific -----
@@ -633,7 +631,6 @@ if test x"$this_os" = "xnetbsd"; then
     AC_DEFINE(OPEN_NOFOLLOW_ERRNO, EFTYPE, errno returned by open with O_NOFOLLOW)
 
 	CFLAGS="-I\$(top_srcdir)/sys/netbsd $CFLAGS"
-	need_dash_r=yes 
 
 	dnl ----- NetBSD does not have crypt.h, uses unistd.h -----
 	AC_DEFINE(UAM_DHX, 1, [Define if the DHX UAM modules should be compiled])
@@ -656,7 +653,6 @@ if test x"$this_os" = "xsolaris"; then
 	AC_DEFINE(SOLARIS, 1, [Solaris compatibility macro])
     AC_DEFINE(_XOPEN_SOURCE, 600, [Solaris compilation environment])
     AC_DEFINE(__EXTENSIONS__,  1, [Solaris compilation environment])
-	need_dash_r=yes
 	init_style=solaris
 fi
 
@@ -666,6 +662,25 @@ echo NETA_LDCONFIG = $NETA_LDCONFIG
 AM_CONDITIONAL(RUN_LDCONFIG, test x"$this_os" = x"linux" -a x"$NETA_LDCONFIG" != x"")
 ])
 
+dnl Check whether to enable rpath (the default on Solaris and NetBSD)
+AC_DEFUN([AC_NETATALK_SET_RPATH], [
+	AS_CASE("$this_os", [solaris|netbsd],
+		[default_rpath=yes],
+		[default_rpath=no])
+	AS_CASE("$this_os", [linux|kfreebsd-gnu],
+		[enable_dtags=yes],
+		[enable_dtags=no])
+	AC_ARG_ENABLE(rpath,
+		AS_HELP_STRING([--enable-rpath]
+			[enable RPATH/RUNPATH (default: $default_rpath)]),
+		AS_CASE("$enableval",
+			[yes], [enable_rpath=yes],
+			[no], [enable_rpath=no],
+			[AC_MSG_ERROR([bad value $enableval for --enable-rpath])]),
+		[enable_rpath=$default_rpath])
+	AC_MSG_RESULT([$enable_rpath])
+])
+
 dnl Check for building PGP UAM module
 AC_DEFUN([AC_NETATALK_PGP_UAM], [
 AC_MSG_CHECKING([whether the PGP UAM should be build])
diff --git a/macros/ssl-check.m4 b/macros/ssl-check.m4
index 8a58142..79219df 100644
--- a/macros/ssl-check.m4
+++ b/macros/ssl-check.m4
@@ -49,8 +49,11 @@ dnl	compile_ssl=no
 			if test -f "$ssldir/include/openssl/cast.h" ; then
 				SSL_CFLAGS="$SSL_CFLAGS -I$ssldir/include -I$ssldir/include/openssl"
 				SSL_LIBS="$SSL_LIBS -L$ssldir/$atalk_libname -L$ssldir -lcrypto"
-				if test "x$need_dash_r" = "xyes"; then
+				if test "x$enable_rpath" = "xyes"; then
 					SSL_LIBS="$SSL_LIBS -R$ssldir/$atalk_libname -R$ssldir"
+					if test "x$enable_dtags" = "xyes"; then
+						SSL_LIBS="$SSL_LIBS -Wl,--enable-new-dtags"
+					fi
 				fi
 				AC_MSG_RESULT([$ssldir (enabling RANDNUM and DHX support)])
 				CFLAGS="$CFLAGS $SSL_CFLAGS"
</pre>
