### ISSUE TITLE
Overlap between AUTHORS and CONTRIBUTORS

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#454]
The AUTHORS and CONTRIBUTORS text files are practically identical, with the latter having just 14 (out of 100+) added lines.

Reading up on the common practice in OSS projects, I think AUTHORS is meant to credit the original creator(s) while CONTRIBUTORS is the living list of folks who have contributed over the years.

For simplicity I suggest we delete AUTHORS.

**Comment by rdmark** [comment]
(This is a really minor thing, but it's been triggering my OCD for years...)

**Comment by dgsga** [comment]
I agree

**Comment by rdmark** [comment]
https://github.com/Netatalk/netatalk/pull/538
https://github.com/Netatalk/netatalk/pull/537
