### ISSUE TITLE
Fix xml processing warnings generated by xsltproc

### ISSUE THREAD

**Issue by dgsga** [Netatalk/netatalk#462]
manpage xml files require author data to silence these warnings

**Comment by dgsga** [comment]
@rdmark, this is what the Samba manpage xml files contain:

`<refmiscinfo class="source">Samba</refmiscinfo>`
`<refmiscinfo class="manual">System Administration tools</refmiscinfo>`
`<refmiscinfo class="version">&doc.version;</refmiscinfo>`

This approach seems to be consistent across other open-source projects I have looked at. What do you think to adopting this approach, and removing the version suppression lines from man.xsl.in :

`<refmiscinfo class="source">Netatalk</refmiscinfo>`
`<refmiscinfo class="manual">Netatalk AFP Fileserver manual</refmiscinfo>`
`<refmiscinfo class="version">@NETATALK_VERSION@</refmiscinfo>`

**Comment by rdmark** [comment]
Seems good to me.

BTW my recommendation for the AUTHOR section was something like this in my mind. Avoid repeating the URL twice. Most readers should present this as a hyperlink, right?

```
  <refsect1>
    <title>AUTHOR</title>

    <para>See <ulink url='https://github.com/Netatalk/netatalk/blob/main/AUTHORS'>AUTHORS</ulink></para>
  </refsect1>
```

**Comment by dgsga** [comment]
URL pointing to contributors or authors?

**Comment by rdmark** [comment]
Right, like that but with CONTRIBUTORS
