### ISSUE TITLE
[PATCH] support for tracker 1.8.0

### ISSUE THREAD

**Issue by andy-js** [Netatalk/Netatalk#49]
The tracker-control command has been deprecated for a while now and with 1.8.0 it has finally been removed.  The "tracker" command offers the same functionality and has done since version 1.3.5.

<pre>
diff --git a/etc/netatalk/netatalk.c b/etc/netatalk/netatalk.c
index 204bd1e..c9bb90e 100644
--- a/etc/netatalk/netatalk.c
+++ b/etc/netatalk/netatalk.c
@@ -176,7 +176,7 @@ static void sigterm_cb(evutil_socket_t fd, short what, void *arg)
     event_del(timer_ev);
 
 #ifdef HAVE_TRACKER
-    system("tracker-control -t");
+    system(TRACKER_PREFIX "/bin/tracker daemon -t");
 #endif
     kill_childs(SIGTERM, &afpd_pid, &cnid_metad_pid, &dbus_pid, NULL);
 }
@@ -186,7 +186,7 @@ static void sigquit_cb(evutil_socket_t fd, short what, void *arg)
 {
     LOG(log_note, logtype_afpd, "Exiting on SIGQUIT");
 #ifdef HAVE_TRACKER
-    system("tracker-control -t");
+    system(TRACKER_PREFIX "/bin/tracker daemon -t");
 #endif
     kill_childs(SIGQUIT, &afpd_pid, &cnid_metad_pid, &dbus_pid, NULL);
 }
@@ -445,7 +445,7 @@ int main(int argc, char **argv)
 
         if (atalk_iniparser_getboolean(obj.iniconfig, INISEC_GLOBAL, "start tracker", 1)) {
             LOG(log_note, logtype_default, "Starting Tracker");
-            system(TRACKER_PREFIX "/bin/tracker-control -s");
+            system(TRACKER_PREFIX "/bin/tracker daemon -s");
         }
     }
 #endif
</pre>

**Comment by hat001** [comment]
duplicated
https://github.com/Netatalk/Netatalk/pull/47/commits/946c5fe986ecdb31258a5f507fad5a2957d7361f

**Comment by andy-js** [comment]
I think you have some baggage in your changes to macros/netatalk.m4.

**Comment by hat001** [comment]
please patch

**Comment by andy-js** [comment]
Notice how the x"$ac_cv_tracker_manage" = x"tracker-control" case is handled twice.

<pre>
 +    dnl Tracker Managing Command
 +    AC_CHECK_PROGS(ac_cv_tracker_manage, tracker tracker-control, , ["$ac_cv_tracker_prefix"/bin])
 +    if test x"$ac_cv_tracker_manage" = x"tracker" ; then
 +       TRACKER_MANAGING_COMMAND="tracker daemon"
 +       AC_DEFINE(TRACKER_MANAGING_COMMAND, "tracker daemon", [tracker managing command])
 +    elif test x"$ac_cv_tracker_manage" = x"tracker-control" ; then
 +       TRACKER_MANAGING_COMMAND="tracker-control"
 +       AC_DEFINE(TRACKER_MANAGING_COMMAND, "tracker-control", [tracker managing command])
 +    elif test x"$ac_cv_tracker_manage" = x"tracker-control" ; then
 +       TRACKER_MANAGING_COMMAND="tracker-control"
 +    else
 +       AC_MSG_ERROR([could find neither tracker command nor tracker-control command])
 +    fi
 +
</pre>

**Comment by hat001** [comment]
pull request:
https://github.com/Netatalk/Netatalk/pull/52/commits/1726a9ac8174f5120e01db06693fa796fe6b23c8
