### ISSUE TITLE
configure fails on checking libiconv

### ISSUE THREAD

**Issue by masahito-yamaga** [Netatalk/netatalk#491]
I think the following patch is needed. After patching, execute autoreconf.

```
--- ./macros/iconv.m4.ORG	2023-09-11 02:55:05.000000000 +0900
+++ ./macros/iconv.m4	2023-09-17 07:59:29.209441797 +0900
@@ -40,14 +40,15 @@
   esac

 	AC_CACHE_CHECK([for libiconv],netatalk_cv_iconv,[
-          AC_LINK_IFELSE([AC_LANG_SOURCE([[
+          AC_LINK_IFELSE([AC_LANG_SOURCE([
 #include <stdlib.h>
 #include <iconv.h>
-],[
+int main(void) {
 	iconv_t cd = iconv_open("","");
         iconv(cd,NULL,NULL,NULL,NULL);
         iconv_close(cd);
-]])], netatalk_cv_iconv=yes, netatalk_cv_iconv=no, netatalk_cv_iconv=cross)])
+}
+])], netatalk_cv_iconv=yes, netatalk_cv_iconv=no, netatalk_cv_iconv=cross)])

 	if test x"$netatalk_cv_iconv" = x"yes"; then
 	    ICONV_LIBS="$ICONV_LIBS -liconv"
```

**Comment by rdmark** [comment]
@masahito-yamaga Thank you for reporting!

May I ask which OS that you are using?

I tested on Debian 12, FreeBSD and OpenIndiana, but I couldn't observe a difference in behavior after applying your patch.

```
checking for libiconv... no
checking for working iconv... yes
checking whether iconv supports UCS-2-INTERNAL... no
```

I'm sure there's something obvious I'm missing here

**Comment by masahito-yamaga** [comment]
Very old Linux Box.

Kernel 2.6.22.7 + uClibc + gcc 8.5.0

**Comment by masahito-yamaga** [comment]
configure fails like:<pre>checking for libiconv... no
configure: error: libiconv not found</pre>In config.log,<pre>configure:16686: checking for libiconv
configure:16704: gcc -o conftest -I/opt/local/include -D_U_=&quot;__attribute__((unused))&quot; -g -O2 -I/opt/local/include -L/opt/local/lib -Wl,-rpath -Wl,
/opt/local/lib:/opt/lib -L/opt/local/lib -liconv conftest.c  >&5
conftest.c:78:1: error: expected identifier or '(' before ',' token
 ,
 ^
conftest.c:80:18: error: expected ')' before '(' token
         iconv(cd,NULL,NULL,NULL,NULL);
                  ^
                  )
conftest.c:81:9: warning: parameter names (without types) in function declaration
         iconv_close(cd);
         ^~~~~~~~~~~
configure:16704: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "netatalk"
(snip)
| #define NDEBUG 1
| /* end confdefs.h.  */
|
| #include &lt;stdlib.h&gt;
| #include &lt;iconv.h&gt;
| ,
|       iconv_t cd = iconv_open(&quot;&quot;,&quot;&quot;);
|         iconv(cd,NULL,NULL,NULL,NULL);
|         iconv_close(cd);
|
configure:16713: result: no
configure:16724: error: libiconv not found</pre>

**Comment by rdmark** [comment]
That explains it. This must mean your version of Linux doesn't have native iconv in glibc but relies on libiconv

**Comment by masahito-yamaga** [comment]
No.
Would you please look at my post carefully?
My patch works correctly.

**Comment by masahito-yamaga** [comment]
The original configure creates the following temporary program.
```
#include <stdlib.h>
#include <iconv.h>
,
      iconv_t cd = iconv_open("","");
        iconv(cd,NULL,NULL,NULL,NULL);
        iconv_close(cd);
```
The above cannot be compiled.
But after applying my patch, configure creates the following one.
```
#include <stdlib.h>
#include <iconv.h>
int main(void) {
      iconv_t cd = iconv_open("","");
        iconv(cd,NULL,NULL,NULL,NULL);
        iconv_close(cd);
}
```
The above can be compiled.

**Comment by rdmark** [comment]
I get it now, thanks. I can see how the syntax is wrong in the current program.

Would you be able to create a Pull Request here in github, so that a project member can approve and merge the change?

**Comment by masahito-yamaga** [comment]
All right. Thank you.
But I am not familiar with Pull Requests, so would you please do it for me?

**Comment by rdmark** [comment]
We are happy to help. Please bear in mind that it takes a little longer time, since one project member has to create the PR, and another one approve the merge, as per the project policy.

If you ever feel like getting to know the code contribution workflow in GitHub, we have a manual written here: https://github.com/Netatalk/netatalk/wiki/Developer-Notes#user-content-Code_Contribution_Process

**Comment by rdmark** [comment]
Out of curiosity I checked what iconv test program is generated with the netatalk 2.2 branch:

```
#include <stdlib.h>
#include <iconv.h>

int
main ()
{

      iconv_t cd = iconv_open("","");
        iconv(cd,NULL,NULL,NULL,NULL);
        iconv_close(cd);

  ;
  return 0;
}
```

A little messy syntax, but the program does compile, with a warning.
