### ISSUE TITLE
[2.2] atalkd won't load on Fedora 38 without manually doing 'modprobe appletalk' first

### ISSUE THREAD

**Issue by rb6502** [Netatalk/netatalk#506]
I compiled and installed 2.2.10 on my Fedora 38 server (x64, currently kernel 6.5.5) and it works great, but when I reboot the system for updates or whatever atalkd and its dependents (timelord and a2bootd) don't load.  If I log in and manually do a 'modprobe appletalk' and then 'systemctl start atalkd' it loads fine.

**Comment by rdmark** [comment]
Thanks for making the ticket!

One additional detail from the original 68kmla thread: the appletalk kernel module isn't included with the system by default (unlike Debian, Ubuntu) but is installed with the `kernel-modules-extra` package.

**Comment by rdmark** [comment]
One solution would be to add this to the systemd unit defintion:
```
ExecStartPre=/usr/sbin/modprobe appletalk
```

The tricky part would be to make the path to modprobe portable. What's the best practice here?

**Comment by NJRoadfan** [comment]
Fedora (and systemd in general) has facilities to persistently load a kernel module on boot. See: https://docs.fedoraproject.org/en-US/fedora/latest/system-administrators-guide/kernel-module-driver-configuration/Working_with_Kernel_Modules/#sec-Persistent_Module_Loading

**Comment by rb6502** [comment]
@rdmark I thought modprobe was always in /usr/sbin - is there a known distro where that isn't true?

@NJRoadfan That sounds perfect, but I tried it and it didn't work.  Created /etc/modules-load.d/appletalk.conf with a command and "appletalk" and rebooted, still no go.  dmesg doesn't show AppleTalk loading until I do it manually and atalkd fails to start.  The man pages claim it's actually that simple, but there are no errors and apparently no way to debug it.

**Comment by NJRoadfan** [comment]
Found the issue, the appletalk module is blacklisted out of the box in Fedora, see (partway down, search for blacklist in the page): https://connor.zip/posts/2023-08-04-localtalk-ethernet

In addition to adding the file under /etc/modules-load.d/ you need to edit the file /etc/modprobe.d/appletalk-blacklist.conf, comment out the line 'blacklist appletalk'.

**Comment by rb6502** [comment]
That did it!  I commented out the blacklist, rebooted, and appletalk loaded and atalkd came up correctly.

**Comment by rdmark** [comment]
> I thought modprobe was always in /usr/sbin - is there a known distro where that isn't true?

Heh, I was just winging it late at night.

> That did it! I commented out the blacklist, rebooted, and appletalk loaded and atalkd came up correctly.

Excellent! I think this is the better solution over forcing the module loading via a modprobe command. How about we document this in the wiki for future Fedora users?

@rb6502 Would you be up for starting an "Install Netatalk" page? https://github.com/Netatalk/netatalk/wiki

**Comment by rb6502** [comment]
I could do something with that.  I haven't dealt with a Github wiki before, is there some kind of pull request mechanism with it or something?

**Comment by rdmark** [comment]
@rb6502 No PR shenanigans required. You edit the wiki just like, say, wikipedia. The one choice you have to make is whether to use markdown or mediawiki syntax for your page.

**Comment by NJRoadfan** [comment]
I did a test install of Fedora 38 Server. All one has to do to get AppleTalk working "out of the box" is deleting /etc/modprobe.d/appletalk-blacklist.conf. After that, compile and install netatalk, run modprobe appletalk, and then setup the systemd services and away you go.

**Comment by rb6502** [comment]
So with the blacklist removed, you don't need an /etc/modules-load.d file?  That's great.

**Comment by NJRoadfan** [comment]
Correct. It was the blacklist that was preventing the module from loading on boot.

**Comment by rdmark** [comment]
Does anyone here have connections inside the Fedora project? Let's get the blacklisting reversed. ;)

**Comment by NJRoadfan** [comment]
The folks at Fedora have very good security reasons for blacklisting rarely used (and infrequently maintained) kernel modules.

**Comment by rb6502** [comment]
Yeah, I'll write up a page still, but I do think it's OK to close this now as well.
