### ISSUE TITLE
Configure and install the Webmin module

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#518]
If Webmin is installed on the target system, it would be nice to have the option in the build system to add the netatalk module and configure it with the correct binary and conf file paths.

To achieve this, I want to bundle the Webmin module with Netatalk proper. This also makes it easier to keep the module up to date.

The proposal:
- Put all of the code in https://github.com/Netatalk/netatalk-webmin under `contrib/webmin`
- Add a `-Dwith-webmin-module` Meson option
- Check for the existence of webmin (e.g. /usr/share/webmin on Debian or /usr/libexec/webmin on Fedora)
- Substitute init commands, pkgconfdir and binary dir paths in `contrib/webmin/config`
- Generate the Webmin module tarball on the fly
- Run the Webmin install script, e.g. `@${WEBMIN_DIR}/install-module.pl netatalk*-wbm.tgz`
- It modify the netatalk webmin module's `config` file to have it point to the correct file system paths for all config files

**Comment by dgsga** [comment]
What is Webmin?

**Comment by rdmark** [comment]
It's a webapp framework for system administration. We have a webmin module for netatalk: https://github.com/Netatalk/netatalk-webmin

**Comment by rdmark** [comment]
Abandoning this. Adds to much complexity to the makefile for little benefit.
