### ISSUE TITLE
become_user_permanently(uid_t uid, gid_t gid) return value

### ISSUE THREAD

**Issue by pgajdos** [Netatalk/netatalk#523]
... should be zero at the very end of the function. Right?

**Comment by rdmark** [comment]
You mean here? https://github.com/Netatalk/netatalk/blob/9aad2d890aa9e5cabbc8b1012ebcfa19efa5b227/etc/afpd/afprun.c#L112

Yes I agree that a `return 0` is better at the end there. Would you like to submit a PR with the change?

As a history lesson, I believe that in the initial ANSI C standard, implicit functions, return values etc. were acceptable, so you see this sometimes in really old school codebases. But this was changed in C99. Netatalk was written in the early 90s so it makes sense you see an older style here and there were refactoring hasn't been done yet.

**Comment by pgajdos** [comment]
Yes, I vaguely remember that. Fortunately, when compiling 3.1.18, I get no other no-return-in-nonvoid.

Do you need the PR?

**Comment by rdmark** [comment]
I’d love a PR!
