### ISSUE TITLE
Residual code for discontinued OSes

### ISSUE THREAD

**Issue by dgsga** [Netatalk/netatalk#543]
kfreebsd:  The development of Debian GNU/kFreeBSD has officially terminated as of July 2023 due to the lack of interest and volunteers... https://lists.debian.org/debian-devel/2023/07/msg00176.html

irix:  Final release | 6.5.30 / 16 August 2006; 17 years ago...

Let's remove the remaining code associated with these operating systems in the netatalk.m4 macro and elsewhere

**Comment by rdmark** [comment]
compat.h has some code for Ultrix and IBMR2 that should get cleaned up: https://github.com/Netatalk/netatalk/blob/main/include/atalk/compat.h

**Comment by rdmark** [comment]
There are remnants of TRU64 compatibility macros, e.g. uams_dhx_passwd.c, uams_passwd.c, auth.c

**Comment by rdmark** [comment]
@dgsga I took the liberty of reviving and pushing additional code cleanup to your branch. This is low hanging fruit that's good to wrap up before it gets too stale.
