### ISSUE TITLE
[PATCH] Spotlight searches can cause afpd to segfault

### ISSUE THREAD

**Issue by andy-js** [Netatalk/netatalk#56]
Seems like a NULL pointer is being passed to strcmp.

<pre>
diff --git a/etc/spotlight/sparql_parser.y b/etc/spotlight/sparql_parser.y
index 9d60997..7128a01 100644
--- a/etc/spotlight/sparql_parser.y
+++ b/etc/spotlight/sparql_parser.y
@@ -119,6 +119,8 @@ BOOL {
         yyerror("Spotlight queries with logic expressions are disabled");
         YYABORT;
     }
+    if ($1 == NULL || $3 == NULL)
+        YYABORT;
     if (strcmp($1, $3) != 0)
         $$ = talloc_asprintf(ssp_slq, "{ %s } UNION { %s }", $1, $3);
     else
</pre>

**Comment by rdmark** [comment]
@andy-js Is there a reason this patch wasn't submitted as a PR? Still a work in progress?

**Comment by rdmark** [comment]
Merged to main
