### ISSUE TITLE
Clicking on "Sparsebundle" shows backups over 20 days but Time Machine only shows today and yesterday

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [Netatalk/netatalk#581]
First thanks for Netatalk !

If I double click on the Sparsebundle file on my server as shown in MacOS Finder then multiple backups are shown from today, 14 of Dec 2023, going back to 24th of Nov. However if I open Time Machine then the backups shown are only for today and yesterday.
<img width="1440" alt="Time Machine" src="https://github.com/Netatalk/netatalk/assets/951566/fc402632-b1fd-49da-b90e-71be2b802d83">
<img width="1150" alt="Time Machine Backups in Finder" src="https://github.com/Netatalk/netatalk/assets/951566/75d1cdcf-44b0-4e2f-8905-e86081280485">

**Comment by rdmark** [comment]
That does not seem right. Can you please provide a few more details:

- Did it work previously? And if so, did you do something (software update etc) that triggered the problem?
- version of macOS?
- version of netatalk
- netatalk host system is running what OS?
- how did you install and configure netatalk?

**Comment by Michael-Z-Freeman** [comment]
> That does not seem right. Can you please provide a few more details:
> 
> * Did it work previously? And if so, did you do something (software update etc) that triggered the problem?
> * version of macOS?

Sonama 14.2

> * version of netatalk
> * netatalk host system is running what OS?

Ubuntu

> * how did you install and configure netatalk?

OK, thanks. Now nothing works apart from standard file sharing. I'm going to try a reinstallation and will get back to you.

**Comment by rdmark** [comment]
It would be helpful to see the contents of your `afp.conf` configuration file, as well.

**Comment by Michael-Z-Freeman** [comment]
> It would be helpful to see the contents of your `afp.conf` configuration file, as well.

Also I forgot. In the docs it says "_It's recommended to enable extended attributes of filesystem. You can check it by "getfattr" and "setfattr" commands_". As far as I understand it this is already turned on in modern file systems such as ext4 ?

**Comment by rdmark** [comment]
I doubt extended attributes make a difference for Time Machine volumes. 

But yes I would expect ext4 file systems to have EA enabled by default. You can always test their presence with the aforementioned tools.

**Comment by rdmark** [comment]
@Michael-Z-Freeman any update on how it’s looking after starting fresh?

**Comment by rdmark** [comment]
Closing for now. Please reopen if the same issue reappears.

**Comment by Michael-Z-Freeman** [comment]
Though I’d clarify this issue. See attachment. Clicking on the right hand controls (yellow arrow) often only goes back a day. However selecting previous backups by using the windows (purple arrow) successfully goes back to all previous backups. Having only recently started using Time Machine this maybe expected behaviour.
![screenshot](https://github.com/Netatalk/netatalk/assets/951566/839ab0d3-951f-4d3f-8b16-3139b9517fef)
