### ISSUE TITLE
Deprecate the use of old versions of tracker when compiling Spotlight support in Netatalk3

### ISSUE THREAD

**Issue by dgsga** [Netatalk/netatalk#595]
In line with having the codebase using up-to-date versions of libtalloc, libevent etc., should we consider deprecating support for tracker v1 and v2? Thoughts welcome...

**Comment by rdmark** [comment]
I think this is the right thing to do. Tracker v3.0.0 stable was released on 2020-09-13. 3 years might be enough to consider it firmly established.

I found this resource: https://repology.org/project/gnome-tracker/versions

What stands out is OpenIndiana that still only distributes v1. I don't think I ever got Spotlight working on OpenIndiana, but it's worth another shot.

Let's give the community a heads-up on the mailing lists and solicit feedback (objections.) Do you want to send the email or should I?

**Comment by dgsga** [comment]
I'd be happy to if I knew how! Can you send me a quick how-to?

**Comment by rdmark** [comment]
The website has an overview of the mailing lists and links to the sign-up page: https://netatalk.sourceforge.io/support.php

You may need a SourceForge account to do so.

The "netatalk-admins" is the main one that most people are subscribed to. Once you've joined the mailing list, you can send emails to netatalk-admins@lists.sourceforge.net

**Comment by dgsga** [comment]
See update in previous post
