### ISSUE TITLE
Netatalk logs with microsecond time stamps when using "log file" option under RockyLinux9.3

### ISSUE THREAD

**Issue by hnagasawa** [Netatalk/netatalk#602]
I compiled successfully under RockyLinux9.3.
/usr/local/sbin/afpd -V

afpd 3.1.99dev - Apple Filing Protocol (AFP) daemon of Netatalk

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version. Please see the file COPYING for further information and details.

afpd has been compiled with support for these features:

      AFP versions: 2.2 3.0 3.1 3.2 3.3 3.4
     CNID backends: dbd last
  Zeroconf support: Avahi

TCP wrappers support: No
Admin group support: Yes
Valid shell checks: Yes
cracklib support: Yes
EA support: ad | sys
ACL support: Yes
LDAP support: Yes
D-Bus support: Yes
Spotlight support: No
DTrace probes: Yes

          afp.conf: /usr/local/etc/afp.conf
       extmap.conf: /usr/local/etc/extmap.conf
   state directory: /usr/local/var/netatalk/
afp_signature.conf: /usr/local/var/netatalk/afp_signature.conf
  afp_voluuid.conf: /usr/local/var/netatalk/afp_voluuid.conf
   UAM search path: /usr/local/lib/netatalk/

Server messages path: /usr/local/var/netatalk/msg/

But same issue occured.

afp.conf

[Global]
; Global server settings
mac charset = MAC_JAPANESE
;uam list = uams_clrtxt.so uams_dhx.so uams_dhx2.so uams_guest.so
afpstats = yes
log level = default:info
log file = /var/log/netatalk/netatalk.log

log file = /var/log/syslog
log seconds = yes
vol dbpath = /var/netatalk/CNID
vol preset = my_default_values

Dec 19 16:16:53.101138 afpd[983] {status.c:631} (info:AFPDaemon): signature is B058973E0349085A35570476CB8A843F
Dec 19 16:16:53.110724 afpd[983] {auth.c:111} (info:AFPDaemon): uam: "DHX2" available
Dec 19 16:16:53.110770 afpd[983] {auth.c:111} (info:AFPDaemon): uam: "DHCAST128" available
Dec 19 16:16:53.110779 afpd[983] {status.c:359} (info:AFPDaemon): servername: RockyLinux
Dec 19 16:16:53.110814 afpd[983] {afp_config.c:196} (note:AFPDaemon): Netatalk AFP/TCP listening on 192.168.1.245:548
Dec 19 16:16:53.110830 afpd[983] {ldap_config.c:103} (info:AFPDaemon): LDAP: not used
Dec 19 16:16:53.110845 afpd[983] {cnid.c:55} (info:AFPDaemon): Registering CNID module [last]
Dec 19 16:16:53.110849 afpd[983] {cnid.c:55} (info:AFPDaemon): Registering CNID module [dbd]
Dec 19 16:16:53.361034 netatalk[981] {afp_avahi.c:94} (info:AFPDaemon): hostname: RockyLinux
Dec 19 16:16:53.361316 netatalk[981] {afp_avahi.c:118} (info:AFPDaemon): Registering server 'RockyLinux' with Bonjour

**Comment by rdmark** [comment]
@hnagasawa Please use this option:

`log microseconds = no`

**Comment by hnagasawa** [comment]
@rdmark 
I apologize delay.
>Please use this option in your afp.conf (global section):
>log microseconds = no

**Comment by rdmark** [comment]
Thanks for reporting back on your testing. I’m glad that it works for you now.
