### ISSUE TITLE
CI runners with additional OSes

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#605]
To look into adding CI runners for:

- FreeBSD
- NetBSD
- Solaris-likes (e g OpenIndiana)
- Fedora Linux

The above list is based on common OSes that netatalk users are using (bug reports, mailing list threads, forum threads)

We occasionally run into configuration or compilation / linking issues on these OSes, often found late because we don’t have continuous testing set up.

**Comment by rdmark** [comment]
One example from the libressl project — https://github.com/libressl/portable/blob/master/.github/workflows/solaris.yml

they use a Solaris VM inside of the Ubuntu runner.

**Comment by dgsga** [comment]
Great idea. While we're at it why don't we simplify (and speed up) the existing jobs by just running make check or make distcheck as both these do make automatically. We don't need to do make twice (just like the libressl example you posted).

Just found this page, perfect for what we need - https://github.com/vmactions.

I'll take this on , I like a challenge!

**Comment by rdmark** [comment]
> While we're at it why don't we simplify (and speed up) the existing jobs by just running make check or make distcheck as both these do make automatically

The reason I configured the jobs like this, is for ease of troubleshooting when something does go wrong. But if you think the increased efficiency is worth it then please go ahead.

Have fun!

**Comment by dgsga** [comment]
@rdmark, I have been looking into using vmactions in the workflow and have already encountered one major issue. The Solaris vmaction takes 5min to initialise alone, so if you have multiple vmactions (for different OSes) then we're looking at a workflow that could potentially take  > 25min to complete. Before I look into this any further do you think this is the right way to go? I'm not so sure...

**Comment by rdmark** [comment]
@dgsga These vmactions workflows can't be run as parallel CI jobs on github? I agree that 25min for a complete CI run sounds excessive. But at ~10min I would say it is worth it.

So what are our options...?

Dockerfiles for automation of a local lab
Other more optimized CI runners (GitLab hosting?)
Anything else?

**Comment by rdmark** [comment]
@dgsga do you think it’s redundant to have a workflow for Fedora? We’ve had some minor defects with the specific toolchain versions on that distribution in the past…
