### ISSUE TITLE
afpd: In-memory fallback to tdb backend when bdb fails

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#610]
etc/afpd/file.c has fallback logic for using a temporary in-memory tdb CNID backend when access to the BDB database fails.

https://github.com/Netatalk/netatalk/blob/4135650f47b0a4e5b61fb771a5332ba743882e34/etc/afpd/file.c#L209

IINM this code is no longer functional since the tdb backend was deprecated.

**Comment by rdmark** [comment]
This fallback code was added in mid 2010: https://github.com/Netatalk/netatalk/commit/a18f3a03913b1382aaecef9ae1317b57f40c0b6c

**Comment by rdmark** [comment]
volume.c also has a similar in-memory tdb fallback:

https://github.com/Netatalk/netatalk/blob/4135650f47b0a4e5b61fb771a5332ba743882e34/etc/afpd/volume.c#L642

**Comment by rdmark** [comment]
@dgsga Kind of a last minute thought, but since it turns out tdb is used internally by netatalk as a fallback mechanism, one option for us would be to keep (bring back) tdb, but not exposing it to users as a configurable CNID backend.

This would still be in line with the goal of reducing configuration complexity to users, while keeping a feature that may be potentially saving users' data.

Of course I want to test that the fallback actually works before making a final decision. :)

**Comment by slowfranklin** [comment]
On 12/23/23 08:31, Daniel Markstedt wrote:
> Of course I want to test that the fallback actually works before making 
> a final decision. :)
I don't quite remember why I added this, but looking back I think this 
was a mistake and should just be removed.

-slow

**Comment by rdmark** [comment]
@slowfranklin I trust your gut feel here. This removes the two obvious instances of backend fallbacks, plus touching up of documentation. https://github.com/Netatalk/netatalk/pull/612

**Comment by rdmark** [comment]
Funnily enough, I stumbled upon a test case by chance.

If you run afpd in debug mode (afpd -d) and attempt to connect from a Classic Mac OS client, you trigger this error state. And it works as advertised. You get a read-only share volume to "rescue" files off of if you like.

<img width="638" alt="Screenshot 2023-12-24 at 19 46 13" src="https://github.com/Netatalk/netatalk/assets/2108467/352242d5-b9b6-448a-87cd-db8d27bf1cf8">

**Comment by rdmark** [comment]
This is the commit that added the other tdb fallback in 2009 https://github.com/Netatalk/netatalk/commit/8bd8ce41c319619c64721f6e4d1f80df8ab79813

**Comment by rdmark** [comment]
My proposed solution: When the cnid_dbd backend encounters a fatal connection error in transmit(), we bail out with abort(). Seems to work as intended in my testing. Any reason this is a bad idea?

<img width="638" alt="Screenshot 2023-12-25 at 9 17 34" src="https://github.com/Netatalk/netatalk/assets/2108467/231ecc50-2a05-4417-837b-6102780da2c0">

**Comment by slowfranklin** [comment]
On 12/25/23 01:19, Daniel Markstedt wrote:
> My proposed solution: When the cnid_dbd backend encounters a fatal 
> connection error in transmit(), we bail out with abort(). Seems to work 
> as intended in my testing. Any reason this is a bad idea?

you mean abort as in abort()? There's no need to for that, we could just 
return an AFP error to the client and then just exit() with an error.

-slow

**Comment by rdmark** [comment]
@slowfranklin Yes, I meant `abort()`. It's used elsewhere (8 times) in cnid_dbd.c so I thought it a safe exit! :)

So transmit() returns -1 for an unsuccessful DB connection. When returning to the various `cnid_dbd_xxx` functions, the error state is handled like this:

```
    if (transmit(db, &rqst, &rply) < 0) {
        errno = CNID_ERR_DB;
        return CNID_INVALID;
    }
```

CNID_INVALID is defined as 0.

In some `cnid_dbd_xxx` functions -1 or NULL is returned instead. I don't yet understand why the different behavior.

Next to figure out exactly where the client receives the return value.

**Comment by rdmark** [comment]
Never mind, I was overthinking it. Calling exit() in the client at the same spots where previously the backend fallback was happening should do the trick, I think. Ex. https://github.com/Netatalk/netatalk/pull/612/commits/78fb9a3d37c3df19a8c775a2b7592207642250bb

**Comment by rdmark** [comment]
@slowfranklin I think I've arrived at a good solution now. What I found by looking at return values from the cnid module, was that we were getting the CNID_ERR_DB error code when the dbd backend could not be reached, which wasn't handled on the client side. So I made the client exit when encountering this specific error in get_id().
