### ISSUE TITLE
Make Fails on Solaris 10

### ISSUE THREAD

**Issue by Michael-Wohlstadter** [Netatalk/netatalk#617]
I am attempting to build Netatalk 3.1.18 on Solaris 10 (1/13) and it fails attempting to include sys/attr.h (see Make_error.log).

I installed autoconf, grip, libgcrypt, bdb-4.8, binutils, gcc5, and libevent-2.1.7 from OpenCSW.  My configure statement is:

```
env PKG_CONFIG_PATH=/opt/csw/lib/pkgconfig ./configure \
	--with-init-style=solaris \
	--with-libgcrypt-dir=/opt/csw \
	--with-pam-confdir=/etc/pam.d \
	--with-bdb=/opt/csw/bdb48 \
	--with-mysql-config=no
```

Configure runs without error (just a few warnings about pam).  Running make generates the error.

This might be a naive question (I'm not a C programmer), but doesn't the line "#include <sys/attr.h>" in the file "include/atalk/ea.h" reference the file "/usr/include/sys/attr.h"?  That file does not exist in my install of Solaris.  I just created a new Solaris virtual machine with the complete install and it isn't on that virtual machine either.

What installs that include file?  Or am I misunderstanding how C searches for includes?  If it is the latter, what do I need to pass to configure?

Thanks,
Michael
[Make_error.log](https://github.com/Netatalk/netatalk/files/13759921/Make_error.log)

**Comment by rdmark** [comment]
@Michael-Wohlstadter Thanks for reporting! So this means either that some required header is missing, or that we're looking for it in the wrong place.

Do you have an "attr.h" header file anywhere on the file system?

[Oracle documentation](https://docs.oracle.com/cd/E86824_01/html/E54766/fgetattr-3c.html) suggests that the correct import statement should be `#include <attr.h>`. Can you try editing ea.h, change that line and try compiling again?

I don't currently have a Solaris VM set up (tried last year but failed) but I tested this on OpenIndiana. FWIW both import styles work on that OS.

**Comment by rdmark** [comment]
While talking about Solaris: Do you have advice on how to get started with Solaris in VirtualBox?

Installing the OS from the [latest Solaris 10 DVD image from Oracle](https://www.oracle.com/solaris/solaris10/downloads/solaris10-get-jsp-downloads.html) works fine, but the automatic configuration of the network interface always fails, I have tried and failed to configure it manually after installing.

I must have tried all possible combinations of network type and emulated network device, but the automatic network configuration step always fails (attempting to configure interface xxx -> skipped interface xxx).

My host OS is Windows 11. Every other virtualized OS work fine (a myriad of Linuxi, NetBSD, FreeBSD, OmniOS, OpenIndiana, etc.)

**Comment by dgsga** [comment]
@rdmark, try installing Solaris 11 on VMWare Fusion using the text DVD from the Oracle website. Run pkg update immediately after install then pkg install solaris-desktop to get the gui. Then pkg install libtool automake autocomf pkgconfig  gcc (from memory) then you’re good to go. If you have a spare PC I can recommend setting up a homelab for Netatalk testing. i.e installing a bare metal hypervisor such as Proxmox or VMware ESXi and then installing VM’s for all the different OSes we need to cater for.

**Comment by Michael-Wohlstadter** [comment]
@rdmark - I was unable to find attr.h anywhere in the file system.  Note, the documentation you referenced is for version 11 and I am using 10.  In the Solaris 10 documentation I didn't see attr.h listed.  Perhaps extended attributes not supported on Solaris 10?

My goal is to setup Netatalk on a physical Sun E250 which Solaris 11 does not support.  I created the virtual machine as a quick test to see what was in a clean and complete install of Solaris 10.

Segueing from VirtualBox, the network is configured by default as NAT.  It is working and I can reach local resources.  The host is a macOS computer running VirtualBox 6.1.48.  I can further research VirtualBox configurations including more recent versions and other hosts, but I propose we take that discussion to another thread.

Thanks,
Michael

**Comment by rdmark** [comment]
You're right, the Solaris 10 docs don't talk about attr.h so the assumption that anything that matches SOLARIS has this header is incorrect. In fairness, Solaris 10 is a legacy version (2005) and there are limits to how many hoops we can (should) jump through to be backwards compatible... I want to try though!

After some tinkering, I was able to get set up with Solaris 10 1/13 on VirtualBox. Started capturing some installation notes on the wiki: https://github.com/Netatalk/netatalk/wiki/Installing-Netatalk-3-on-Solaris-10

The offending code that you ran into was introduced with this commit: https://github.com/Netatalk/netatalk/commit/0a2866325bcd446a5cded51de95f00820b554338

We need to introduce a more fine-grained capability check and replace or add to the SOLARIS check. Perhaps check for the presence and usability of attr.h itself?

Additionally, there is another portability deficiency elsewhere in the code right now. Namely: `libatalk/util/netatalk_conf.c` uses `flock()` calls which aren't Solaris compatible.

See: https://www.perkin.org.uk/posts/solaris-portability-flock.html

**Comment by rdmark** [comment]
@Michael-Wohlstadter Can you test if this resolves your problem? https://github.com/Netatalk/netatalk/pull/622

Note that we need to test that Solaris 11 as well as illumos distros still work.

**Comment by Michael-Wohlstadter** [comment]
@rdmark Your change does address the sys/attr.h issue on Solaris 10.  But as you already discovered, it now fails on flock().

I will setup a Solaris 11 virtual machine and test on that.

As to your comment about the age of Solaris 10, I do recognize the legacy state and that we can't support old operating systems forever.  My mild pushback would be that we shouldn't obsolete an operating system in a point release.  I do have time for testing and will continue to contribute as I can.

Thank you for your efforts.  I know that I greatly appreciate them, and based on the increase in activity here, I'm not alone.

Michael

**Comment by rdmark** [comment]
@Michael-Wohlstadter Thanks for the kind words! It is encouraging to get feedback, and know that the software is being used out there.

The reason I convinced myself that supporting Solaris 10 is the right thing to do, is that [Oracle has it on life support until January 2025](https://blogs.oracle.com/support/post/extended-support-for-oracle-solaris-10-operating-system).

FWIW, the last version that would have worked on Solaris 10 was 3.1.8 released in mid 2015, since 3.1.9 contains that code that we are looking to patch now. So you're the first one in 8 years who's trying to run the latest netatalk on that OS. ;)

**Comment by rdmark** [comment]
Filed https://github.com/Netatalk/netatalk/issues/623 for the flock() issue

**Comment by Michael-Wohlstadter** [comment]
@rdmark Again thank you.

I agree that the Solaris 10 user base is likely next to zero.  And it might be splitting hairs, but I am likely the only one trying to _compile_ Netatalk on Solaris 10 in the past eight years.  Indeed it is possible that others are using Netatalk on Solaris 10 and OpenCSW has the compiled version of Netatalk from the 3.1.8 code base available for download.  (I actually looked at that first before deciding that I wanted a more current version of Netatalk.) Additionally, until your involvement, Netatalk itself had become rather quiescent.  So while it might be a razor sharp edge case, with the renewed activity in Netatalk there could be a couple other folks who crawl out of the shadows as I have.  

However, to be fair, my interest is mostly nostalgia.  In the 90s when I was working with databases in corporate America, I had the opportunity to work with Digital's Rdb, IBM's DB2, and Oracle.  The Rdb experience was at a big Digital shop (I even have a couple of MicroVAX 3100's that I rescued from the scrap heap) and I got a small taste of working with VMS.  My involvement with DB2 was extremely limited and I'm not even sure of the hardware but if memory serves me correctly it was AS/400's.  But I spent most of my time with Oracle originally with version 7 and culminating with 8i which was hosted on Sparcs.

So my interest in Solaris 10 is mostly reminiscing.  For what it is worth, I do run an active Domino server on the Sun E250.  As a document based database, Notes/Domino was a technology ahead of its time.  I use it as a distributed information store.  But that's a story for another time.

Cheers and thanks again!

**Comment by rdmark** [comment]
@Michael-Wohlstadter Oh I totally get it. The reason I decided to start contributing to this project is also for retrocomputing purposes. Although my emphasis has been on retrocomputer *clients* and not retrocomputer *servers*. Obviously because I was a kid in the 80s-90s and only got into managing servers as a young adult circa 2003 (Linux by that point).

Netatalk 3.1.8 has a handful of known and now patched security holes so I agree with your approach of running newer code if at all possible! Luckily it seems the hurdle to restore Solaris 10 compatibility was quite low, so hopefully you should be good to go now. Please let me know if everything compiles and works in production.

BTW, one fun fact about Solaris 10 is that the Netatalk v2 codebase still has code for an AppleTalk kernel module for the Sparc architecture (won't compile on x86). I primarily use Netatalk v2 because I want the AppleTalk networking with my very old Macs and Apple IIs.

**Comment by Michael-Wohlstadter** [comment]
@rdmark It does now compile, but it isn't running correctly yet.  The issue is that I can't copy files to the volume.  The copy begins and an empty file is created but then I receive a prompt that the file already exists.  What I'm left with is a zero byte file on the target volume.

I want to research more to make sure that I don't have a mistake in my build or configuration.  The post that you shared   flock() and fcntl() mentions that locks are not held across forks with fcntl() and I'm wondering if that's related.  But I really want to try to make sure that I haven't made a mistake before I state that the fix doesn't work.

As to the vintage clients, my notes from that time are sketchy, but I have references to source tagged "ASUN" and hardware builds that include a Dayna DL2000 LocalTalk interface card.  I still have two 68K Macintoshes including my SE bought new in the mid 80's and an HP LaserJet IIP with the LocalTalk interface.  Really need to get the SE re-capped but the capacitors were looking okay about a year ago when I last examined them.  I haven't powered it on in a while.

Sorry if that last paragraph rambled a bit.  Just a trip down memory lane...

**Comment by rdmark** [comment]
@Michael-Wohlstadter as someone who has recapped dozens of Macs in recent years, I can emphatically say that recapping the SE is very low priority. You may want to check the PSU to make sure it’s a Sony OEM. Non-Sony compact Mac PSUs are prone to severe leakage. But we’re getting way off topic now. :)

Let me close out this ticket now since we’ve gotten past the compilation stage. If you still have trouble don’t hesitate to file a new issue ticket, or discussion thread (separate tab in the GitHub UI) if you’re not sure it’s an actual bug. 

Cheers!
