### ISSUE TITLE
Spotlight is very slow

### ISSUE THREAD

**Issue by andy-js** [Netatalk/Netatalk#62]
Title says it all.  On the CLI the results come back from tracker fast, but on the client side they take a while.

**Comment by slowfranklin** [comment]
Single term queries or multiple terms? Here's a takeaway from a recent discussion via IRC with one of the Tracker developers: when building fts queries with two subqueries we generate:

`SELECT ?url WHERE { ?obj fts:match 'protogonous*' . ?obj fts:match 'Uroglena*' . ?obj nie:url ?url . FILTER(tracker:uri-is-descendant('file:///afp/lots', ?url)) }
`

Afair, newer versions of Tracker will support a newer fts syntax resuling in faster queries:

`SELECT ?url WHERE { ?obj fts:match 'protogonous* Uroglena*' . ?obj nie:url ?url . FILTER(tracker:uri-is-descendant('file:///afp/lots', ?url)) }`

**Comment by andy-js** [comment]
Both single term and multi-term and pretty slow.  In the order of 3-5 seconds.

**Comment by slowfranklin** [comment]
Recommendation from 2021: switch to Samba and test with the new Elasticsearch backend.
