### ISSUE TITLE
Fixing bugs that can cause system errors in uam_getname

### ISSUE THREAD

**Issue by neko-hat** [Netatalk/netatalk#627]
It seems unlikely that a bug will occur, but it seems that a patch is needed just in case.

```
diff --git a/etc/afpd/auth.c b/etc/afpd/auth.c
index 15e16441..89a2a3b3 100644
--- a/etc/afpd/auth.c
+++ b/etc/afpd/auth.c
@@ -827,7 +827,7 @@ int afp_logout(AFPObj *obj, char *ibuf _U_, size_t ibuflen  _U_, char *rbuf  _U_
  */
 int afp_changepw(AFPObj *obj, char *ibuf, size_t ibuflen, char *rbuf, size_t *rbuflen)
 {
-    char username[MACFILELEN + 1], *start = ibuf;
+    char username[MAXUSERLEN], *start = ibuf;
     struct uam_obj *uam;
     struct passwd *pwd;
     size_t len;
```
It could be overflowed when uam_getname is called in afp_changepw. (that function is in etc/afpd/uam.c)
(name buf size is 32 but MAXUSERLEN is 255)

**Comment by rdmark** [comment]
@neko-hat It is an interesting discrepancy in buffer size, thank you for reporting.

The reason we are supporting the MAXUSERLEN (255) length of user names, is to be able to authenticate with ActiveDirectory or Windows NT domains (i.e. adding an "@domain" suffix to the username). So your proposed change will have the side effect of breaking that support. See: https://github.com/Netatalk/netatalk/commit/f46e5ef2816b2b330e9a8808e585f015c87d02b0#diff-61eb02c8f49a54f08a330e73818bdfe4f4c147d74b99964c516d246b4e94254b

The better solution might be to increase the buffer to MAXUSERLEN in `afp_changepw`... Although we should make sure that there won't be *other* side effects. What do you think?

**Comment by neko-hat** [comment]
Oh, I didn't consider supporting Windows NT domain.
I will fix the username size in afp_changepw to MAXUSERLEN and proceed with the PULL REQUEST again.

**Comment by rdmark** [comment]
@neko-hat PR merged; thanks again for your contribution. 

FYI I want to keep this ticket open until we investigate if the same patch is needed for the “old” netatalk v2 branch as well. The patch may need to be back ported.

**Comment by rdmark** [comment]
Backported to v2 with https://github.com/Netatalk/netatalk/pull/630
