### ISSUE TITLE
[PATCH] Login using LDAP creds fails if username case doesn't match

### ISSUE THREAD

**Issue by andy-js** [Netatalk/Netatalk#63]
LDAP username lookups are not case-sensitive but Kerberos Auth is.  Netatalk should be passing the username returned by LDAP when authenticating and not the one input by the user, which might not have the correct case.

<pre>
diff --git a/etc/uams/uams_dhx2_pam.c b/etc/uams/uams_dhx2_pam.c
index 8e79b45..51d45c0 100644
--- a/etc/uams/uams_dhx2_pam.c
+++ b/etc/uams/uams_dhx2_pam.c
@@ -325,7 +325,7 @@ static int login(void *obj, char *username, int ulen,  struct passwd **uam_pwd _
         return AFPERR_NOTAUTH;
     }
 
-    PAM_username = username;
+    PAM_username = dhxpwd->pw_name;
     LOG(log_info, logtype_uams, "DHX2 login: %s", username);
     return dhx2_setup(obj, ibuf, ibuflen, rbuf, rbuflen);
 }
</pre>

**Comment by slowfranklin** [comment]
Lgtm. Now a patch or pull request please.

**Comment by andy-js** [comment]
Done.
