### ISSUE TITLE
Refactor afpstats implementation to remove dependency on dbus-glib

### ISSUE THREAD

**Issue by ghost** [Netatalk/netatalk#666]
Potential roadmap for afpstats:
Compile afpstats support automatically if dbus and dbus-glib are present (easy, only requires netatalk.m4 macro changes). This would mean that afpstats support would require less user intervention and so make it more accessible. At the moment it needs the two dependencies along with the --with-afpstats configure flag _and_ afpstats=yes in afp.conf

Migrate from the now deprecated dbus-glib to  gdbus. I've already done some work on this but haven't got the coding skill to make it work correctly:

https://docs.gtk.org/gio/migrating-gdbus.html
https://github.com/dgsga/netatalk/commit/2f935ac7b2275ec1b4d63d397f9497e268d67b8d

@rdmark, what are your thoughts?

**Comment by rdmark** [comment]
Is dbus-glib going away any time soon? I see no rush to move to a newer library.

**Comment by dgsga** [comment]
D is-glib is now deprecated in favour of gdbus,last updated in 2021...

**Comment by rdmark** [comment]
Ah, that’s important context. The deprecation train keeps on going!

**Comment by rdmark** [comment]
This was raised in the Debian bug tracker as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955927
