### ISSUE TITLE
[2.3] Remove obsoleted style of appledouble support

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#668]
We currently support an obsoleted OSX 10.3 style AppleDouble metadata. I believe it was a transitional format before EA became the standard on OSX. Let’s remove the option and related code.

from the AppleVolumes man page:

> adouble:[v1|v2|osx]
> Specify the format of the metadata files, which are used for saving the Mac resource fork as well. Earlier versions used AppleDouble V1, while the new default format is V2. Starting with Netatalk 2.0, the scheme Mac OS X 10.3.x uses, is also supported.

> Note

> adouble:osx cannot be treated normally any longer. Its only aim was to temporarily share e.g. FAT32 formatted FireWire hard drives written on a Macintosh with afpd. Apple's metadata scheme lacks several essential features, so using it on the server's side will break both CNIDs and Mac OS 9 compatibility. An AppleDouble file of Mac OS X 10.6 is incompatible to V1 and V2.

**Comment by rdmark** [comment]
At a related note, I don’t think EA works properly on 2.2/2.3 although we have an option for it: `ea:sys`

**Comment by rdmark** [comment]
While reading the code, I found traces of an undocumented "sfm" style of appledouble metadata. Searching the mailing lists suggests it was a historical hack for a Samba hack by now-defunct Israeli company Exanet.

I will remove the code for this option in the same PR.

https://sourceforge.net/p/netatalk/mailman/message/22638728/
https://sourceforge.net/p/netatalk/mailman/message/24926910/

**Comment by NJRoadfan** [comment]
I suspect "sfm" means "Services For Macintosh", which was an AFP server that Microsoft shipped with Windows Server 2000 and 2003. On NTFS it should be using alternate data streams to store the resource forks of files. I don't know how it handled forks on FAT32 drives.
