### ISSUE TITLE
Configure not failing if libevent doesn't exists

### ISSUE THREAD

**Issue by KalleDK** [Netatalk/Netatalk#68]
If I do **not** install libevent and use configure with 

`./configure --without-libevent`

configure doesn't complain that libevent is not available, and compile will fail.

( Don't know if its a bug, but I would expect it to fail )

**Comment by andy-js** [comment]
I agree.  This is a bug.

**Comment by hat001** [comment]
$ ./configure --help
  --with-libevent         whether to use the bundled libevent (default: yes)
 
--------------
--with-libevent         use the bundled libevent
--without-libevent   not use he bundled libevent

**Comment by KalleDK** [comment]
@hat001 - yes that is what I would expect.

But configure doesn't fail like it does with the other options
--with-kerberos fails if I do not have kerberos

Hence --without-libevent should fail if I do not have libevent

**Comment by rdmark** [comment]
Bundled libevent removed with https://github.com/Netatalk/Netatalk/commit/f9e667934b5fbedeb70d9f58cd6afcad893e8baf
