### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by VorpalBlade** [Netatalk/netatalk#689]
Arch Linux has switched to [SPDX-identifiers](https://spdx.org/licenses/) for packaging software.
Previously I just marked the package as GPL2, but now I need to mark as either "GPL-2.0-only"  or "GPL-2.0-or-later". I cannot find info in this repository on which it is,

I would appreciate a clarification on this matter. 

*NOTE*: I package netatalk 2.x so that is what I'm interested (in case there are differences in the license between 2.x and 3.x).

**Comment by rdmark** [comment]
@VorpalBlade Thanks again for managing the Arch package!

The correct license is "GPL-2.0-only" for netatalk2. There is exactly one module (that I know of) which has a clause that adds a blocking condition. Namely cnid: https://github.com/Netatalk/netatalk/blob/main/libatalk/cnid/cnid.c

The copyright blurb mandates that the author approves any GPL "upgrade".
```
/*
 * Copyright (c) 2003 the Netatalk Team
 * Copyright (c) 2003 Rafal Lewczuk <rlewczuk@pronet.pl>
 *
 * This program is free software; you can redistribute and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation version 2 of the License or later
 * version if explicitly stated by any of above copyright holders.
 *
 */
```

See also the detailed copyright breakdown that the Debian package managers have been maintaining: https://salsa.debian.org/netatalk-team/netatalk/-/blob/debian/old/debian/copyright?ref_type=heads

**Comment by rdmark** [comment]
Please let me know if any further info is needed. Closing for now!

**Comment by rdmark** [comment]
@VorpalBlade BTW, I read the brief discussion thread at the Arch package page. I’d be the first to admit that the official manual is dense and inscrutable. If you come up with a handy getting-started guide please do share it here!

The one small thing that I did recently, was adding a feature matrix to the top of the netatalk website: https://netatalk.sourceforge.io/

…in the hope that this will at least provide a sliver of guidance towards which version to choose…

Feedback, ideas very welcome!

**Comment by rdmark** [comment]
And there’s also the FAQ: https://netatalk.sourceforge.io/docs/FAQ.html

**Comment by VorpalBlade** [comment]
@rdmark if only I knew how to write a better intro guide. But I haven't managed to *properly* configure it myself. My use case is an old first gen ibook that I dual boot OS 9 and 10.3 on.

I found that the only viable way to connect from OS 9 is as a guest login (something wrong with uams I guess?) to a specific IP (I cannot get it to show up in the chooser or network browser, if that is the correct terminology, I'm back translating from Swedish OS 9).

For 10.3 it was a bit easier, it can actually be discovered over the network just fine (assuming you don't build with avahi/mdns, but the older alternative instead). But I didn't get non-guest login working there either.

**Comment by rdmark** [comment]
There is a lot to unpack here! May I suggest you start a thread over at GitHub Discussions, where I can assist with troubleshooting. 

The short answers are: the first issue is UAM related, and the second is because you need AppleTalk for service discovery in Classic Mac OS
