### ISSUE TITLE
Cnid consistency

### ISSUE THREAD

**Issue by KalleDK** [Netatalk/netatalk#69]
MySql is missing from configure cnid options.. 

I can disable mysql via --without-mysql-config but that seems consistent with the others 

```
  --with-cnid-dbd-backend       build CNID with Database Daemon Data Store [yes]
  --with-cnid-cdb-backend   build CNID with Concurrent BDB Data Store  [no]
  --with-cnid-last-backend  build LAST CNID scheme                     [yes]
  --with-cnid-tdb-backend   build TDB CNID scheme                      [yes]
  --with-cnid-default-backend=val   set default DID scheme [dbd]
```

**Comment by rdmark** [comment]
Agreed that the inconsistency can be confusing. It was to me until I played around with the different options. Rather than messing with the cnid-backends macro, I suggest we update the html manual: https://github.com/Netatalk/netatalk/pull/266

**Comment by rdmark** [comment]
Merged to main.
