### ISSUE TITLE
Netatalk 2 afpd: -D and -T flags not consistent

### ISSUE THREAD

**Issue by rofore** [Netatalk/netatalk#725]
The afpd `man` page lists the -D flag as follows: 

```
-D
    Use DDP (AppleTalk) as transport protocol. (Equivalent to -ddp in afpd.cond.)
```

But the code appears to disable DDP instead:

```
case 'D':
    options->transports &= ~AFPTRANS_DDP;
    break;
```

Because `options->transports` is initialized like `options->transports = AFPTRANS_ALL; /*  TCP and DDP */`, you cannot simply change it to
```
case 'D':
    options->transports |= AFPTRANS_DDP;
    break;
```

So my suggestion would be to ether change the man page or introduce flags like `--ddp`, `--noddp`, `--tcp` etc.. like in afpd.conf

**Comment by rdmark** [comment]
The equivalent logic exists for -T and TCP so we have the same discrepancy between code and man page there. 

At present, the default behavior of afpd when no config file is present, is to enable both DDP and TCP (-transall). So I think it makes sense that -D and -T act as the negation of that.

**Comment by rdmark** [comment]
Proposing to fix with https://github.com/Netatalk/netatalk/pull/727
