### ISSUE TITLE
[PATCH] Stale pid file puts netatalk into maintenance mode

### ISSUE THREAD

**Issue by andy-js** [Netatalk/Netatalk#73]
SMF ensures that only a single instance of netatalk is ever started.  There’s no need to futz with a pidfile.  I decided to leave libatalk as it is for now (keeping its API consistent across all platforms - hopefully) in the off chance that there’s a consumer outside netatalk that relies on this.

<pre>
diff --git a/etc/netatalk/netatalk.c b/etc/netatalk/netatalk.c
index bbb782d..285a1a6 100644
--- a/etc/netatalk/netatalk.c
+++ b/etc/netatalk/netatalk.c
@@ -299,7 +299,9 @@ static void kill_childs(int sig, ...)
 /* this get called when error conditions are met that require us to exit gracefully */
 static void netatalk_exit(int ret)
 {
+#ifndef SOLARIS
     server_unlock(PATH_NETATALK_LOCK);
+#endif
     exit(ret);
 }
 
@@ -373,7 +375,9 @@ static void show_netatalk_paths( void )
        printf( "     dbus-session.conf:\t%s\n", _PATH_CONFDIR "dbus-session.conf");
 #endif
 
+#ifndef SOLARIS
        printf( "    netatalk lock file:\t%s\n", PATH_NETATALK_LOCK);
+#endif
 
 }
 
@@ -412,14 +416,18 @@ int main(int argc, char **argv)
         }
     }
 
+#ifndef SOLARIS
     if (check_lockfile("netatalk", PATH_NETATALK_LOCK) != 0)
         exit(EXITERR_SYS);
+#endif
 
     if (!debug && daemonize(0, 0) != 0)
         exit(EXITERR_SYS);
 
+#ifndef SOLARIS
     if (create_lockfile("netatalk", PATH_NETATALK_LOCK) != 0)
         exit(EXITERR_SYS);
+#endif
 
     sigfillset(&blocksigs);
     sigprocmask(SIG_SETMASK, &blocksigs, NULL);
</pre>

**Comment by slowfranklin** [comment]
Nack I guess. As I've just learned, there are still Solaris 10 installations around that want to update to newer versions. That was for Samba, but it made me aware of the fact.
Maybe we can check for presence of SMF instead? There's probably some SMF header around who's presence we could check at configure time (hm... don't we already do this?).

**Comment by andy-js** [comment]
Not sure I follow.  Solaris 10 has SMF.

**Comment by slowfranklin** [comment]
Uh, right. I even added the SMF support to disturb/initscripts/ back then for Solaris 10. Sorry for the confusion. :)
But please add the platform specific handling of the lock file into the functions create_lockfile() and server_unlock(), not into the callers.

**Comment by andy-js** [comment]
No problem.  Will do.  Thanks for the feedback.

**Comment by andy-js** [comment]
How does this look?

<pre>
diff --git a/NEWS b/NEWS
index 54a130e..9a0ccfc 100644
--- a/NEWS
+++ b/NEWS
@@ -2,6 +2,7 @@ Changes in 3.1.10
 ================
 * FIX: cannot build when ldap is not defined, bug #630
 * FIX: SIGHUP can cause core dump when mdns is enabled, bug #72
+* FIX: Solaris: stale pid file puts netatalk into maintenance mode, bug #73
 
 Changes in 3.1.9
 ================
diff --git a/etc/netatalk/netatalk.c b/etc/netatalk/netatalk.c
index ec409a3..9052fa6 100644
--- a/etc/netatalk/netatalk.c
+++ b/etc/netatalk/netatalk.c
@@ -374,7 +374,9 @@ static void show_netatalk_paths( void )
        printf( "     dbus-session.conf:\t%s\n", _PATH_CONFDIR "dbus-session.conf");
 #endif
 
+#ifndef SOLARIS
        printf( "    netatalk lock file:\t%s\n", PATH_NETATALK_LOCK);
+#endif
 
 }
 
diff --git a/libatalk/util/server_lock.c b/libatalk/util/server_lock.c
index 6ae817e..45d1a93 100644
--- a/libatalk/util/server_lock.c
+++ b/libatalk/util/server_lock.c
@@ -33,6 +33,7 @@ static struct itimerval itimer;
  * been changed to do the kill() thing. */
 pid_t server_lock(char *program, char *pidfile, int debug)
 {
+#ifndef SOLARIS
   char buf[10];
   FILE *pf;
   pid_t pid;
@@ -95,7 +96,7 @@ pid_t server_lock(char *program, char *pidfile, int debug)
   fprintf(pf, "%d\n", getpid());
   fclose(pf);
   } 
-
+#endif
   return 0;
 }
 
@@ -104,6 +105,7 @@ pid_t server_lock(char *program, char *pidfile, int debug)
  */
 int check_lockfile(const char *program, const char *pidfile)
 {
+#ifndef SOLARIS
     char buf[10];
     FILE *pf;
     pid_t pid;
@@ -118,6 +120,7 @@ int check_lockfile(const char *program, const char *pidfile)
         }
         fclose(pf);
     }
+#endif
     return 0;
 }
 
@@ -126,6 +129,7 @@ int check_lockfile(const char *program, const char *pidfile)
  */
 int create_lockfile(const char *program, const char *pidfile)
 {
+#ifndef SOLARIS
     FILE *pf;
     int mask;
   
@@ -142,6 +146,6 @@ int create_lockfile(const char *program, const char *pidfile)
     umask(mask);
     fprintf(pf, "%d\n", getpid());
     fclose(pf);
-
+#endif
     return 0;
 }
</pre>

**Comment by slowfranklin** [comment]
On Fri, Aug 19, 2016 at 02:29:42AM -0700, Andrew Stormont wrote:
> How does this look?

lgtm.

Cheerio!
-slow
