### ISSUE TITLE
2.3.1 neither generates nor installs init scripts.  Documentation is never generated.

### ISSUE THREAD

**Issue by snhirsch** [Netatalk/netatalk#739]
**Describe the bug**

There are init script templates for many different systems, but the build process never produces the appropriate output.  I cannot find any particular optional make target to do so either.

Similarly, the manual is never created from XML.

**To Reproduce**
Steps to reproduce the behavior.

Configure for the build system, run 'make', then 'make install'

**Expected behavior**

I expected to find a netatalk startup file in /etc/init.d and a configuration file under /etc/default.

**Environment**
 - Server OS: 
 Debian Linux 6.0.10

 - Client OS [n/a]

 - Netatalk Version 

2.3.1

**Logs**
Attach syslogs from the malfunctioning process, `maxdebug` log level n/a/.

**Additional context**
If it is a crash, please attach a [stacktrace](https://github.com/Netatalk/netatalk/wiki/Using-GDB-to-Analyze-a-Crash).

**Comment by rdmark** [comment]
This section in the manual talks about how to enable the OS specific init scripts:

https://netatalk.io/oldstable/htmldocs/installation#compiling-netatalk

On debian you can either do `--enable-debian` for traditional sysv style init scripts, or `--enable-systemd` for systemd.

This wiki page talks about how to generate the manual from XML sources:

https://netatalk.io/docs/Release-Process

And yes, you are correct to note that neither of these compile time options are enabled by default. Last year I experimented with autodetecting the right init script type for the host OS, but couldn't get autoconf to consistently do what I wanted it to...

**Comment by snhirsch** [comment]
Thanks for the clarification.  Part of the issue is that documentation and source are sort of scattered around.  

The `--enable-debian` flag worked and I now have a proper init script.  However, it does not create /etc/default/netatalk.

The instructions for setting up the doc build result in a 'yes' in the configuration summary, yet the manual is still not being generated.  I tried 'make', 'make doc', 'make pdf' and anything else I could think of with no success.

**Comment by rdmark** [comment]
Fair enough. I've gradually been fleshing out the docs and improving on https://netatalk.io to serve as a hub for everything. Do you have suggestions on how to organize it better?

Can you check if the config file is located in `/usr/local/etc/default/netatalk`? The automake logic for installing this file is `$(INSTALL_DATA) $(srcdir)/netatalk.conf $(DESTDIR)/etc/default/netatalk;` so it all depends on what DESTDIR expands to.

And finally, the correct make target for building the manual is `make html` ... this is also noted in that wiki page if you look closely.

**Comment by rdmark** [comment]
> I'm finding /usr/local/etc/netatalk/netatalk.conf, but there is not even a /usr/local/etc/default directory much less a configuration file within it.

The former is surely a remnant of your earlier attempt. Please try to remove it manually and then run `make install` for netatalk again and see if it gets recreated or not.

It's still a mystery why `/etc/default/netatalk` doesn't get created. The Makefile logic looks correct to me. Let me try in my own Debian environment when I get home from work tonight.

> The applicability of documentation pages to v2 vs. v3 of netatalk should be clear. The user should not have to figure out what might apply to their choice of build.

Agreed. One improvement idea I have is to print the netatalk version number more prominently on html manual pages. Right now it's only on the index page. Beyond that, I *think* I've been pretty good at labeling wiki pages etc. with applicable netatalk version.

> While there are instructions for checking out the latest 2.x build, there is no guidance (that I could see) for cloning the latest release version.

You mean like cloning the git tag of the latest release? That is true. My intention was for people to go to Releases and pick the latest release tarball and go from there.

> Since many folks will be going to the Github page, there should be specific mention - at the top - about where to go if you want the 2.x version (directing them to the .io pages).

What we have right now is the third paragraph in the README.md on the Github landing page that points you how to find 2.x releases. You would like to see it even higher up on that page?

**Comment by rdmark** [comment]
Something like this might get you a pdf manual: 

https://stackoverflow.com/questions/2615002/how-to-generate-pdf-from-docbook-5-0

I believe our docbook XML sources are in the older 4.5 format.

**Comment by rdmark** [comment]
Hm, I can't reproduce your issue with `/etc/default/netatalk`. I'm configuring with a simple `./configure --enable-debian` and then install. The config file gets installed as expected.

Can you share all the parameters you pass to `configure`? Please also share the logs from `make install`.

**Comment by snhirsch** [comment]
Thanks for the tip on PDF output!  The dblatex utility did the trick.
[netatalk_manual.pdf](https://github.com/Netatalk/netatalk/files/14602638/netatalk_manual.pdf)

**Comment by snhirsch** [comment]
Mea Culpa!  The issue with `/etc/default/netatalk` was pilot error.   The file existed already and was (correctly) not overwritten.  I kept misreading your advice about removing it first by ensuring it wasn't under `/usr/local/etc`.  Sorry about that.  

I'm curious:  Why was all the documentation removed from AppleVolumes.default?  Not sure when that happened, but the 13 year old file I had been using was a lot larger.

**Comment by snhirsch** [comment]
> > The applicability of documentation pages to v2 vs. v3 of netatalk should be clear. The user should not have to figure out what might apply to their choice of build.
> 
> Agreed. One improvement idea I have is to print the netatalk version number more prominently on html manual pages. Right now it's only on the index page. Beyond that, I _think_ I've been pretty good at labeling wiki pages etc. with applicable netatalk version.

I think that's a good idea.

> 
> > While there are instructions for checking out the latest 2.x build, there is no guidance (that I could see) for cloning the latest release version.
> 
> You mean like cloning the git tag of the latest release? That is true. My intention was for people to go to Releases and pick the latest release tarball and go from there.

I just navigated to releases and unless I'm missing the obvious I do not see a download link.  The only place I found links to tarballs was on the `.io` site.

> 
> > Since many folks will be going to the Github page, there should be specific mention - at the top - about where to go if you want the 2.x version (directing them to the .io pages).
> 
> What we have right now is the third paragraph in the README.md on the Github landing page that points you how to find 2.x releases. You would like to see it even higher up on that page?

No, not necessarily.  But it wouldn't hurt to boldface or highlight the mention of older machines and insert a link to the `.io` site.

**Comment by rdmark** [comment]
> Mea Culpa! The issue with `/etc/default/netatalk` was pilot error. The file existed already and was (correctly) not overwritten. I kept misreading your advice about removing it first by ensuring it wasn't under `/usr/local/etc`. Sorry about that.
> 

Good to hear that you figured it out!

> I'm curious: Why was all the documentation removed from AppleVolumes.default? Not sure when that happened, but the 13 year old file I had been using was a lot larger.

It was removed in an effort to reduce duplicated documentation. The same topics are covered by the manual pages, i.e. https://netatalk.io/oldstable/htmldocs/AppleVolumes.default.5

When you have duplicated information and no single source of truth, you face higher maintenance costs and higher risk of diverging/outdated documentation. This diverging had started to occur in practice at the time.

**Comment by rdmark** [comment]
> > > The applicability of documentation pages to v2 vs. v3 of netatalk should be clear. The user should not have to figure out what might apply to their choice of build.
> > 
> > 
> > Agreed. One improvement idea I have is to print the netatalk version number more prominently on html manual pages. Right now it's only on the index page. Beyond that, I _think_ I've been pretty good at labeling wiki pages etc. with applicable netatalk version.
> 
> I think that's a good idea.
> 

This code change should do the trick I think: https://github.com/Netatalk/netatalk/pull/741

> > > While there are instructions for checking out the latest 2.x build, there is no guidance (that I could see) for cloning the latest release version.
> > 
> > 
> > You mean like cloning the git tag of the latest release? That is true. My intention was for people to go to Releases and pick the latest release tarball and go from there.
> 
> I just navigated to releases and unless I'm missing the obvious I do not see a download link. The only place I found links to tarballs was on the `.io` site.
> 

What happens if you expand the "Assets" at the bottom of the GitHub release notes?

> > > Since many folks will be going to the Github page, there should be specific mention - at the top - about where to go if you want the 2.x version (directing them to the .io pages).
> > 
> > 
> > What we have right now is the third paragraph in the README.md on the Github landing page that points you how to find 2.x releases. You would like to see it even higher up on that page?
> 
> No, not necessarily. But it wouldn't hurt to boldface or highlight the mention of older machines and insert a link to the `.io` site.

Ok, let me take this into consideration the next time I touch up the README.

**Comment by rdmark** [comment]
Okay I see your point. The Assets section is only expanded when you follow a direct link to a release tag, and not on a list of all releases, or a search results page. The GitHub UI is being obtuse. I'll add a link to the netatalk.io downloads page in addition.

**Comment by snhirsch** [comment]
Glad it wasn't just me.

**Comment by rdmark** [comment]
@snhirsch This is what I'm proposing for disambiguating the html manual pages: Print the Netatalk version number above the chapter heading on each generated html page. What do you think?

![image](https://github.com/Netatalk/netatalk/assets/2108467/98d1e1af-787f-412f-9fb0-182dce610fcf)

**Comment by snhirsch** [comment]
Any way to highlight the version or enlarge the font?  Seriously, it does make things much clearer - thanks!

**Comment by rdmark** [comment]
I can style that div with any html or css style that I want. At first I gave it the same style as the navheader below (80% font size and bold), but it looked awkward above the actual navheader (chapter title). I also tried the different pre-defined heading styles in the netatalk.css stylesheet, but wasn't happy with the look either. For instance, when using the header styles (h1, h2, h3) the colored block merges with the title bar.

I don't want that line too overpowering, or taking up too much vertical real-estate on the page, so the options are somewhat limited. Happy to field concrete ideas.

**Comment by rdmark** [comment]
The online html manual for both stable and oldstable have been updated now, e.g. https://netatalk.io/oldstable/htmldocs/

With this PR I aim to more prominently promote netatalk 2.x, and make it easier to find releases: https://github.com/Netatalk/netatalk/pull/782 Please let me know if you think this would be more helpful for visitors in the future.

**Comment by snhirsch** [comment]
Thanks, Daniel.  I've been suffering with a terrible head cold and haven't had much energy for anything over the past few days.  I'll review the documentation when I feel better.

**Comment by snhirsch** [comment]
Ok, while still at the keyboard I went here: `https://netatalk.io/oldstable/htmldocs/installation#idm61` to pull what one would have expected to be the 2.3.2 source code.  Unfortunately that gets you 3.1.99dev.  This is the type of thing that is likely to throw beginners.

**Comment by rdmark** [comment]
I hope you feel better soon!

You're right, those git instructions are unfortunate. One challenge is that we create new stable branches for each minor release version (branch-netatalk-2-3 etc.) so keeping that information up to date will be an overhead. Let me think about how to write that paragraph in a helpful and maintainable way.

**Comment by rdmark** [comment]
This should make for a more helpful git section I think: https://github.com/Netatalk/netatalk/pull/784
