### ISSUE TITLE
please clarify licensing of etc/afpd/fce_api.c

### ISSUE THREAD

**Issue by jonassmedegaard** [Netatalk/Netatalk#74]
The file etc/afpd/fce_api.c indicates - both in its copyright statement, in commit message when initially added to the project, and in VCS tag back when initially added - to be originally authored by Mark Williams in 2010, one year before inclusion in netatalk.

That code lacks proper licensing information, however.

Please include in header of the file the licensing granted by Mark Williams.

**Comment by hat001** [comment]
Please post a patch file.

**Comment by jonassmedegaard** [comment]
Hi hat001,

The issue raised here is that knowledge of licensing information is missing.

What is needed here is to get the needed information from the copyright holder of the code: Mark Williams.

Alternatively, if Mark Williams cannot be reached, or if he is unwilling to license his code in a way compatible with the rest of Netatalk, then that code need to be dropped/rewritten.

I have contacted Frank Lahm by mail about this issue, as it seems he introduced this code into Netatalk, so might have more knowledge about getting in touch with Mark Williams.

Hope that helps.

**Comment by jonassmedegaard** [comment]
More accurately, the code currently is *not* licensed freely!

**Comment by slowfranklin** [comment]
On Fri, Sep 02, 2016 at 11:06:31PM -0700, Jonas Smedegaard wrote:
> The issue raised here is that knowledge of licensing information is
> missing.
> 
> What is needed here is to get the needed information from the
> copyright holder of the code: Mark Williams.

I've reached out to Mark but haven't received a response yet.

> Alternatively, if Mark Williams cannot be reached, or if he is
> unwilling to license his code in a way compatible with the rest of
> Netatalk, then that code need to be dropped/rewritten.

I don't think we're going to enter a discussion about licensing
requirements here, at least I will stay away from it. If anyone comes
up with patches that can replace the existing code then I'm fine with
that, but I'm going to nack patches that remove it just because of
licensing issues.

Cheerio!
-slow

**Comment by jonassmedegaard** [comment]
Quoting slowfranklin (2016-09-03 12:04:22)
> On Fri, Sep 02, 2016 at 11:06:31PM -0700, Jonas Smedegaard wrote:
>> The issue raised here is that knowledge of licensing information is 
>> missing.
>>
>> What is needed here is to get the needed information from the 
>> copyright holder of the code: Mark Williams.
>
> I've reached out to Mark but haven't received a response yet.

Thanks!


>> Alternatively, if Mark Williams cannot be reached, or if he is 
>> unwilling to license his code in a way compatible with the rest of 
>> Netatalk, then that code need to be dropped/rewritten.
>
> I don't think we're going to enter a discussion about licensing 
> requirements here, at least I will stay away from it.

Sorry - I did not mean to dictate the netatalk project what do or not do 
about licensing.  My intent was solely to clarify that in my opinion the 
next step in resolving this issue is more "what is the license?" than 
"where is the patch?" - i.e. responding to the comment by hat001.


> If anyone comes up with patches that can replace the existing code 
> then I'm fine with that, but I'm going to nack patches that remove it 
> just because of licensing issues.

I (think I understand and) respect your unwillingness to discuss 
licensing, and will therefore simply ask (and promise to not comment on 
the response, no matter what you choose to respond, including silence):

Under which licensing terms (granted by whom, if not Mark Williams) do 
the netatalk project currently redistribute the file etc/afpd/fce_api.c?


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by slowfranklin** [comment]
Hi Jonas,

btw, I appreciate your effort to sort out this licensing
issue and to bring Netatalk back to Debian!

On Sat, Sep 03, 2016 at 03:51:19AM -0700, Jonas Smedegaard wrote:
> > If anyone comes up with patches that can replace the existing code 
> > then I'm fine with that, but I'm going to nack patches that remove it 
> > just because of licensing issues.
> 
> I (think I understand and) respect your unwillingness to discuss 
> licensing, and will therefore simply ask (and promise to not comment on 
> the response, no matter what you choose to respond, including silence):
> 
> Under which licensing terms (granted by whom, if not Mark Williams) do 
> the netatalk project currently redistribute the file etc/afpd/fce_api.c?

No idea. :) I'm no licensing expert, but afaict shouldn't this new
code be forced to inherit the GPL from the "surrounding" code? Iow, no
matter which license Mark Williams would have liked to put this under,
it forcibly inherits the GPL and must be licensed under the GPL.

I will ping Mark once more in the course of next week.

Cheerio!
-slow

**Comment by jonassmedegaard** [comment]
Quoting slowfranklin (2016-09-03 13:36:32)
> btw, I appreciate your effort to sort out this licensing
> issue and to bring Netatalk back to Debian!
>
> On Sat, Sep 03, 2016 at 03:51:19AM -0700, Jonas Smedegaard wrote:
>>> If anyone comes up with patches that can replace the existing code 
>>> then I'm fine with that, but I'm going to nack patches that remove 
>>> it just because of licensing issues.
>>
>> I (think I understand and) respect your unwillingness to discuss 
>> licensing, and will therefore simply ask (and promise to not comment 
>> on the response, no matter what you choose to respond, including 
>> silence):
>>
>> Under which licensing terms (granted by whom, if not Mark Williams) 
>> do the netatalk project currently redistribute the file 
>> etc/afpd/fce_api.c?
>
> No idea. :) I'm no licensing expert,

[no comment, as promised]


> but afaict shouldn't this new code be forced to inherit the GPL from 
> the "surrounding" code?

[not sure if breaking my promise here, but since you explicitly ask...]

I am not a lawyer either, but as I understand it, what you ask here is 
the license resulting license when combining multiple works - commonly 
called "effective license": That only makes sense to resolve _after_ 
resolving the licensing of each part involved in a combined work.

Broadly speaking, free licensing is either "permissive" (granting 
freedoms) or "copyleft" (mandating "inheritance" of granted freedoms).

Currently I am unaware if the copyright holder of this code intended for 
it to be...

 a) not licensed (the default if saying nothing in most places¹)
 b) permissively licensed (e.g. BSD- or MIT-style).
 c) copyleft, and compatible with copyleft of Netatalk
 d) copyleft, but incompatible with copyleft of Netatalk

In cases b) and d) will the _effective_ licensing after compiling 
this code with Netatalk code licensed as GPL.

But if this code is not licensed, or its license is incompatible (e.g. 
has a "do no evil" clause" which clahses with GPL mandates), then there 
is no effective license because the act of redistributing the compiled 
binary is forbidden (by the _combination_ of multiple licenses - all 
licenses may permit redistribution but under _different_ circumstances).

Debian, where I am involved, redistributes both source and binary code, 
so we need this specific code to be licensed compatible with Netatalk.  
The Netatalk project does not (as I understand it) redistribute compiled 
code and therefore can legally distribute code which is a) legal to 
compile and use but b) illegal to redistribute in compiled form.  But I 
fail to see a reason that the Netatalk project would want to do that 
(and now I am really throwing bait for discussion, so will stop here!).


> Iow, no matter which license Mark Williams would have liked to put 
> this under, it forcibly inherits the GPL and must be licensed under 
> the GPL.

[no comment, as promised (tell me if you want my comments)]


> I will ping Mark once more in the course of next week.

Thanks!


 - Jonas


¹ https://en.wikipedia.org/wiki/Berne_Convention#Copyright_term

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by slowfranklin** [comment]
After some more digging in email boxes we concluded that the code in question was clearly submitted under the GPL.

**Comment by jonassmedegaard** [comment]
Thanks for the digging, @slowfranklin - could you please then update the licensing information accordingly?

The issue reported here is that `etc/afpd/fce_api.c` simply says "See COPYRIGHT" and the file `COPYRIGHT` in topmost directory does not tell which parts have which licenses (and none of the licenses there are versions of GPL).

**Comment by slowfranklin** [comment]
8da45ffe426b937c0b20ee8abcd2700175432309

**Comment by jonassmedegaard** [comment]
perfect :-)
