### ISSUE TITLE
Detect system docbook stylesheets at configure time

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#746]
Debian/Ubuntu ships docbook-xsl packages that are installed into `/usr/share/xml/docbook`. Fedora seems to have them as well: https://src.fedoraproject.org/rpms/docbook-style-xsl

It would be handy if the build system could detect these stylesheets automatically without having to pass the path with the `--with-docbook` parameter (or the equivalent in Meson).

**Comment by dgsga** [comment]
Good idea. Shall I  set up auto-detection for docbook stylesheets by meson too?

**Comment by rdmark** [comment]
Yes please, that would be great.

**Comment by dgsga** [comment]
> Yes please, that would be great.

Automatic docbook root detection is now working with meson on Debian and Ubuntu. The question is do we want manpages / documentation to be generated automatically? I can change the syntax with meson so that the docbook root is auto-detected but the manpages/html are only built if the user specifies -Dwith-manpages or -Dwith-documentation. What do you think?

**Comment by rdmark** [comment]
Good question. For starters, is there a need to split this into two options? Both manpages and html docs have the same dependencies, so why don't turn on and off both with one option? It doesn't make a huge difference either way, but keeping things simple where possible is a good practice.

Let's break down the scenarios:

1. User wants the manpages, but doesn't have the dependencies
2. User wants the manpages, and has the dependencies
3. User doesn't want the manpages, and doesn't have the dependencies
4. User doesn't want the manpages, but has the dependencies

In scenario 1, I think we want an error message telling them what tools to install.

Scenario 2 might be the most challenging with your suggestion, since it's unclear to the user that they need to take special action to get the manpages. Especially if they're used to always getting manpages by default (e.g. as in the previous netatalk build system.)

Scenario 3 is moot, and scenario 4 seems like a very unlikely outcome. Why would someone not want manpages installed with the software on their system?

**Comment by rdmark** [comment]
As a side note, I tried to build the docbook docs on macOS and Fedora but ran into errors.

On Fedora the docbook-style-xsl package installs the stylesheets into `/usr/share/sgml/docbook/xsl-stylesheets`

On macOS homebrew puts it in `/opt/homebrew/opt/docbook-xsl/docbook-xsl/`

The error happens when it tries to start transcoding the html pages.

```
doc/manual/meson.build:23:22: ERROR: configure_file keyword argument 'output' was of type File but should have been str
```

I haven't been able to dig to deep into the cause yet, but I wonder if you've seen this too and know a workaround?

**Comment by dgsga** [comment]
All fixed, manages are installed by default from the man subdirectory and the manual is only built if -Dbuild-manual=true is passed to meson. I am currently working through all the oses to add their default docbook-xsl paths... The docbook macro also errors out if docbook-xsl or xsltproc are not found when -Dbuild-manual=true
