### ISSUE TITLE
Lock issues when using Git over AFP on OSX 10.10+

### ISSUE THREAD

**Issue by hadjedjvincent** [Netatalk/netatalk#75]
Hi,

I'm experiencing an issue when using git over an AFP mounted sharing point on OSX (10.10 or 10.11).
Randomly, i'm getting error (from git), like :

`fatal: unable to write new_index file`
`fatal: Could not write new index file.`

The only way to fix this, is to do a `git status` on the remote server (will not work locally).
Sometimes it does not fix the issue anyway, and we must restart netatalk to remove this lock...

I don't know if it's related to `git` which is maybe not doing the lock correctly ? Or directly related to Netatalk.
There are few people experiencing the same issue, and most of them are using OSX (looks so).

So it may be related to Netatalk <=> OSX only.

I'm using latest version available (3.1.9) compiled on the server, which is running ubuntu trusty.

How could i help to give you more information about the lock issues ? Is there any debug flag i can enable somewhere (even if i have to recompile) ?

Regards,

**Comment by mligor** [comment]
I got the same issue today - Netatalk on rPi (armv7l raspbian) and OSX 10.13.1.

Something is locking index file, but I'm not able to find out what.

I found similar issue here:
https://apple.stackexchange.com/questions/111934/git-not-working-over-afp

**Comment by rdmark** [comment]
Let's call this a "wontfix" since AFP is known to not coexist well with git.
