### ISSUE TITLE
[2.3] afpd SIGABRT after forking when running on macOS

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#755]
At some point between August 2023 and today netatalk 2.x stopped working on macOS. I tested it before releasing 2.2.10, at the very least.

But with Sonoma 14.4 there's a SIGABRT after authenticating.

```
% sudo afpd -d
objc[20713]: +[ODNode initialize] may have been in progress in another thread when fork() was called.
objc[20713]: +[ODNode initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

```
Mar 25 23:52:38.516232 afpd[20749] {dsi_stream.c:179} (D10:DSI): buf_read(84 bytes): got: 84
Mar 25 23:52:38.516809 afpd[20749] {dsi_stream.c:432} (D10:DSI): dsi_stream_read(84 bytes): got: 84
Mar 25 23:52:38.517381 afpd[20749] {dsi_stream.c:551} (D5:DSI): dsi_stream_receive: DSI cmdlen: 84
Mar 25 23:52:38.517959 afpd[20749] {afp_dsi.c:598} (D5:DSI): DSI request ID: 3
Mar 25 23:52:38.518534 afpd[20749] {afp_dsi.c:613} (D5:AFPDaemon): <== Start AFP command: AFP_LOGINCONT
Mar 25 23:52:38.527916 afpd[20749] {uams_dhx_pam.c:158} (I:UAMS): uams_dhx_pam.c :PAM: PAM Success
Mar 25 23:52:38.529105 afpd[20738] {main.c:202} (I:AFPDaemon): child[20749]: killed by signal 6
Mar 25 23:52:38.529150 afpd[20738] {main.c:394} (D10:AFPDaemon): main: polling 1 fds
```

**Comment by dgsga** [comment]
@rdmark, I think the issue probably lies with macOS and not netatalk. A recent macOS update has begun terminating certain fork() processes under specific circumstances .If you look at the stop/start/restart script in v3 (netatalkd), you can see it contains the line:
`export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES`
Try exporting this environment variable before running the afpd command and let me know how you get on. Maybe we need to replace the fork() functions but TBH I really wouldn't know where to start. Hmmm...

**Comment by rdmark** [comment]
@dgsga I tried doing `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` and then launching cnid_metad and atalkd in sequence in the terminal, but that led to the same behavior.

So instead I created a netatalkd init script by mimicking what you did in main, and got it working that way!

Here's the commit from my work branch: https://github.com/Netatalk/netatalk/commit/b79589c779ee6fe904db5f6bb82b84f1099f5beb

Note that I haven't made a PR yet because the code is hackish. For instance, I couldn't get the launchd plists working properly. BTW why do we have both launchd plist configs *and* a netatalkd init script? They seem to be two things that have the same function.

**Comment by rdmark** [comment]
The discussion in https://github.com/php/php-src/issues/11818 has some additional context and links to other articles that go into depth on the topic.

**Comment by dgsga** [comment]
> @dgsga I tried doing `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` and then launching cnid_metad and atalkd in sequence in the terminal, but that led to the same behavior.
> 
> So instead I created a netatalkd init script by mimicking what you did in main, and got it working that way!
> 
> Here's the commit from my work branch: [b79589c](https://github.com/Netatalk/netatalk/commit/b79589c779ee6fe904db5f6bb82b84f1099f5beb)
> 
> Note that I haven't made a PR yet because the code is hackish. For instance, I couldn't get the launchd plists working properly. BTW why do we have both launchd plist configs _and_ a netatalkd init script? They seem to be two things that have the same function.

The netatalkd script ids a convenient way of starting/stopping/restarting netatalk once it has been installed on a macOS system. The launchd plist starts netatalk on boot.

**Comment by dgsga** [comment]
I have just committed a wee tweak to your branch that should fix the plists. You could also combine them into one like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>PATH</key>
		<string>/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
		<key>OBJC_DISABLE_INITIALIZE_FORK_SAFETY</key>
		<string>YES</string>
	</dict>
	<key>Label</key>
	<string>com.netatalk.daemon</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/bash</string>
		<string>-c</string>
                <string>/usr/local/sbin/cnid_metad && /usr/local/sbin/afpd</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/tmp/netatalk.err</string>
	<key>StandardOutPath</key>
	<string>/tmp/netatalk.out</string>
</dict>
</plist>
```

**Comment by rdmark** [comment]
Oh, thank you for doing that. I do not mind the intrusion. 

Merging the two plists into one is probably for the better. 99% of the times a user would use the dbd backend so… 

…if you have a moment to spare, please make that change too. 

The final thing that should be done is to implement the prefix path substitution. For some reason I couldn’t get autoconf to play ball and I ran out of time and had to go to work.

**Comment by dgsga** [comment]
Leave it with me.

**Comment by rdmark** [comment]
Cheers!

**Comment by rdmark** [comment]
The newly added netatalkd helper script does the trick on Sonoma 14.4.1
