### ISSUE TITLE
Backport meson build system to the 2.4 branch

### ISSUE THREAD

**Issue by dgsga** [Netatalk/netatalk#759]

**Comment by rdmark** [comment]
@dgsga I plan to tag the next 2.3 release this weekend. If by a miracle you're done with this by then we can include it.

**Comment by rdmark** [comment]
The current plan is to target this for the next minor feature release: 2.4.0

**Comment by dgsga** [comment]
@rdmark, @NJRoadfan. The meson implementation is ready to PR. Please can you test and feedback? Any suggestions welcome.

**Comment by rdmark** [comment]
@dgsga The html manual has a passage about building with autotools. Shall we update that with instructions for Meson as well, or do you have another idea how to rephrase or consolidate information?

https://github.com/Netatalk/netatalk/blob/branch-netatalk-2-4/doc/manual/install.xml

**Comment by rdmark** [comment]
@dgsga does this build system have an uninstall target? Sorry if you covered this already and I forgot…

**Comment by dgsga** [comment]
> @dgsga does this build system have an uninstall target? Sorry if you covered this already and I forgot…

I'm not 100% sure on this one yet. I have been researching it and will post updates.
