### ISSUE TITLE
Incorrect logging level set for message in ldap.c? 

### ISSUE THREAD

**Issue by szaydel** [Netatalk/Netatalk#76]
Looking at this line: https://github.com/Netatalk/Netatalk/blob/master/libatalk/acl/ldap.c#L386
which is a log message being generated:
```
LOG(log_error, logtype_default, "ldap_getnamefromuuid: uuid_string: %s", *uuid_string);
```
... what is it about this block of code which results in this being logged as an error? I am not sure I see anything there that suggests this are of code is entered under some erroneous condition. And if this is not an error, perhaps this really should be informational instead? Thanks!

**Comment by szaydel** [comment]
Just wanted to bump this issue. I am not sure this is really an error, and fix is rather quick/easy.

**Comment by andy-js** [comment]
The fix has already gone in.

- Andy.

**Comment by szaydel** [comment]
Thanks for confirming. I noticed and dropped the branch in my clone.
