### ISSUE TITLE
GitLab CI: Build with Spotlight in the Solaris job

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#799]
This is to get a working Tracker / SparQL environment for Spotlight support in Solaris compiling in the GitLab CI environment.

**Comment by rdmark** [comment]
The `tracker` package gets you Tracker v2.0 with SparQL which seems complete with development headers.

**Comment by rdmark** [comment]
My current blocker is linking with a dynamic libtalloc.so. I tried building from source, and got the build system to recognize the library and header, i.e. with `TALLOC_LIBS="-L/usr/local/lib" TALLOC_CFLAGS="-I/usr/local/include"` and autotools.

But I run into undefined symbols errors for symbols that are clearly in the compiled library.

**Comment by dgsga** [comment]
Spotlight support compiles successfully on Solaris 11.4.42  by compiling and installing talloc from source beforehand. But it is never going to work on the Solaris VM until the latter is updated upstream. The current VM only has python2.7 which is too old to allow the talloc waf configure script to run successfully. So no talloc = no spotlight.

**Comment by rdmark** [comment]
It's that old, huh? Thanks for documenting the theoretical steps in the PR. I wanted to get it working locally too, of course, in order to update the old Spotlight docs in the install manual page.

**Comment by rdmark** [comment]
I fleshed out the Solaris wiki page: https://github.com/Netatalk/netatalk/wiki/Installing-Netatalk-3-on-Solaris

We can also decisively remove or update the aging Solaris specific instructions on https://netatalk.io/stable/htmldocs/installation

**Comment by rdmark** [comment]
Discarding this for now. The state of the vmactions VM is out of our control
