### ISSUE TITLE
Japanese localization of manual

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#806]
There exists a Japanese localization of the Netatalk 3.1 manual, git repo hosted at https://ja.osdn.net/projects/netatalk-doc-ja/scm/git/netatalk-doc-ja/

The localization was last updated for 3.1.11 on 2017-03-21. The html pages used to be hosted on osdn.jp but went dark some time after September 2019 according to the Wayback Machine.

http://web.archive.org/web/20190906114604/http://netatalk-doc-ja.osdn.jp/3.1/htmldocs/

I want to explore restoring the hosting and eventually bringing it up to date with 3.1.18 and beyond.

In the long term, instead of translating copies of the XML sources, it might be worth investigating i18n frameworks for XML.

**Comment by rdmark** [comment]
@hat001 @eiichirou If I'm not mistaken, you are the original authors of the Japanese localization. Would you have any objections to hosting the manual pages on https://netatalk.io ?

**Comment by eiichirou** [comment]
@rdmark 
Thank you for taking care of Japanese users :-)
Surely, I have no objection about above.
@rdmark , do you have resources of ja-translated-docs?
If you have any trouble, ask me anything.
I have a copy of git tree on local PC.
Regards.

**Comment by rdmark** [comment]
@eiichirou Thank you for the kind offer!

Luckily, the git hosting on osdn.net is still live. I was able to clone this remote: `http://scm.osdn.net/gitroot/netatalk-doc-ja/netatalk-doc-ja.git`

After some downtime, the html pages are now live again, freshly generated from docbook XML: https://netatalk.io/3.1/htmldocs/ja/

I also made a mirror repo in GitHub: https://github.com/Netatalk/netatalk-doc-jp

**Comment by hat001** [comment]
@rdmark
I also have no objection.
Who will maintain it in the future?
I no longer use Netatalk.
