### ISSUE TITLE
[2.4] Missing rresvport() in Alpine

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#865]
Only with 2.4, and only with meson, stdint.h type declarations aren't present:

```
In file included from ../libatalk/unicode/utf16_case.c:12:
../include/atalk/unicode.h:83:5: error: unknown type name 'u_int32_t'
   83 |     u_int32_t flags;
      |     ^~~~~~~~~
```

etc.

**Comment by dgsga** [comment]
@rdmark, if we apply PR #902 to the 2.4 codebase we get to the root of the problem. It's not that meson cannot find the stdint.h header in /usr/include, it's that the Alpine version of stdint.h does not contain the rresvport() function (which is deprecated) for security reasons. Hence the build of [2.4] now fails further on when compiling /etc/papd/lp.c with an undefined reference to 'rresvport'. If we can fix this I'm pretty sure the Alpine build of 2.4 will complete. Any ideas?

**Comment by rdmark** [comment]
@dgsga Excellent sleuthing job! The `rresvport()` function is only used by the lpr/lpd printing system interface for papd, which is arguably legacy and hardly used (as compared to CUPS.)

I wonder why the lpd connection needs to use the unsafe port reservation? My reading of rresvport() is that it allows a non-root process to reserve a privileged (<1024) port. I *think* we can expect papd to run as root, and that we can use normal `bind()` to reserve the port (as is done elsewhere in the netatalk codebase.)

@NJRoadfan do you have any insights here?

**Comment by NJRoadfan** [comment]
The only solid reference I can find to `rresvport()` is that it is required for RFC 1179 compliant implementations of lpd. The lpd back end of CUPS actually re-implements this instead of using a system's implementation. See `cups_rresvport()` in https://github.com/OpenPrinting/cups/blob/master/backend/lpd.c#L545

Additionally, older versions of CUPS used a macro to detect if the host had `rresvport()` and used its own implementation if it wasn't found. This PR ended that practice: https://github.com/OpenPrinting/cups/commit/a6a4a2f5b69eace9fb07f281bbdc4ed4c2f13c27

**Comment by rdmark** [comment]
@NJRoadfan This looks like a perfectly solid reference...

I think we should follow the CUPS example and just supply our own implementation. INAL, but to my best knowledge the Apache 2.0 license is very permissive so it should be feasible to take the `cups_rresvport()` implementation verbatim and distribute it with netatalk.

**Comment by dgsga** [comment]
> The only solid reference I can find to `rresvport()` is that it is required for RFC 1179 compliant implementations of lpd. The lpd back end of CUPS actually re-implements this instead of using a system's implementation. See `cups_rresvport()` in https://github.com/OpenPrinting/cups/blob/master/backend/lpd.c#L545
> 
> Additionally, older versions of CUPS used a macro to detect if the host had `rresvport()` and used its own implementation if it wasn't found. This PR ended that practice (note this code has since been updated): [OpenPrinting/cups@a6a4a2f](https://github.com/OpenPrinting/cups/commit/a6a4a2f5b69eace9fb07f281bbdc4ed4c2f13c27)

@NJRoadfan, Thanks for the great detective work...

**Comment by dgsga** [comment]
@rdmark and @NJRoadfan, please can you take a peek at draft PR #920. Unfortunately I have no way of testing if the rresvport function for must systems works correctly.

**Comment by NJRoadfan** [comment]
I'll see if I can test it. Its tough as everyone has moved away from LPR to CUPS. I suspect that rresvport might be going away from more platforms in the future though.

**Comment by rdmark** [comment]
I don't have an obvious way to test lpr printing myself either.

I feel bad saying this after @dgsga spent all this effort, but one option would be to make papd depend on cups, and leverage their lpr/lpd interface instead. But TBH I don't know enough right now to say whether this is a good idea or not.

**Comment by NJRoadfan** [comment]
OK, I built the PR (netatalk 2.4dev with meson under Alpine Linux) without CUPS support (the rresvport() call will never happen if CUPS support is enabled). I can print ok by manually configuring a printer (ironically a CUPS queue). I noticed the code in question only gets triggered if using (UMICH?) authentication and if you want to remove a job from a queue. I'll play around with it, but I can't guarantee I'll be able to thoroughly test this code. Ugh.

**Comment by NJRoadfan** [comment]
I think I figured out what these commands are for in papd. There appears to have been a Chooser extension written to allow one to view and delete queued files on a papd server: https://websites.umich.edu/~rsug/netatalk/archive/admins/1995/0007.html

That Chooser extension is what calls the functions that calls `rresvport()`. Doesn't help that we don't have a name of this extension or source.... or anything outside of that nearly 30 year old listserv post!

**Comment by rdmark** [comment]
Holy internet archeology, Batman!

Going further down that rabbit hole, someone posted this a few months later, talking about a *Print Queue* RDEV which **may** be the same RDEV that Robert was developing..

https://websites.umich.edu/~rsug/netatalk/archive/admins/1995/0066.html

But then again, it might simply be the one in the SuperSpool package:

https://macintoshgarden.org/apps/superspool-50

Another potential lead could be *Choosier*, a contemporaneous Chooser replacement also by folks at UMich.

http://web.archive.org/web/19961220150401/http://www.umich.edu/~rsug/choosier/

The ftp server hosting the software itself is unfortunately not archived, but archive.org at least has a screenshot of the app saved. :)

![choosier](https://github.com/Netatalk/netatalk/assets/2108467/c963288b-6bb9-42f9-a785-1d9b74864842)

**Comment by rdmark** [comment]
Some helped me track down Choosier!

https://macgui.com/downloads/?file_id=19347
