### ISSUE TITLE
OpenSSL 1.1 support

### ISSUE THREAD

**Issue by hat001** [Netatalk/Netatalk#87]
Netatalk currently does not build against OpenSSL 1.1.

https://wiki.openssl.org/index.php/1.1_API_Changes

**Comment by hat001** [comment]
OpenSSL 1.1.x compatibility #86 
https://github.com/Netatalk/Netatalk/pull/86

**Comment by hat001** [comment]
Fixed in 3.1.11

**Comment by cactus** [comment]
This seems to break building with LibreSSL.

From libressl:
```
opensslv.h:#define OPENSSL_VERSION_NUMBER	0x20000000L
```

I think you might want this for the version check instead?

```
#if OPENSSL_VERSION_NUMBER < 0x10100000L || defined(LIBRESSL_VERSION_NUMBER)
```

**Comment by hat001** [comment]
This ticket is closed already.
Go to new ticket https://github.com/Netatalk/Netatalk/issues/91 .
