### ISSUE TITLE
Configure summary is broken when PAM is missing

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#872]
In the absence of PAM, I think the configure summary should say "shadow" for the applicable UAMs. However we're getting empty parentheses. Meson and autotools behaves the same in this regard.

```
    UAMS:
      Kerberos V               : NO
      PGP                      : YES
      Randnum                  : (afppasswd)
      clrtxt                   : ()
      guest                    : YES
      DHX                      : ()
      DHX2                     : ()
```

Easily observed on OpenBSD which lacks PAM out of the box. You can even see it in our GitHub actions logs.

As a side note, installing `openpam` on OpenBSD results in a proper summary.

```
    UAMS:
      Kerberos V               : NO
      PGP                      : YES
      Randnum                  : (afppasswd)
      clrtxt                   : (PAM)
      guest                    : YES
      DHX                      : (PAM)
      DHX2                     : (PAM)
```

**Comment by dgsga** [comment]
@rdmark, my understanding is that it's not **either** PAM **or** SHADOW. Some systems have the PAM headers and library, some have the shadow.h header, some have both and some have neither...

**Comment by rdmark** [comment]
That’s fair. The build system can build both shadow and pam, but in the end only one or the other will be symlinked to .so files that netatalk read, e.g. 

```
uams_clrtxt.so -> uams_pam.so
uams_dhx.so -> uams_dhx_pam.so
uams_dhx2.so -> uams_dhx2_pam.so
```
