### ISSUE TITLE
Remove unused function 'evutil_secure_rng_add_bytes', fixing build on SmartOS.

### ISSUE THREAD

**Issue by hat001** [Netatalk/Netatalk#89]
Matt Connolly said:

Remove unused function 'evutil_secure_rng_add_bytes', fixing build on SmartOS.

This function was not used anywhere in netatalk. Additionally, it
was calling arc4random_addrandom() which is apparently notoriously
difficult to use correctly and has since been removed from OpenBSD
and SmartOS.

See: https://www.illumos.org/issues/5949

**Comment by hat001** [comment]
patch is here.
https://github.com/Netatalk/Netatalk/pull/88

**Comment by hat001** [comment]
Bundled libevent is old, maybe.

1) Install libevent.
2) Use configure option "--without-libevent".

**Comment by mattconnolly** [comment]
Well... I already had libevent installed (libevent-2.0.21nb2)... Building `--without-libevent` seems to work just fine.

Do you think there should be a test to only build with the bundled libevent if there is none provided by the system?

**Comment by hat001** [comment]
I cannot build with bundled libevent on Fedora Rawhide either.
The bundled libevent is clearly old.

CentOS 6 has libevent1 package, so bundled libevent2 is useful. Your patch is not needed because  CentOS 6 is old system.

"--without-libevent" should be default option.
The bundled libevent should be updated. (or should apply your patch.)
If system has libevent1 package, bundled libevent should be used.
If system has no libevent, libevent2 should be installed from tarball.

**Comment by andy-js** [comment]
I vote to remove libevent completely from netatalk.

**Comment by hat001** [comment]
I'm consulting developers on ML.
https://sourceforge.net/p/netatalk/mailman/message/35770458/

**Comment by slowfranklin** [comment]
On Wed, Apr 05, 2017 at 06:43:52AM -0700, HAT wrote:
> I cannot build with bundled libevent on Fedora Rawhide either.
> The bundled libevent is clearly old.
> 
> CentOS 6 has libevent1 package, so bundled libevent2 is useful. Your patch is not needed because  CentOS 6 is old system.
> 
> "--without-libevent" should be default option.

Yes, we could change this for 3.2. Though the name is a bit misleading, as we
can't build *without*. We can only choose between bundled and external.

So maybe something like

 --with-bundled-library=talloc|tdb|event

 --with-bundled-library=ALL (uses all available)

 --with-bundled-library=NONE (use external, fail if a required one is missing
   (like libevent))

similar to what we have in Samba.

> The bundled libevent should be updated. (or should apply your patch.)

yes.

Cheerio!
-slow

**Comment by slowfranklin** [comment]
On Wed, Apr 05, 2017 at 07:05:26AM -0700, Andrew Stormont wrote:
> I vote to remove libevent completely from netatalk.

replace it with what in the netatalk binary?

Cheerio!
-slow

**Comment by andy-js** [comment]
I mean remove the bundled version and make it a hard dependency.

**Comment by slowfranklin** [comment]
On Wed, Apr 05, 2017 at 07:10:46AM -0700, Andrew Stormont wrote:
> I mean remove the bundled version and make it a hard dependency.

is it available on all systems? What about Solaris 10?

Cheerio!
-slow

**Comment by andy-js** [comment]
It is if you build it yourself.

**Comment by hat001** [comment]
bundled libevent is needed for CentOS6.

**Comment by slowfranklin** [comment]
On Wed, Apr 05, 2017 at 07:32:24AM -0700, HAT wrote:
> bundled libevent is needed for CentOS6.

I absolutely hate the idea requiring our users to compile libevent themselves on
systems that lack a package.

If others think different here, you may overrule me, but imho this would be
handled better by the proposed change to the way we deal with all bundled
libraries. Now we just need someone to code up a fancy m4 macro that does
it. Anyone? :)

Until then, we can just import an updated libevent.

-slow

-- 
SerNet GmbH, Bahnhofsallee 1b, 37081 Göttingen
phone: +49-551-370000-0, fax: +49-551-370000-9
AG Göttingen, HRB 2816, GF: Dr. Johannes Loxen
http://www.sernet.de,mailto:kontakt@sernet.de

Samba eXPerience 2017, Hotel Freizeit In
2nd-4th of May 2017, http://sambaXP.org

**Comment by hat001** [comment]
> Now we just need someone to code up a fancy m4 macro that does it. Anyone? :)
I cannot do it because I don't have enough knowledge.

**Comment by slowfranklin** [comment]
On Thu, Apr 06, 2017 at 07:49:53AM -0700, HAT wrote:
> > Now we just need someone to code up a fancy m4 macro that does it. Anyone? :)
> I cannot do it because I don't have enough knowledge.

I'm lacking time to do it. Anyone else?

If not, maybe let's just bump the internal version.

-slow

-- 
SerNet GmbH, Bahnhofsallee 1b, 37081 Göttingen
phone: +49-551-370000-0, fax: +49-551-370000-9
AG Göttingen, HRB 2816, GF: Dr. Johannes Loxen
http://www.sernet.de,mailto:kontakt@sernet.de

Samba eXPerience 2017, Hotel Freizeit In
2nd-4th of May 2017, http://sambaXP.org

**Comment by hat001** [comment]
> is it available on all systems? What about Solaris 10?

What is the problem on Solaris 10?
Is compiler Solaris Studio?

**Comment by slowfranklin** [comment]
On Mon, Apr 10, 2017 at 09:40:03AM -0700, HAT wrote:
> > is it available on all systems? What about Solaris 10?
> 
> What is the problem on Solaris 10?
> Is compiler Solaris Studio?

no, but there's probably no Solaris 10 libevent package.

Cheerio!
-slow

**Comment by slowfranklin** [comment]
I prepared a branch with an updated libevent version 2.1.18:
[https://github.com/Netatalk/Netatalk/commits/libevent-2.1.18](url)
Does this fix the issue?

**Comment by hat001** [comment]
I tested it on Fedora rawhide.

<pre>
$ ./bootstrap

$ ./configure \
    --with-init-style=redhat-systemd \
    --enable-krbV-uam \
    --with-cracklib \
    --without-tdb \
    --with-pam-confdir=/etc/pam.d \
    --with-dbus-sysconf-dir=/etc/dbus-1/system.d \
    --with-dbus-daemon=/usr/bin/dbus-daemon \
    --with-tracker-pkgconfig-version=1.0 \
    --with-docbook=/usr/share/sgml/docbook/xsl-stylesheets

$ make
# make install
</pre>

<pre>
$ ldd /usr/local/sbin/netatalk | grep libevent
        libevent-2.1.so.6 => /usr/local/lib/libevent-2.1.so.6 (0x00007fb3b0dab000)
</pre>

The bundled libevent is NOT static.

**Comment by andy-js** [comment]
I agree, that's a problem.  We don't want to accidentally clobber the system libevent (which might have some distro-specific fixes) and break stuff.

**Comment by slowfranklin** [comment]
Closing this, I'll create a MR that removes the bundled libevent in a minute.
