### ISSUE TITLE
Build system puts netatalk-dbus.conf in wrong dir

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#894]
netatalk-dbus.conf should go into /etc/dbus-1/system.d/ (on Debian at least) but the build system puts it under /etc/ or /usr/local/etc/ ... haven't debugged exactly which build system and under which circumstances yet. Creating this to not forget to troubleshoot later.

**Comment by rdmark** [comment]
@dgsga Please correct me if I'm wrong, but I think the problem is that on this line we always install the dbus config with a pkgconfdir prefix, which overrides any usage in the `with-dbus-sysconf-dir` build system parameter.

https://github.com/Netatalk/netatalk/blob/777effc95a0a05c68518414f039c3b624d43d6ce/config/meson.build#L28

**Comment by dgsga** [comment]
Well spotted, fixed in PR #903
