### ISSUE TITLE
LibreSSL Support

### ISSUE THREAD

**Issue by hat001** [Netatalk/Netatalk#91]
cactus said at https://github.com/Netatalk/Netatalk/issues/87#issuecomment-302267528

This seems to break running with LibreSSL.

I get this in the error logs

```
uam_load(uams_dhx.so): failed to load: /usr/local/libexec/netatalk-uams//uams_dhx.so: Undefined symbol "DH_set0_pqg"
```

From libressl you can see the version is higher:
```
opensslv.h:#define OPENSSL_VERSION_NUMBER	0x20000000L
```

I think you might want something like this for the version check instead?

```
#if OPENSSL_VERSION_NUMBER < 0x10100000L || defined(LIBRESSL_VERSION_NUMBER)
```

**Comment by hat001** [comment]
Did you test this patch?

By what environment did you test?
OpenBSD?

**Comment by cactus** [comment]
Currently testing the patch. So far, it compiles fine and starts up without the previous error.
System is FreeBSD.

**Comment by cactus** [comment]
Patch appears to be working. I have time machine backups running properly again (had to rollback to a snapshot a few days ago though).

**Comment by hat001** [comment]
Please attach the patch file.

**Comment by cactus** [comment]
[etc_uams_openssl__compat.h.diff.txt](https://github.com/Netatalk/Netatalk/files/1015057/etc_uams_openssl__compat.h.diff.txt)

**Comment by hat001** [comment]
Just in case, I tested your patch on the following environments.

* Fedora 25 (OpenSSL 1.0.2k)
* Fedora 26 alpha (OpenSSL 1.1.0e)

It was no problem.
I'm going to create a patch for git.

**Comment by hat001** [comment]
See Netatalk-devel ML
https://sourceforge.net/p/netatalk/mailman/message/35855444/

**Comment by hat001** [comment]
committed.
thanks!
