### ISSUE TITLE
[2.4] Substitution of "machinename" in netatalk.conf

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#928]
The default netatalk.conf has this section:

```
#### machine's AFPserver/AppleTalk name.
#ATALK_NAME=machinename
```

The ATALK_NAME env variable is used by rc/sysv init scripts to register NBP entries, etc.

1) we should not comment this out by default and
2) we should substitute "machinename" for the actual hostname of the machine through the build system

Example output for illustration:

```
 * Caching service dependencies ...                                                                            [ ok ]
 * Starting atalkd ...                                                                                         [ ok ]
 *   Registering machinename:Workstation ...                                                                   [ ok ]
 *   Registering machinename:netatalk ...                                                                      [ ok ]
 *   Starting papd ...                                                                                         [ ok ]
 *   Starting timelord ...                                                                                     [ ok ]
 *   Starting a2boot ...                                                                                       [ ok ]
 * Starting cnid_metad ...                                                                                     [ ok ]
 * Starting afpd ...                                                                                           [ ok ]
alpine:~/netatalk2$ nbplkup 
                    machinename:AFPServer                          65280.197:131
                         alpine:Apple //gs                         65280.197:3
                         alpine:TimeLord                           65280.197:128
                    machinename:netatalk                           65280.197:4
                    machinename:Workstation                        65280.197:4
                         alpine:Apple //e Boot                     65280.197:3
```

**Comment by NJRoadfan** [comment]
For some reason, this commit removed setting the host name: https://github.com/Netatalk/netatalk/commit/7f9fdfa28c00b0d5fa37f81af35fd0a8110dcbdf

This is how Debian (used to?) set it, based on an old netatalk.conf found in the A2SERVER tree.
```
ATALK_NAME=`/bin/hostname --short`
```

**Comment by rdmark** [comment]
Ah, of course, I kind of broke this with my commit in https://github.com/Netatalk/netatalk/commit/d13f5d1e8c65a04a37b5ea197279bb10db0bf920

Each rc script used to have their own platform specific shell script logic override that I removed:

Debian

```
ATALK_NAME=`/bin/hostname --short`
```

Gentoo

```
ATALK_NAME=`echo ${HOSTNAME}|cut -d. -f1`
```

Redhat

```
ATALK_NAME=`echo ${HOSTNAME}|cut -d. -f1`
```

Solaris

```
ATALK_NAME=`hostname|cut -d. -f1`
```

SUSE

```
ATALK_NAME=`hostname|sed 's/\..*$//'`
```

**Comment by NJRoadfan** [comment]
The issue is.... hostnames are easily changed after a build, particularly if the system comes up and there is a conflict. I already had to do it once on a VM. The programmatic method of retrieving it from the system makes sense. I'm actually surprised that timelord and a2boot get the host name properly without it set in netatalk.conf, but afpd isn't. I'm not seeing that problem on a Debian systemd install or an Alpine Linux install (only registering Workstation and netatalk with nbprgstr relies on it and fails without it set).

```
/home/user1 # nbplkup
                     alpinetest:ProDOS16 Image                     65280.24:3
                     alpinetest:Apple //e Boot                     65280.24:3
                     alpinetest:TimeLord                           65280.24:130
                     alpinetest:AFPServer                          65280.24:133
                        CUPSPDF:LaserWriter                        65280.24:128
                     alpinetest:Apple //gs                         65280.24:3
```

**Comment by rdmark** [comment]
@NJRoadfan Bringing back the old behavior with some tweaks in https://github.com/Netatalk/netatalk/pull/935
