### ISSUE TITLE
Possible service registering bug with mdns

### ISSUE THREAD

**Issue by omor1** [Netatalk/netatalk#93]
There is a possible bug when using DNS-SD/mDNS instead of Avahi for Zeroconf. In [lines 237 through 304 of etc/netatalk/afp_mdns.c](../blob/master/etc/netatalk/afp_mdns.c#L237-L304), several services are registered: `_afpovertcp._tcp`, `_adisk._tcp`, and `_device-info._tcp`. [Documentation](https://developer.apple.com/documentation/dnssd/1804733-dnsserviceregister) for `DNSServiceRegister()` states that

> The port, in network byte order, on which the service accepts connections. Pass 0 for a "placeholder" service (that is, a service that will not be discovered by browsing, but will cause a name conflict if another client tries to register that same name).

However, both the `_afpovertcp._tcp` service and the `_adisk._tcp` attempt to register over the AFP port (taken from options). `_device-info._tcp` registers on port 9. Avahi ([etc/netatalk/afp_avahi.c](../blob/master/etc/netatalk/afp_avahi.c)) registers `_adisk._tcp` on port 9, `_device-info._tcp` on port 0, and `_afpovertcp._tcp` over the AFP port.

I don't know whether this actually causes problems or if the `DNSServiceRegister()` documentation is incorrect—I just noticed this discrepancy while browsing the code (I was looking into implementing similar functionality in Samba, now that AFP is being deprecated and SMB preferred for Time Machine). If someone could check and see whether this is actually a problem or just incorrect documentation, it would be appreciated. Of note is that Avahi does not have this limitation—it is neither documented in their equivalent `avahi_entry_group_add_service()` nor is it an undocumented limitation, seeing as I have a service definition file with both `_device-info._tcp` and `_adisk._tcp` on port 0 that works correctly.

On a side note, is this the correct place for this? I wasn't able to find a contribution guide or anything of that sort on the Netatalk website.

**Comment by slowfranklin** [comment]
Can we check what ports macOS uses for the respective services? Guess we must use the same ports anyway, regardless of what other specs or API documentations state. Iirc we ARE already using the same ports as macOS, but checking this to make sure won't hurt. :-)

Btw, the Netatalk project home is still on Sourceforge:
[https://sourceforge.net/projects/netatalk/](url)
There are the mailing lists for discussion:
[https://sourceforge.net/p/netatalk/mailman/](url)

**Comment by rdmark** [comment]
A little bit of git archeology revealed that the port for `_device-info._tcp` was changed from 0 to 9 because of this bug report:

https://sourceforge.net/p/netatalk/bugs/443/

With this commit from Oct 2012:

https://github.com/Netatalk/netatalk/commit/d202fc4ee109f920ec222cb8fd723f48f3803754

It should be worth revisiting Solaris's mDNS today and test this out again, and compare with mDNS on macOS (since netatalk happily runs on Sonoma now.)

The test case for `_device-info._tcp` is the mimicmodel setting. When mounted in the macOS Network tray, you should get the appropriate icon.

**Comment by rdmark** [comment]
Testing the latest netatalk main code running on Solaris 11.4 and macOS Sonoma, using their respective mDNS implementations, I can only conclude that the current port assignments are required for `_device-info._tcp` to work in reality. I think we should keep the current code even though it strictly speaking contradicts the spec.
