### ISSUE TITLE
Deprecate cracklib support

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#930]
This is to discuss the removal of cracklib support (in both main and 2.x) from afppasswd, and by extension the RandNum UAM.

Maintaining cracklib support in a cross-platform compatible way has proven costly, and hardly worth the effort.

It supports a niche of a niche of a niche usecase at this point... The RandNum UAM is really only for providing a modicum of encryption for Apple IIe / IIGS / Mac System Software 6 and early 7 clients. And increasing the password strength when the max length is 8 characters, in 56bit encryption, makes hardly any difference at all IMHO.

**Comment by dgsga** [comment]
I think we should keep it as there will be enthusiasts out there who have very old vintage macs. As a rule I think we should only deprecate features related to vintage host operating systems, not vintage client ones :)

**Comment by rdmark** [comment]
Alright, since you're volunteering to keep the build system working... ;)
