### ISSUE TITLE
[2.4] AppleTalk service missing errors on Alpine

### ISSUE THREAD

**Issue by rdmark** [Netatalk/netatalk#945]
Distribution of services.atalk was removed in https://github.com/Netatalk/netatalk/commit/bda82747ba63bebe72e202187c6f4036f71fbce2

I think it should be restored

**Comment by NJRoadfan** [comment]
looks like it was just moved to the /config directory.

**Comment by rdmark** [comment]
Well, the file itself still exists, but the build system doesn't process it...

**Comment by NJRoadfan** [comment]
I'll have to check a clean install to see if it comes with the distro, but I am seeing the entries in `services.atalk` in `/etc/services` post netatalk install.

**Comment by rdmark** [comment]
Hm, you're right I'm seeing 'em all except for "afpovertcp	548/udp" in my Alpine VM too... I wonder why I was getting those errors the other day, then..? Maybe I hadn't installed netatalk2 yet at that point?

**Comment by NJRoadfan** [comment]
This appears to be an Alpine Linux issue of some sort. I am not getting the "service missing" errors on a Debian install. Somehow `getservbyname()` is returning NULL on Alpine even though the services are present in `/etc/services`.

**Comment by NJRoadfan** [comment]
OK, found the problem. The musl implementation of `getservbyname_r()` only supports passing `tcp` or `udp` as the protocol type. Type `ddp` (or anything else) is not supported.

**Comment by rdmark** [comment]
That explains it! DDP seems to work anyways, so I'm not sure what effect this has in reality?

**Comment by rdmark** [comment]
I have not seen this occur again. Closing.
